### ISSUE TITLE
Git-Credential-Manager crashes in WSL2 in Windows Terminal in quake mode

### ISSUE THREAD

**Issue by Nosamdaman** [microsoft/WSL#10284]
### Windows Version

10.0.22621.0

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04.6 LTS

### Other Software

git 2.25.1
git-credential-manager 2.2.1 (installed on Windows via git-for-windows v2.41.0.windows.2)

### Repro Steps

1. Open a Windows Terminal instance normally
2. Launch Windows Terminal in quake mode using ``` Win + ` ```
3. Close the original, normal terminal instance
4. Open WSL2 Ubuntu in the quake mode instance
5. Attempt any git action that requires remote authentication (ie `git pull`)

### Expected Behavior

The pull should work without issue as it does when the terminal isn't in quake mode

### Actual Behavior

git-credential-manager core crashes as follows:
```
>> git pull

Unhandled Exception: System.ComponentModel.Win32Exception: Only part of a ReadProcessMemory or WriteProcessMemory request was completed
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at GitCredentialManager.CommandContext.GetEntryApplicationPath()
   at GitCredentialManager.CommandContext..ctor()
   at GitCredentialManager.Program.AppMain(Object o)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Username for '<LOCAL_GIT_SERVER>': ^C⏎    
```

Note that the shell prompt and hostname of our remote server have been removed for privacy reasons.

**Comment by Nosamdaman** [comment]
Note that this issue was cross-posted to this repo after I reported it to the wt guys [here](https://github.com/microsoft/terminal/issues/15698)

**Comment by pmartincic** [comment]
Has this been filed against the git credential manager bug tracker? I'm not sure how either us or the windows terminal guys are an appropriate first stop for this issue? It not time effective for us to triage crashes in other projects that we don't work on.
