### ISSUE TITLE
VS Code Remote SSH Repeatedly Asks for User Password But Fails to Connect 

### ISSUE THREAD

**Issue by Perry31** [microsoft/WSL#10396]
Below is the environment and configs I'm using,
 **- WSL 2
 - Ubuntu 22.04
 - I used IPv6 IP since IPv4 IP is not working.
 **
I've tried using the details provided in this ticket https://github.com/microsoft/vscode-remote-release/issues/6150, still issue is not resolved.

**Below is the log for the error,**

[13:18:04.305] Showing password prompt
[13:18:09.337] Got password response
[13:18:09.338] "install" wrote data to terminal: "******"
[13:18:09.372] > 
[13:18:12.343] > Permission denied, please try again.
[13:18:12.359] > root@fe80::87be:f9b4:d731:3c9e's password: 
[13:18:12.360] Showing password prompt
[13:18:16.257] Got password response
[13:18:16.257] "install" wrote data to terminal: "******"
[13:18:16.278] > 
[13:18:37.649] > ssh_dispatch_run_fatal: Connection to fe80::87be:f9b4:d731:3c9e port 22: Connect
> ion timed out
[13:18:37.670] > The process tried to write to a nonexistent pipe.
[13:18:38.948] "install" terminal command done
[13:18:38.948] Install terminal quit with output: ion timed out
[13:18:38.948] Received install output: ion timed out
[13:18:38.949] Failed to parse remote port from server output
[13:18:38.951] Resolver error: Error: 
	at m.Create (c:\Users\testuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584145)
	at t.handleInstallOutput (c:\Users\testuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:582705)
	at t.tryInstall (c:\Users\testuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:681881)
	at async c:\Users\testuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:644110
	at async t.withShowDetailsEvent (c:\Users\testuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:647428)
	at async t.resolve (c:\Users\testuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:645160)
	at async c:\Users\testuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:720916
[13:18:38.959] ------

**Comment by pmartincic** [comment]
I don't think this is the right repo to file this bug against. In the future when you do file bugs against us please use the template and provide us with logs.
