### ISSUE TITLE
Can not seek to real end of file after write() without flush() for BufferedWriter in python3.8

### ISSUE THREAD

**Issue by Hypothesis-Z** [microsoft/WSL#10477]
### Windows Version

Microsoft Windows [Version 10.0.19045.3448]

### WSL Version

not sure

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Other Software

ROS noetic
python3.8

### Repro Steps

```shell
rosbag filter xxx.bag -t start end
```
or other instructions of writing a rosbag.

for example:
```python
import rosbag
import rospy

def exchange_topics(input_bagfile, output_bagfile, topic1, topic2):
    with rosbag.Bag(output_bagfile, 'w') as outbag:
        for topic, msg, t in rosbag.Bag(input_bagfile).read_messages():
            if topic == topic1:
                new_topic = topic2
            elif topic == topic2:
                new_topic = topic1
            else:
                new_topic = topic

            outbag.write(new_topic, msg, t)

if __name__ == "__main__":
    input_bagfile = "/path/to/input.bag"  # Replace with the path to the input bagfile
    output_bagfile = "/path/to/output.bag"  # Replace with the path to the output bagfile
    topic1 = "/topic1"  # Replace with the first topic to be exchanged
    topic2 = "/topic2"  # Replace with the second topic to be exchanged

    exchange_topics(input_bagfile, output_bagfile, topic1, topic2)
```

more infomation: 
https://github.com/ros/ros_comm/issues/2339

### Expected Behavior

No error.

### Actual Behavior

```shell
Traceback (most recent call last):
  File "exchange_uwb_topic_name.py", line 36, in <module>
    process(outbag, topic, msg, t)
  File "exchange_uwb_topic_name.py", line 18, in process
    bag.write(topic, msg, t)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 704, in write
    self._stop_writing_chunk()
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 1664, in _stop_writing_chunk
    self._write_connection_index_record(connection_id, entries)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 1744, in _write_connection_index_record
    buffer.write(_pack_uint32(entry.offset))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 1940, in _pack_uint32
    def _pack_uint32(v): return struct.pack('<L', v)
struct.error: argument out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exchange_uwb_topic_name.py", line 36, in <module>
    process(outbag, topic, msg, t)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 478, in __exit__
    self.close()
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 719, in close
    self._stop_writing()
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 1587, in _stop_writing
    self.flush()
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 579, in flush
    self._stop_writing_chunk()
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 1664, in _stop_writing_chunk
    self._write_connection_index_record(connection_id, entries)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 1744, in _write_connection_index_record
    buffer.write(_pack_uint32(entry.offset))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosbag/bag.py", line 1940, in _pack_uint32
    def _pack_uint32(v): return struct.pack('<L', v)
struct.error: argument out of range
```

### Diagnostic Logs

I checked the traceback and found out that the error is produced by a wrong action of `self._file.seek(0, os.SEEK_END)`. The program seeks to a wrong place where data has been written via calling `self._file.write(data)`. Should `self._file.flush()` be added after writing, no error occurs. However, in native Ubuntu OS, I don't need to flush the buffer before letting it seek to a new position.

**Comment by OneBlue** [comment]
Thank you for reporting this @Hypothesis-Z. Which files are you reading / writing ? Is this under /mnt ?

**Comment by Hypothesis-Z** [comment]
@OneBlue Yes, I am writing to files under /mnt.

**Comment by OneBlue** [comment]
Ok thank you. Could you share an strace of both a successful and failing scenario so I can compare them ?
