### ISSUE TITLE
Turning on networkingMode=mirrored does not run code with PyCharm

### ISSUE THREAD

**Issue by LH667371** [microsoft/WSL#10695]
Windows Version
10.0.22621.2506

WSL Version
2.0.7.0

Kernel Version
5.15.133.1-1

Distro Version
Ubuntu 20.04

Other Software
PyCharm 2023.2.3 (Professional Edition)

Repro Steps
Turn on networkingMode=mirrored; can't use PyCharm to invoke WSL's Python environment to run code.

Expected Behavior
The code runs normally and there is an output log.

Actual Behavior
![1698718162101_042E21A0-6E0E-4b3f-B425-A72F6A8C80B0](https://github.com/microsoft/WSL/assets/49465892/c45aa424-d2d2-4bdd-af6a-ab98df11d47d)

A look at idea.log reveals the following error
2023-10-31 10:03:42,862 [1040478]   INFO - #c.i.e.wsl - WSL mount root for Ubuntu-20.04 is /mnt/ (done in 162 ms)
2023-10-31 10:03:43,171 [1040787]   INFO - #c.i.e.r.ExecutionUtil - Error running '1017':<br>wslproxy closed stream unexpectedly. See idea.log for errors
java.lang.Exception: wslproxy closed stream unexpectedly. See idea.log for errors
	at com.intellij.execution.wsl.WslProxy.readToBuffer(WslProxy.kt:107)
	at com.intellij.execution.wsl.WslProxy.access$readToBuffer(WslProxy.kt:37)
	at com.intellij.execution.wsl.WslProxy$readToBuffer$1.invokeSuspend(WslProxy.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.execution.wsl.WslProxy.<init>(WslProxy.kt:129)
	at com.intellij.execution.wsl.target.WslTargetEnvironment.getWslPort(WslTargetEnvironment.kt:96)
	at com.intellij.execution.wsl.target.WslTargetEnvironment.<init>(WslTargetEnvironment.kt:83)
	at com.intellij.execution.wsl.target.WslTargetEnvironmentRequest.prepareEnvironment(WslTargetEnvironmentRequest.kt:51)
	at com.jetbrains.python.run.PythonCommandLineState.startProcess(PythonCommandLineState.java:342)
	at com.jetbrains.python.run.PythonCommandLineState.execute(PythonCommandLineState.java:234)
	at com.jetbrains.python.run.PythonScriptCommandLineState.execute(PythonScriptCommandLineState.java:147)
	at com.jetbrains.python.run.PythonCommandLineState.execute(PythonCommandLineState.java:180)
	at com.jetbrains.python.run.PythonRunner.lambda$execute$2(PythonRunner.java:67)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: kotlinx.coroutines.channels.ClosedReceiveChannelException: Unexpected EOF: expected 4 more bytes
	at io.ktor.utils.io.ByteBufferChannel.readFullySuspend(ByteBufferChannel.kt:580)
	at io.ktor.utils.io.ByteBufferChannel.access$readFullySuspend(ByteBufferChannel.kt:24)
	at io.ktor.utils.io.ByteBufferChannel$readFullySuspend$1.invokeSuspend(ByteBufferChannel.kt)
	... 25 more
2023-10-31 10:03:44,171 [1041787]   WARN - #c.i.e.w.WslProxy - Exit code was 255
2023-10-31 10:03:44,514 [1042130]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities to files
2023-10-31 10:04:46,465 [1104081]   INFO - #c.j.p.PyToolWindowLayoutProvider - Python default layout applied
2023-10-31 10:04:56,343 [1113959]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities to files

**Comment by craigloewen-msft** [comment]
Ah I think this could be due to PyCharm not knowing about mirrored mode networking. Could you please file a bug in the PyCharm interface asking them to support it? (I will also file a bug with them). I'll keep this issue open to track this bug.

**Comment by LH667371** [comment]
> Ah I think this could be due to PyCharm not knowing about mirrored mode networking. Could you please file a bug in the PyCharm interface asking them to support it? (I will also file a bug with them). I'll keep this issue open to track this bug.

Okay, I'll go to the official PyCharm for feedback on my end as well.

**Comment by LH667371** [comment]
I have given feedback about the problem, and then again over there in the forum found that the software communication are judged eth0 network card, this time I open the VPN, WSL eth0 also created, this time running can be normal, I do not know if the mirror mode can be used by default eth0 or Pycharm side to modify the fixed use of eth0, I think you can contact to determine how to solve.
![image](https://github.com/microsoft/WSL/assets/49465892/762e1f50-c3c1-4643-b68b-9f9c22d28e18)

**Comment by LH667371** [comment]
The official reply to the current solution is to turn on this switch via Pycharm.
Currently the workaround is: Help->Find Actions->Registry->wsl.proxy.connect.localhost: true(check the box)
![image](https://github.com/microsoft/WSL/assets/49465892/c73f52ac-c783-42eb-a10d-fc5c1addae02)

**Comment by mgarber-ops** [comment]
I thought the experimental flag of mirrored networking was only available on a preview build of win 11?

**Comment by mgarber-ops** [comment]
> I thought the experimental flag of mirrored networking was only available on a preview build of win 11?

https://learn.microsoft.com/en-us/windows/wsl/wsl-config#experimental-settings

**Comment by LH667371** [comment]
> > I thought the experimental flag of mirrored networking was only available on a preview build of win 11?
> 
> https://learn.microsoft.com/en-us/windows/wsl/wsl-config#experimental-settings

It was supported after getting the latest system update before, then updating the preview version of wsl will work, if not it will switch to the old network mode on startup.

**Comment by amorZhu** [comment]
> 对当前解决方案的官方回复是通过 Pycharm 打开此开关。目前解决方法是：Help->Find Actions->Registry->wsl.proxy.connect.localhost： true（选中该框） ![图像](https://user-images.githubusercontent.com/49465892/280167937-c73f52ac-c783-42eb-a10d-fc5c1addae02.png)

good

**Comment by myname-dyh** [comment]
I can't find this key in registry. How do I add it?
![image](https://github.com/microsoft/WSL/assets/102351368/d2b919db-d6ad-4261-b00d-029ab55ce283)

**Comment by Danrusty** [comment]
> I can't find this key in registry. How do I add it? ![image](https://private-user-images.githubusercontent.com/102351368/289729067-d2b919db-d6ad-4261-b00d-029ab55ce283.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NzU4MjYsIm5iZiI6MTcwNjY3NTUyNiwicGF0aCI6Ii8xMDIzNTEzNjgvMjg5NzI5MDY3LWQyYjkxOWRiLWQ2YWQtNDI2MS1iMDBkLTAyOWFiNTVjZTI4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQwNDMyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2ZkZTMxNTY3YjYyMjc0ZGU0OTg1N2MzMWQwZDJkMjc3MmUwODJlN2ExNDIyNjlhMGI0ZTc2ZDAwYThlY2E0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SBoSd6cPGHUv4phr6k2esiYzUu9PDFMGjTYC1O9yKyU)

Just update the PyCharm to the latest version. I encountered the same problem as you. Then I updated the PyCharm from 2023.1 to 2023.3.3 and problem was solved.
