### ISSUE TITLE
OpenGl cannot work on WSL2

### ISSUE THREAD

**Issue by Javacr** [microsoft/WSL#10719]
### Windows Version

Microsoft Windows [Version 10.0.19044.2846]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu-20.04

### Repro Steps

OpenGL cannot be used in my WSL2, I have  tried any solution that I can search.
declaration: `xeyes` is ok in my WSL2.
my driver can be detected, and I already run  many projects that rely on pytorch-gpu:
```
(base) jim@DESKTOP-9F1UKHC:~$ nvidia-smi
Tue Nov  7 00:48:37 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 516.94       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
|  0%   48C    P8    40W / 370W |   1407MiB / 12288MiB |     13%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```
case 1: when `export LIBGL_ALWAYS_INDIRECT=0`, `glxinfo -B` and `glxgears` both return `Segmentation fault`
```
(base) jim@DESKTOP-9F1UKHC:~$ export LIBGL_ALWAYS_INDIRECT=0
(base) jim@DESKTOP-9F1UKHC:~$ glxinfo -B
name of display: 172.28.144.1:0
Segmentation fault
(base) jim@DESKTOP-9F1UKHC:~$ glxgears
Segmentation fault
```
case 2: when `export LIBGL_ALWAYS_INDIRECT=1`, `glxinfo -B` return `X Error of failed request:  GLXBadCurrentWindow` , but glxgears works.
```
(base) jim@DESKTOP-9F1UKHC:~$ export LIBGL_ALWAYS_INDIRECT=1
(base) jim@DESKTOP-9F1UKHC:~$ glxinfo -B
name of display: 172.28.144.1:0
display: 172.28.144.1:0  screen: 0
direct rendering: No (LIBGL_ALWAYS_INDIRECT set)
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: softpipe
OpenGL version string: 1.4 (3.3 (Compatibility Profile) Mesa 22.0.0-devel (git-7aab7ccd36))

X Error of failed request:  GLXBadCurrentWindow
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  56
  Current serial number in output stream:  56
(base) jim@DESKTOP-9F1UKHC:~$ glxgears
```

### Expected Behavior

...

### Actual Behavior

...

**Comment by zcobol** [comment]
@Javacr `LIBGL_ALWAYS_INDIRECT` is a Mesa 3D flag ( https://docs.mesa3d.org/envvars.html ) and has no effect on the Nvidia driver. Try running your apps w/out this flag. It's unset by default.

**Comment by Javacr** [comment]
> @Javacr `LIBGL_ALWAYS_INDIRECT` is a Mesa 3D flag ( https://docs.mesa3d.org/envvars.html ) and has no effect on the Nvidia driver. Try running your apps w/out this flag. It's unset by default.

As I said above, if I do not set `LIBGL_ALWAYS_INDIRECT`, `X Error of failed request:  GLXBadCurrentWindow` will be shown. Because OpenGL version is 1.4, WSL cannot render mesh by OpenGl. Everything that depends on OpenGl doesn't work, such as pyglet, pyrender and etc..

```
Traceback (most recent call last):
  File "render.py", line 358, in <module>
    visualize_seqs(args)
  File "render.py", line 320, in visualize_seqs
    rendered_image = render_multi_pose(img=image,
  File "render.py", line 130, in render_multi_pose
    _, mask, color = render_pose(
  File "render.py", line 75, in render_pose
    r = pyrender.OffscreenRenderer(viewport_width=img.shape[1],
  File "/home/jim/miniconda3/envs/smplerx/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/jim/miniconda3/envs/smplerx/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/jim/miniconda3/envs/smplerx/lib/python3.8/site-packages/pyrender/platforms/pyglet_platform.py", line 50, in init_context
    self._window = pyglet.window.Window(config=conf, visible=False,
  File "/home/jim/miniconda3/envs/smplerx/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 133, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/jim/miniconda3/envs/smplerx/lib/python3.8/site-packages/pyglet/window/__init__.py", line 538, in __init__
    context = config.create_context(gl.current_context)
  File "/home/jim/miniconda3/envs/smplerx/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 105, in create_context
    return XlibContext(self, share)
  File "/home/jim/miniconda3/envs/smplerx/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 127, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context
```

**Comment by zcobol** [comment]
@Javacr your setup might need some fixing! And are you using `WSLg` for display or `VcXsrv`? W/out setting `LIBGL_ALWAYS_INDIRECT` this is the result when running `pyglet-2.0.9` example:

![pyglet_opengl](https://github.com/microsoft/WSL/assets/104515072/fb499aea-1f1c-4830-8c4e-a3468d3b1a9f)

From https://github.com/pyglet/pyglet/blob/master/examples/opengl/opengl.py

**Comment by zcobol** [comment]
Also, this might be of interest to you: https://github.com/pyglet/pyglet/issues/768
