### ISSUE TITLE
OOM error for any memory requests - Can't Train AI Models Using WSL

### ISSUE THREAD

**Issue by SemihGuner** [microsoft/WSL#11341]
### Windows Version

Microsoft Windows [Version 10.0.19045.4170]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Other Software

Conda 24.1.2, Python 3.10, Tensorflow 2.16.1, Jupyter Notebook, CUDA, CuDNN

### Repro Steps

-Switch to the Conda env. that is configurated for AI model training.
-Go to /mnt/c/ and where the files are in.
-enter command "jupyter notebook".
-start the training via jupyter notebook.

### Expected Behavior

WSL and Jupyter notebook getting the memory they want, and successfully working. 

### Actual Behavior

I got this error from Python:

`WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1711104293.495667    1669 service.cc:145] XLA service 0x7fac88002460 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1711104293.495707    1669 service.cc:153]   StreamExecutor device (0): NVIDIA GeForce GTX 1650, Compute Capability 7.5
2024-03-22 13:44:53.853920: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var MLIR_CRASH_REPRODUCER_DIRECTORY to enable.
2024-03-22 13:44:55.768035: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:465] Loaded cuDNN version 8902
I0000 00:00:1711104343.130383    1669 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2024-03-22 13:45:53.162752: W external/local_tsl/tsl/framework/bfc_allocator.cc:487] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.25MiB (rounded to 2359296)requested by op 
2024-03-22 13:45:53.162803: I external/local_tsl/tsl/framework/bfc_allocator.cc:1044] BFCAllocator dump for GPU_0_bfc`

`ResourceExhaustedError                    Traceback (most recent call last)
Cell In[13], line 4
      1 epochs = 6 # ideal olduğunu düşünmekteyim.
      2 batch_size = 8
----> 4 history = classifier.fit(
      5     x_train, y_train, epochs=epochs, batch_size=batch_size
      6 )

File ~/anaconda3/envs/py310/lib/python3.10/site-packages/keras_nlp/src/utils/pipeline_model.py:188, in PipelineModel.fit(self, x, y, batch_size, sample_weight, validation_data, validation_split, **kwargs)
    181         (vx, vy, vsw) = keras.utils.unpack_x_y_sample_weight(
    182             validation_data
    183         )
    184         validation_data = _convert_inputs_to_dataset(
    185             vx, vy, vsw, batch_size
    186         )
--> 188 return super().fit(
    189     x=x,
    190     y=None,
    191     batch_size=None,
    192     sample_weight=None,
    193     validation_data=validation_data,
    194     **kwargs,
    195 )

File ~/anaconda3/envs/py310/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py:122, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    119     filtered_tb = _process_traceback_frames(e.__traceback__)
    120     # To get the full stack trace, call:
    121     # `keras.config.disable_traceback_filtering()`
--> 122     raise e.with_traceback(filtered_tb) from None
    123 finally:
    124     del filtered_tb

File ~/anaconda3/envs/py310/lib/python3.10/site-packages/tensorflow/python/eager/execute.py:53, in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     51 try:
     52   ctx.ensure_initialized()
---> 53   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     54                                       inputs, attrs, num_outputs)
     55 except core._NotOkStatusException as e:
     56   if name is not None:

ResourceExhaustedError: Graph execution error:

Detected at node StatefulPartitionedCall defined at (most recent call last):
  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/runpy.py", line 196, in _run_module_as_main

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/runpy.py", line 86, in _run_code

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/ipykernel_launcher.py", line 17, in <module>

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/traitlets/config/application.py", line 992, in launch_instance

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 701, in start

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 195, in start

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/asyncio/base_events.py", line 595, in run_forever

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/asyncio/base_events.py", line 1881, in _run_once

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/asyncio/events.py", line 80, in _run

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in dispatch_queue

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 523, in process_one

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 429, in dispatch_shell

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767, in execute_request

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 429, in do_execute

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3051, in run_cell

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3106, in _run_cell

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3311, in run_cell_async

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3493, in run_ast_nodes

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code

  File "/tmp/ipykernel_1160/3842547599.py", line 4, in <module>

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/keras_nlp/src/utils/pipeline_model.py", line 188, in fit

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 325, in fit

  File "/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 118, in one_step_on_iterator

Out of memory while trying to allocate 2359296 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  766.26MiB
              constant allocation:         8B
        maybe_live_out allocation:  766.24MiB
     preallocated temp allocation:    1.46GiB
  preallocated temp fragmentation:    8.00MiB (0.53%)
                 total allocation:    2.21GiB
              total fragmentation:    8.07MiB (0.36%)
Peak buffers:
	Buffer 1:
		Size: 89.42MiB
		Operator: op_type="AssignSubVariableOp" op_name="cond/adam/AssignSubVariableOp" source_file="/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/tensorflow/python/framework/ops.py" source_line=1177
		XLA Label: fusion
		Shape: f32[30522,768]
		==========================

	Buffer 2:
		Size: 89.42MiB
		Operator: op_type="AssignSubVariableOp" op_name="cond/adam/AssignSubVariableOp" source_file="/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/tensorflow/python/framework/ops.py" source_line=1177
		XLA Label: fusion
		Shape: f32[30522,768]
		==========================

	Buffer 3:
		Size: 89.42MiB
		Operator: op_type="AssignSubVariableOp" op_name="cond/adam/AssignSubVariableOp" source_file="/home/{USER}/anaconda3/envs/py310/lib/python3.10/site-packages/tensorflow/python/framework/ops.py" source_line=1177
		XLA Label: fusion
		Shape: f32[30522,768]
		==========================

	Buffer 4:
		Size: 48.00MiB
		XLA Label: fusion
		Shape: f16[96,512,512]
		==========================

	Buffer 5:
		Size: 48.00MiB
		Operator: op_type="Softmax" op_name="distil_bert_classifier_1/distil_bert_backbone_1/transformer_layer_5_1/self_attention_layer_1/softmax_5_1/Softmax" deduplicated_name="input_exponential_reduce_fusion"
		XLA Label: fusion
		Shape: f16[8,12,512,512]
		==========================

	Buffer 6:
		Size: 48.00MiB
		XLA Label: fusion
		Shape: f16[96,512,512]
		==========================

	Buffer 7:
		Size: 48.00MiB
		Operator: op_type="Softmax" op_name="distil_bert_classifier_1/distil_bert_backbone_1/transformer_layer_4_1/self_attention_layer_1/softmax_4_1/Softmax" deduplicated_name="input_exponential_reduce_fusion"
		XLA Label: fusion
		Shape: f16[8,12,512,512]
		==========================

	Buffer 8:
		Size: 48.00MiB
		XLA Label: fusion
		Shape: f16[96,512,512]
		==========================

	Buffer 9:
		Size: 48.00MiB
		Operator: op_type="Softmax" op_name="distil_bert_classifier_1/distil_bert_backbone_1/transformer_layer_3_1/self_attention_layer_1/softmax_3_1/Softmax" deduplicated_name="input_exponential_reduce_fusion"
		XLA Label: fusion
		Shape: f16[8,12,512,512]
		==========================

	Buffer 10:
		Size: 48.00MiB
		XLA Label: fusion
		Shape: f16[96,512,512]
		==========================

	Buffer 11:
		Size: 48.00MiB
		Operator: op_type="Softmax" op_name="distil_bert_classifier_1/distil_bert_backbone_1/transformer_layer_2_1/self_attention_layer_1/softmax_2_1/Softmax" deduplicated_name="input_exponential_reduce_fusion"
		XLA Label: fusion
		Shape: f16[8,12,512,512]
		==========================

	Buffer 12:
		Size: 48.00MiB
		XLA Label: fusion
		Shape: f16[96,512,512]
		==========================

	Buffer 13:
		Size: 48.00MiB
		Operator: op_type="Softmax" op_name="distil_bert_classifier_1/distil_bert_backbone_1/transformer_layer_1_1/self_attention_layer_1/softmax_1_1/Softmax" deduplicated_name="input_exponential_reduce_fusion"
		XLA Label: fusion
		Shape: f16[8,12,512,512]
		==========================

	Buffer 14:
		Size: 48.00MiB
		XLA Label: fusion
		Shape: f16[96,512,512]
		==========================

	Buffer 15:
		Size: 48.00MiB
		Operator: op_type="Softmax" op_name="distil_bert_classifier_1/distil_bert_backbone_1/transformer_layer_0_1/self_attention_layer_1/softmax_1/Softmax" deduplicated_name="input_exponential_reduce_fusion"
		XLA Label: fusion
		Shape: f16[8,12,512,512]
		==========================

	 [[{{node StatefulPartitionedCall}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_one_step_on_iterator_27316]`

### Diagnostic Logs

[WslLogs-2024-03-22_14-00-31.zip](https://github.com/microsoft/WSL/files/14721601/WslLogs-2024-03-22_14-00-31.zip)

**Comment by OneBlue** [comment]
Unfortunately @SemihGuner this means that your GPU is out of memory so this is not something that WSL can fix.
