### ISSUE TITLE
Multiple BadZipFile errors while installing any project

### ISSUE THREAD

**Issue by hex17or** [microsoft/WSL#11721]
### Windows Version

Microsoft Windows [Version 10.0.22631.3737]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.153.1-2

### Distro Version

Ubuntu 22.04

### Repro Steps

I have setup WSL on my new Windows 11 PC. However, when I try to install any linux project (e.g. Stable Diffusion), I get multiple BadZipFile CRC-32 errors. This happens for almost every project that I try to install. I thought there might be an issue with my disk hence I set up a new WSL installation on an external hard drive but still face the same issue. Everytime, there is a new file that has this error if I keep repeating the installation. I am not sure what has gone wrong. I have previously used WSL without any issues.

### Expected Behavior

Setup should complete successfully without any errors.

### Actual Behavior

I get zipfile.BadZipFile: Bad CRC-32 errors while installing any project. If I repeat the installation after this error, the error is shown for a different file. I am attaching the log of the installation. Everytime, the file with the error is different if I repeat the installation. 

### Diagnostic Logs

```
 bash webui.sh

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on sdp user
################################################################

################################################################
Clone stable-diffusion-webui
################################################################
Cloning into 'stable-diffusion-webui'...
remote: Enumerating objects: 33923, done.
remote: Counting objects: 100% (179/179), done.
remote: Compressing objects: 100% (103/103), done.
remote: Total 33923 (delta 95), reused 143 (delta 76), pack-reused 33744
Receiving objects: 100% (33923/33923), 35.00 MiB | 13.13 MiB/s, done.
Resolving deltas: 100% (23701/23701), done.

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
glibc version is 2.35
Cannot locate TCMalloc. Do you have tcmalloc or google-perftool installed on your system? (improves CPU memory usage)
Python 3.10.6 (main, Oct 24 2022, 16:07:47) [GCC 11.2.0]
Version: v1.9.4
Commit hash: feee37d75f1b168768014e4634dcb156ee649c05
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Collecting torch==2.1.2
  Downloading https://download.pytorch.org/whl/cu121/torch-2.1.2%2Bcu121-cp310-cp310-linux_x86_64.whl (2200.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 GB 1.5 MB/s eta 0:00:00
Collecting torchvision==0.16.2
  Downloading https://download.pytorch.org/whl/cu121/torchvision-0.16.2%2Bcu121-cp310-cp310-linux_x86_64.whl (6.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 14.1 MB/s eta 0:00:00
Collecting filelock
  Downloading filelock-3.15.3-py3-none-any.whl (16 kB)
Collecting fsspec
  Downloading fsspec-2024.6.0-py3-none-any.whl (176 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.9/176.9 kB 3.1 MB/s eta 0:00:00
Collecting triton==2.1.0
  Downloading https://download.pytorch.org/whl/triton-2.1.0-0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.2/89.2 MB 12.4 MB/s eta 0:00:00
Collecting networkx
  Downloading networkx-3.3-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 11.8 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting jinja2
  Downloading jinja2-3.1.4-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.3/133.3 kB 10.3 MB/s eta 0:00:00
Collecting sympy
  Downloading sympy-1.12.1-py3-none-any.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 12.8 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.32.3-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 8.3 MB/s eta 0:00:00
Collecting pillow!=8.3.*,>=5.3.0
  Downloading pillow-10.3.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 12.9 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-2.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.3/19.3 MB 14.0 MB/s eta 0:00:00
Collecting MarkupSafe>=2.0
  Downloading https://download.pytorch.org/whl/MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.1/142.1 kB 21.8 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.7-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 10.8 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.2.2-py3-none-any.whl (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.4/121.4 kB 22.0 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2024.6.2-py3-none-any.whl (164 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.4/164.4 kB 8.2 MB/s eta 0:00:00
Collecting mpmath<1.4.0,>=1.1.0
  Downloading https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 10.7 MB/s eta 0:00:00
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, fsspec, filelock, charset-normalizer, certifi, triton, requests, jinja2, torch, torchvision
ERROR: Exception:
Traceback (most recent call last):
  File "/home/sdp/stable-diffusion-webui/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/sdp/stable-diffusion-webui/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/home/sdp/stable-diffusion-webui/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 461, in run
    installed = install_given_reqs(
  File "/home/sdp/stable-diffusion-webui/venv/lib/python3.10/site-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "/home/sdp/stable-diffusion-webui/venv/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 790, in install
    install_wheel(
  File "/home/sdp/stable-diffusion-webui/venv/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 727, in install_wheel
    _install_wheel(
  File "/home/sdp/stable-diffusion-webui/venv/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 587, in _install_wheel
    file.save()
  File "/home/sdp/stable-diffusion-webui/venv/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 388, in save
    shutil.copyfileobj(f, dest)
  File "/home/sdp/miniconda3/envs/sd/lib/python3.10/shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "/home/sdp/miniconda3/envs/sd/lib/python3.10/zipfile.py", line 925, in read
    data = self._read1(n)
  File "/home/sdp/miniconda3/envs/sd/lib/python3.10/zipfile.py", line 1015, in _read1
    self._update_crc(data)
  File "/home/sdp/miniconda3/envs/sd/lib/python3.10/zipfile.py", line 943, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'torch/include/ATen/ops/view_as_complex_copy.h'

[notice] A new release of pip available: 22.2.1 -> 24.1
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/home/sdp/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/home/sdp/stable-diffusion-webui/launch.py", line 39, in main
    prepare_environment()
  File "/home/sdp/stable-diffusion-webui/modules/launch_utils.py", line 380, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "/home/sdp/stable-diffusion-webui/modules/launch_utils.py", line 115, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install torch.
Command: "/home/sdp/stable-diffusion-webui/venv/bin/python3" -m pip install torch==2.1.2 torchvision==0.16.2 --extra-index-url https://download.pytorch.org/whl/cu121
Error code: 2
```

**Comment by hex17or** [comment]
Added logs
[WslLogs-2024-06-21_13-23-30.zip](https://github.com/user-attachments/files/15926889/WslLogs-2024-06-21_13-23-30.zip)

**Comment by hex17or** [comment]
Just as an update - the problem seems to be with pip throwing bad zip file errors for random packages.

**Comment by OneBlue** [comment]
Unfortunately this seems to be issue either with pip or the projects in question, not something that can be fixed from the wsl side

**Comment by ziyuliu258** [comment]
Same things happened to me

**Comment by murlock1000** [comment]
Same thing here

Update: The issue was a badly installed CPU cooler causing the cpu to overheat and corrupt data, BSOD.

**Comment by hex17or** [comment]
Not sure if it helps anyone but I sent my PC to MSI for a warranty check and they had to replace my CPU after which this was solved. In their tests, they got a BSOD after which they replaced the CPU.
