### ISSUE TITLE
XOpenDisplay failed when running Git Credential Manager on WSL 2.2.4.0

### ISSUE THREAD

**Issue by mikelor** [microsoft/WSL#11777]
### Windows Version

Windows 11 Pro Insider Preview 24H2 26244.5000

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 22.04

### Other Software

- git version 2.34.1
- git credential manager 2.5.1
- VcXsrv X Server 1.20.9.0

### Repro Steps
```
~/repos/tsathroughput>main> git push
Unhandled exception. System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
   at Avalonia.AvaloniaX11PlatformExtensions.<>c.<UseX11>b__0_0()
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithoutStarting()
   at GitCredentialManager.UI.AvaloniaUi.<>c__DisplayClass8_1.<ShowWindowAsync>b__1(CancellationToken appCancelToken)
   at GitCredentialManager.UI.Dispatcher.DispatcherJob.Execute(CancellationToken ct)
   at GitCredentialManager.UI.Dispatcher.DispatcherJobQueue.Run()
   at GitCredentialManager.UI.Dispatcher.Run()
   at GitCredentialManager.Program.Main(String[] args)
Aborted
```
### Expected Behavior
When doing a git push I would expect the Github authentication popup in XWindows

This was working fine until I upgraded to WSL 2.2.4.0 from WSL 2.1.5.0 to fix this issue https://twitter.com/mikelor/status/1780657187649654992

Other X Window Apps Open Successfully.
I submitted an [Issue on Git Credential Manager](https://github.com/git-ecosystem/git-credential-manager/issues/1592#issue-2251033389) but they told me to open one here.

### Actual Behavior
```
2024-07-12 14:54:59.743 [info] > git push origin main:main [3938ms]
2024-07-12 14:54:59.743 [info] Unhandled exception. System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
   at Avalonia.AvaloniaX11PlatformExtensions.<>c.<UseX11>b__0_0()
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithoutStarting()
   at GitCredentialManager.UI.AvaloniaUi.<>c__DisplayClass8_1.<ShowWindowAsync>b__1(CancellationToken appCancelToken)
   at GitCredentialManager.UI.Dispatcher.DispatcherJob.Execute(CancellationToken ct)
   at GitCredentialManager.UI.Dispatcher.DispatcherJobQueue.Run()
   at GitCredentialManager.UI.Dispatcher.Run()
   at GitCredentialManager.Program.Main(String[] args)
Aborted
```

**Comment by mikelor** [comment]
[WslLogs-2024-07-12_15-57-12.zip](https://github.com/user-attachments/files/16199887/WslLogs-2024-07-12_15-57-12.zip)

**Comment by mikelor** [comment]
See above. This appears to be an issue with Avalonia based apps.

**Comment by mikelor** [comment]
Never mind. We can close this. I found the fix here.

https://github.com/microsoft/WSL/issues/11698#issuecomment-2176996205

I modified my configuration to look like this.
export DISPLAY=$(ip route | grep default | awk '{print $3}'):0.0
