### ISSUE TITLE
clock skew in `wsl2`

### ISSUE THREAD

**Issue by surfacepatterns** [microsoft/WSL#11790]
### Windows Version

Microsoft Windows [Version 10.0.22631.3737]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

CBL-Mariner 2.0.20240628

### Repro Steps

1. Start the Linux instance.
2. Do various things in the `wsl` instance.
3. Observe that, occasionally, you get error messages regarding timestamps in the future, and detection of clock skew.  Sometimes, depending on the task, clock skew occurs often enough that you can't complete the task (e.g. building RPMs wherein the tests rely on file modification times that end up appearing to be in the future).

### Expected Behavior

I expect to observe clock skew quite rarely, and to have it impact my work on a much less frequent basis.

### Actual Behavior

Here are a couple examples.

`dmesg` output
```
[danderson: /tmp/tmpawdfb76t]
> dmesg | tail -n 40
[404082.973889] systemd-journald[84]: Time jumped backwards, rotating.
[404111.348115] systemd-journald[84]: Time jumped backwards, rotating.
[404139.703269] systemd-journald[84]: Time jumped backwards, rotating.
[404168.096403] systemd-journald[84]: Time jumped backwards, rotating.
[404196.480773] systemd-journald[84]: Time jumped backwards, rotating.
[404224.872429] systemd-journald[84]: Time jumped backwards, rotating.
[404253.223833] systemd-journald[84]: Time jumped backwards, rotating.
[404281.594155] systemd-journald[84]: Time jumped backwards, rotating.
[404309.968480] systemd-journald[84]: Time jumped backwards, rotating.
[404338.363311] systemd-journald[84]: Time jumped backwards, rotating.
[404366.732147] systemd-journald[84]: Time jumped backwards, rotating.
[404395.108002] systemd-journald[84]: Time jumped backwards, rotating.
[404423.480880] systemd-journald[84]: Time jumped backwards, rotating.
[404451.831353] systemd-journald[84]: Time jumped backwards, rotating.
[404480.194392] systemd-journald[84]: Time jumped backwards, rotating.
[404508.549149] systemd-journald[84]: Time jumped backwards, rotating.
[404536.920285] systemd-journald[84]: Time jumped backwards, rotating.
[404565.283479] systemd-journald[84]: Time jumped backwards, rotating.
[404593.654135] systemd-journald[84]: Time jumped backwards, rotating.
[404622.024996] systemd-journald[84]: Time jumped backwards, rotating.
[404650.397592] systemd-journald[84]: Time jumped backwards, rotating.
[404678.775581] systemd-journald[84]: Time jumped backwards, rotating.
[404707.127293] systemd-journald[84]: Time jumped backwards, rotating.
[404735.490979] systemd-journald[84]: Time jumped backwards, rotating.
[404763.840208] systemd-journald[84]: Time jumped backwards, rotating.
[404792.189098] systemd-journald[84]: Time jumped backwards, rotating.
[404820.536595] systemd-journald[84]: Time jumped backwards, rotating.
[404848.904155] systemd-journald[84]: Time jumped backwards, rotating.
[404877.268762] systemd-journald[84]: Time jumped backwards, rotating.
[404905.630039] systemd-journald[84]: Time jumped backwards, rotating.
[404933.999577] systemd-journald[84]: Time jumped backwards, rotating.
[404962.374937] systemd-journald[84]: Time jumped backwards, rotating.
[404990.729142] systemd-journald[84]: Time jumped backwards, rotating.
[405019.091547] systemd-journald[84]: Time jumped backwards, rotating.
[405047.445148] systemd-journald[84]: Time jumped backwards, rotating.
[405075.793623] systemd-journald[84]: Time jumped backwards, rotating.
[405104.138690] systemd-journald[84]: Time jumped backwards, rotating.
[405132.488783] systemd-journald[84]: Time jumped backwards, rotating.
[405160.846706] systemd-journald[84]: Time jumped backwards, rotating.
[405189.185044] systemd-journald[84]: Time jumped backwards, rotating.
```

Partial (relevant) output when `meson` tests fail, which are run as part of building binary RPMs:
```
Traceback (most recent call last):
  File "/builddir/build/BUILD/meson-1.3.1/meson.py", line 40, in <module>
    sys.exit(mesonmain.main())
  File "/builddir/build/BUILD/meson-1.3.1/mesonbuild/mesonmain.py", line 294, in main
    return run(sys.argv[1:], launcher)
  File "/builddir/build/BUILD/meson-1.3.1/mesonbuild/mesonmain.py", line 280, in run
    return errorhandler(e, 'setup')
  File "/builddir/build/BUILD/meson-1.3.1/mesonbuild/mesonmain.py", line 40, in errorhandler
    raise e
  File "/builddir/build/BUILD/meson-1.3.1/mesonbuild/mesonmain.py", line 278, in run
    return msetup.run(['--reconfigure'] + args[2:])
  File "/builddir/build/BUILD/meson-1.3.1/mesonbuild/msetup.py", line 358, in run
    app.generate()
  File "/builddir/build/BUILD/meson-1.3.1/mesonbuild/msetup.py", line 181, in generate
    return self._generate(env, capture, vslite_ctx)
  File "/builddir/build/BUILD/meson-1.3.1/mesonbuild/msetup.py", line 251, in _generate
    captured_compile_args = intr.backend.generate(capture, vslite_ctx)
  File "/builddir/build/BUILD/meson-1.3.1/mesonbuild/backend/ninjabackend.py", line 657, in generate
    self.generate_ending()
  File "/builddir/build/BUILD/meson-1.3.1/mesonbuild/backend/ninjabackend.py", line 3679, in generate_ending
    deps = self.get_regen_filelist()
  File "/builddir/build/BUILD/meson-1.3.1/mesonbuild/backend/backends.py", line 1353, in get_regen_filelist
    self.check_clock_skew(deps)
  File "/builddir/build/BUILD/meson-1.3.1/mesonbuild/backend/backends.py", line 1380, in check_clock_skew
    raise MesonException(f'Clock skew detected. File {absf} has a time stamp {delta:.4f}s in the future.')
mesonbuild.utils.core.MesonException: Clock skew detected. File /builddir/build/BUILD/meson-1.3.1/b 41766a13e6/../test cases/common/22 object extraction/meson.build has a time stamp 0.2633s in the future.
ninja: error: rebuilding 'build.ninja': subcommand failed
```
(In the build log this excerpt is from, there were 32 such clock skew failures.  I've tried building this package five times today, and each instance results in a similar amount of failures.)

Note that I've seen the issues about clock skew after rebooting.  A few things make me think this is different:
1. I'm running a version of WSL that should have the fix for that issue.
2. I observe these issues right after restarting my computer, prior to the computer sleeping.
3. Running `sudo hwclock -s` doesn't seem to change anything.

**Comment by surfacepatterns** [comment]
[WslLogs-2024-07-17_16-35-07.zip](https://github.com/user-attachments/files/16275765/WslLogs-2024-07-17_16-35-07.zip)

**Comment by surfacepatterns** [comment]
So, it seems like `wsl`, or something `wsl` is dependent upon, get's in a bad state sometimes.  Right now, after waking up from sleep, the issue isn't happening:
```
[danderson: /tmp/tmpawdfb76t]
> dmesg | tail -n 5
[456589.205091] hv_utils: TimeSync IC version 4.0
[456665.948959] mini_init (176): drop_caches: 1
[459550.465849] mini_init (176): drop_caches: 1
[459640.326553] mini_init (176): drop_caches: 1
[459910.870860] mini_init (176): drop_caches: 1
```
I"m going to continue monitoring the system, and try to identify what happens around the time that the issue starts.

**Comment by barries** [comment]
@surfacepatterns, does this happen more with higher parallelism for you, too?

**Comment by Defined2014** [comment]
I think maybe you could stop the ntp services in `WSL2` or change it same as Windows'.

**Comment by dmsza** [comment]
+1. Same issue. It is not clock skew. Clock sometimes simply goes backwards. It can happen just executing "date" commands in a row. Building in WSL is almost impossible now. 

```
(...)
dmsza@dme300:~$ date
Sun Jul  6 16:07:23 -03 2025
dmsza@dme300:~$ date
Sun Jul  6 16:07:24 -03 2025
dmsza@dme300:~$ date
Sun Jul  6 16:07:24 -03 2025
dmsza@dme300:~$ date
Sun Jul  6 16:07:23 -03 2025 ### Clock went 1 second backwards
dmsza@dme300:~$ date
Sun Jul  6 16:07:23 -03 2025
dmsza@dme300:~$ date
Sun Jul  6 16:07:24 -03 2025
(...)
```

**Comment by cnihelton** [comment]
Did you guys figure out whether NTS inside the WSL instances has any relationship with this kind of skew observed in this thread?

**Comment by AdelMadkour** [comment]
same issue almost every 30 sec, and it messes with my running projects specially workers and Redis

Windows 10 Pro (22H2) + WSL2

```
Nov 01 06:45:46 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:46:02 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:45:59 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:45:59 systemd-journald[56]: Time jumped backwards, rotating.
Nov 01 06:45:59 systemd-journald[58]: Time jumped backwards, rotating.
Nov 01 06:45:59 systemd-journald[53]: Time jumped backwards, rotating.
Nov 01 06:46:01 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:46:30 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:46:29 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:46:29 systemd-journald[56]: Time jumped backwards, rotating.
Nov 01 06:46:29 systemd-journald[53]: Time jumped backwards, rotating.
Nov 01 06:46:29 systemd-journald[58]: Time jumped backwards, rotating.
Nov 01 06:46:59 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:46:57 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:46:58 systemd-journald[56]: Time jumped backwards, rotating.
Nov 01 06:46:58 systemd-journald[58]: Time jumped backwards, rotating.
Nov 01 06:46:58 systemd-journald[53]: Time jumped backwards, rotating.
Nov 01 06:47:27 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:47:24 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:47:24 systemd-journald[58]: Time jumped backwards, rotating.
Nov 01 06:47:24 systemd-journald[56]: Time jumped backwards, rotating.
Nov 01 06:47:24 systemd-journald[53]: Time jumped backwards, rotating.
Nov 01 06:47:55 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:47:54 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:47:54 systemd-journald[58]: Time jumped backwards, rotating.
Nov 01 06:47:54 systemd-journald[53]: Time jumped backwards, rotating.
Nov 01 06:47:54 systemd-journald[56]: Time jumped backwards, rotating.
Nov 01 06:48:24 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:48:22 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:48:23 systemd-journald[58]: Time jumped backwards, rotating.
Nov 01 06:48:23 systemd-journald[53]: Time jumped backwards, rotating.
Nov 01 06:48:23 systemd-journald[56]: Time jumped backwards, rotating.
Nov 01 06:48:23 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:48:53 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:48:52 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:48:52 systemd-journald[56]: Time jumped backwards, rotating.
Nov 01 06:48:52 systemd-journald[58]: Time jumped backwards, rotating.
Nov 01 06:48:52 systemd-journald[53]: Time jumped backwards, rotating.
Nov 01 06:49:22 systemd-resolved[169]: Clock change detected. Flushing caches.
Nov 01 06:49:21 systemd-resolved[169]: Clock change detected. Flushing caches.
```

**Comment by Rob2309** [comment]
> +1. Same issue. It is not clock skew. Clock sometimes simply goes backwards. It can happen just executing "date" commands in a row. Building in WSL is almost impossible now.
> 
> ```
> (...)
> dmsza@dme300:~$ date
> Sun Jul  6 16:07:23 -03 2025
> dmsza@dme300:~$ date
> Sun Jul  6 16:07:24 -03 2025
> dmsza@dme300:~$ date
> Sun Jul  6 16:07:24 -03 2025
> dmsza@dme300:~$ date
> Sun Jul  6 16:07:23 -03 2025 ### Clock went 1 second backwards
> dmsza@dme300:~$ date
> Sun Jul  6 16:07:23 -03 2025
> dmsza@dme300:~$ date
> Sun Jul  6 16:07:24 -03 2025
> (...)
> ```

I can observe the same thing on my Laptop, but not on my desktop. But it seems to be unrelated to hibernation, it also happens right after `wsl --shutdown` and restarting WSL.

I also noticed that `nanosleep` waits for less than the specified amount, which the linux docs say can never happen.

**Comment by cnihelton** [comment]
Disabling `systemd-timesyncd` doesn't help then? ( `systemctl disable systemd-timesyncd.service`).

**Comment by AdelMadkour** [comment]
> same issue almost every 30 sec, and it messes with my running projects specially workers and Redis
> 
> Windows 10 Pro (22H2) + WSL2
> 
> ```
> Nov 01 06:45:46 systemd-resolved[169]: Clock change detected. Flushing caches.
> Nov 01 06:46:02 systemd-resolved[169]: Clock change detected. Flushing caches.
> Nov 01 06:45:59 systemd-resolved[169]: Clock change detected. Flushing caches.
> Nov 01 06:45:59 systemd-journald[56]: Time jumped backwards, rotating.
> Nov 01 06:45:59 systemd-journald[58]: Time jumped backwards, rotating.
> Nov 01 06:45:59 systemd-journald[53]: Time jumped backwards, rotating.
> Nov 01 06:46:01 systemd-resolved[169]: Clock change detected. Flushing caches.
> Nov 01 06:46:30 systemd-resolved[169]: Clock change detected. Flushing caches.
> Nov 01 06:46:29 systemd-resolved[169]: Clock change detected. Flushing caches.
> Nov 01 06:46:29 systemd-journald[56]: Time jumped backwards, rotating.
> Nov 01 06:46:29 systemd-journald[53]: Time jumped backwards, rotating.
> Nov 01 06:46:29 systemd-journald[58]: Time jumped backwards, rotating.
> Nov 01 06:46:59 systemd-resolved[169]: Clock change detected. Flushing caches.
> Nov 01 06:46:57 systemd-resolved[169]: Clock change detected. Flushing caches.
> Nov 01 06:46:58 systemd-journald[56]: Time jumped backwards, rotating.
> Nov 01 06:46:58 systemd-journald[58]: Time jumped backwards, rotating.
> Nov 01 06:46:58 systemd-journald[53]: Time jumped backwards, rotating.
> Nov 01 06:47:27 systemd-resolved[169]: Clock change detected. Flushing caches.
> ```

I found out the problem was only on Ubuntu WSL2, When I tried Debian it worked flawlessly, if that can help anybody

**Comment by oldium** [comment]
Same issue, executed `systemctl disable --now systemd-timesyncd.service` to stop the sync service, observing now...

Update: Looks like it is fixed

**Comment by GinjaNinja32** [comment]
based on behaviour on my system, something (windows? wsl internals? unsure) is trying to sync the time by speeding/slowing the clock, while systemd-timesyncd is trying to sync by discontinuous jumps to a new time. when the time is in sync, everything looks fine, but it can get into a loop where timesyncd jumps the clock backwards (or presumably forwards, but that's less noticeable) because it's running fast, which makes whatever's skewing the clock speed continue running it fast, so timesyncd jumps again, etc. disabling timesyncd fixes the jumps, but presumably disabling whatever's skewing the clock rate would also work.

**Comment by lazytiger** [comment]
I run 

```bash 
while [ 1 ]; do date; sleep 1; done
``` 
on wsl, and 
```pwsh
while ($true) {
    Get-Date
    Start-Sleep -Seconds 1
}
```
on windows at the same time.

And got this on linux

```log
Thu Feb 26 18:54:57 CST 2026
Thu Feb 26 18:54:58 CST 2026
Thu Feb 26 18:54:59 CST 2026
Thu Feb 26 18:55:00 CST 2026
Thu Feb 26 18:55:01 CST 2026
Thu Feb 26 18:55:02 CST 2026
Thu Feb 26 18:55:03 CST 2026
Thu Feb 26 18:55:02 CST 2026 **back**
Thu Feb 26 18:55:03 CST 2026
Thu Feb 26 18:55:04 CST 2026
Thu Feb 26 18:55:05 CST 2026
```

And got this on windows

```log
2026年2月26日 18:54:57
2026年2月26日 18:54:58
2026年2月26日 18:54:59
2026年2月26日 18:55:00
2026年2月26日 18:55:01
2026年2月26日 18:55:02
2026年2月26日 18:55:03
2026年2月26日 18:55:04
2026年2月26日 18:55:05
```

I have no time sync tools installed on wsl, and I don't find a way to fix this.

**Comment by lazytiger** [comment]
> I run
> 
> while [ 1 ]; do date; sleep 1; done
> on wsl, and
> 
> while ($true) {
>     Get-Date
>     Start-Sleep -Seconds 1
> }
> on windows at the same time.
> 
> And got this on linux
> 
> ```
> Thu Feb 26 18:54:57 CST 2026
> Thu Feb 26 18:54:58 CST 2026
> Thu Feb 26 18:54:59 CST 2026
> Thu Feb 26 18:55:00 CST 2026
> Thu Feb 26 18:55:01 CST 2026
> Thu Feb 26 18:55:02 CST 2026
> Thu Feb 26 18:55:03 CST 2026
> Thu Feb 26 18:55:02 CST 2026 **back**
> Thu Feb 26 18:55:03 CST 2026
> Thu Feb 26 18:55:04 CST 2026
> Thu Feb 26 18:55:05 CST 2026
> ```
> 
> And got this on windows
> 
> ```
> 2026年2月26日 18:54:57
> 2026年2月26日 18:54:58
> 2026年2月26日 18:54:59
> 2026年2月26日 18:55:00
> 2026年2月26日 18:55:01
> 2026年2月26日 18:55:02
> 2026年2月26日 18:55:03
> 2026年2月26日 18:55:04
> 2026年2月26日 18:55:05
> ```
> 
> I have no time sync tools installed on wsl, and I don't find a way to fix this.

I find my problem. I have two ubuntu, and one enabled systemd-timesyncd. when disabled that, everything goes ok.

**Comment by gustavcke** [comment]
## Guest clock runs fast by up to ~7%, on every available clocksource, intermittently after boot

All figures below are from a single host, measured 2026-07-30. Points that are inference rather
than measurement are marked as such.

### Environment

| | |
|---|---|
| Host CPU | Intel Core i9-13900K (24 cores / 32 threads, hybrid 8 P-core + 16 E-core) |
| Windows | 11 25H2, build 26200.8973 |
| WSL | 2.7.10.0 (Store) |
| Kernel | 6.18.33.2-microsoft-standard-WSL2 |
| Distro | Ubuntu 24.04.4 LTS (noble), systemd 255, systemd-timesyncd active |
| Host VBS | Running: Credential Guard, HVCI, HVPT. Secure Boot on. |

`/proc/cmdline`:

```
initrd=\initrd.img WSL_ROOT_INIT=1 panic=-1 nr_cpus=32 hv_utils.timesync_implicit=1
swiotlb=force console=hvc0 debug pty.legacy_count=0 WSL_ENABLE_CRASH_DUMP=1
```

TSC flags in guest: `constant_tsc nonstop_tsc tsc_reliable tsc_known_freq tsc_adjust hypervisor`.
`dmesg` reports `tsc: Detected 2995.201 MHz processor`, which matches the 13900K's nominal
base frequency, so TSC calibration itself looks correct.

### Symptom

The guest's `CLOCK_MONOTONIC` advances faster than real time. `sleep N` returns early in wall
time. systemd-timesyncd then repeatedly steps `CLOCK_REALTIME` backwards to compensate, which
in turn:

- flushes systemd-resolved's cache every ~45s, so `getaddrinfo()` fails intermittently
- breaks hostname-based CIFS mounts in `/etc/fstab` at boot
  (`wsl: Processing /etc/fstab with mount -a failed.`)
- produces out-of-order journal entries, e.g. a service logging "Starting" at 14:10:36 and its
  own first message at 14:10:35

### Measurement method

Timed from the Windows host, so it does not depend on the guest's own clock being right:

```powershell
$sw = [System.Diagnostics.Stopwatch]::StartNew()
wsl.exe -d Ubuntu -u root -- sh -c "sleep 10"
$sw.Stop()
# rate = 10 / elapsed ; error_ppm = (rate - 1) * 1e6   (positive = guest fast)
```

`sleep` waits on `CLOCK_MONOTONIC` and is unaffected by NTP. `wsl.exe` process startup
(~0.07s here) is measured separately with a no-op invocation and subtracted, and every figure
below is a median of 3+ reps.

Cross-check from inside the guest: `/proc/uptime` deltas were captured either side of the same
sleep. During the fault the guest reported **10.00–10.04 s elapsed while the host measured
9.34–9.71 s**, so the guest genuinely believes more time has passed. This is not host-side
timing noise.

### The error is present on every clocksource, including `acpi_pm`

`available_clocksource`: `tsc hyperv_clocksource_tsc_page hyperv_clocksource_msr acpi_pm`.
Switched at runtime via `/sys/devices/system/clocksource/clocksource0/current_clocksource`.

**While the fault was active** (~5 min after boot, 2026-07-30 14:15 UTC, 3 reps × 10 s each):

| clocksource | median error | individual reps (ppm) |
|---|---:|---|
| `tsc` | **+45,674 ppm** (+4.57%) | 45674, 49971, 37039 |
| `hyperv_clocksource_tsc_page` | **+55,017 ppm** (+5.50%) | 43468, 55017, 55434 |
| `hyperv_clocksource_msr` | **+54,793 ppm** (+5.48%) | 54793, **478**, 76241 |
| `acpi_pm` | **+69,620 ppm** (+6.96%) | 69620, 78963, 48921 |

**Same host, same day, fault dormant** (VM settled ~20 min, 13:07 UTC):

| clocksource | median error |
|---|---:|
| `tsc` | +10,739 ppm |
| `hyperv_clocksource_tsc_page` | +10,959 ppm |
| `hyperv_clocksource_msr` | +10,671 ppm |
| `acpi_pm` | +9,887 ppm |

Two things stand out:

1. **`acpi_pm` is affected as badly as the TSC-derived sources** — worst of the four while the
   fault was active. Selecting a different clocksource in the guest does not avoid it. *(Inference:
   this points at the shared upstream time base the hypervisor synthesises all four from, rather
   than at Linux's clocksource selection or TSC scaling specifically.)*
2. **It fluctuates on a ~10 second timescale.** The `+478 ppm` rep sits between `+54,793` and
   `+76,241` on the same clocksource, minutes apart. A constant frequency-scaling error would
   not do that.

### Intermittency

Severe shortly after boot, decaying as the VM settles. A 60-second sampler over ~45 minutes:

| window | n | median | min | max |
|---|---:|---:|---:|---:|
| settled VM (13:05–13:50 UTC) | 41 | +5,952 ppm | −14,861 | +8,343 |
| first minutes after boot (14:11+ UTC) | 5 | +29,484 ppm | +19,242 | +45,114 |

Corroborating signal that is independent of my timing method: the cumulative count of
systemd-timesyncd sync events went from **6** on the settled VM to **34** within minutes of
boot — timesyncd working far harder to hold the clock down.

Note that even the "quiet" state is +3,000 to +11,000 ppm, i.e. 60–200× a healthy virtualised
clock. There appear to be two phenomena: a persistent baseline error and an intermittent
excursion on top of it.

### Things that did NOT fix it

| tried | result |
|---|---|
| `kernelCommandLine=clocksource=hyperv_clocksource_tsc_page` | No improvement. While the fault is active this is measurably **worse** than plain `tsc` (+55,017 vs +45,674 ppm). |
| `processors=16` in `.wslconfig` (half the logical CPUs, testing hybrid P/E topology) | No improvement — the +45,000..+69,000 ppm figures above were taken with `nproc=16`. |

### Not yet tested

- HVCI (memory integrity) and HVPT off — the per-scenario registry opt-out is not honoured on
  this build, and the documented alternative disables VBS wholesale along with Credential Guard.
- Removing the Hyper-V role and leaving only VirtualMachinePlatform — not attempted; this host's
  only network path is a Hyper-V external vSwitch.

### Question for maintainers

Given the error tracks across `tsc`, `hyperv_clocksource_tsc_page`, `hyperv_clocksource_msr`
and `acpi_pm` alike, and varies on a ~10s timescale:

1. Is there host-side instrumentation for the reference TSC page's scale/offset as WSL's
   utility VM sees it, so the hypervisor time base can be observed directly rather than inferred?
2. Is `hv_utils.timesync_implicit=1` (default in the WSL cmdline) expected to leave a rate error
   this large uncorrected, given it only steps on large deltas?
3. Any known interaction with hybrid P/E-core parts, or with VBS features that are on by default
   on 25H2?

Happy to run further instrumentation (within reason: I can't turn off WSL) — the fault is demonstrably reproducible on this host within minutes of a reboot. Or at any point, really.

**Comment by oldium** [comment]
@gustavcke Your AI analysis looks exhaustive, but missing one key point repeated multiple times in this issue. The root cause for many clock skews is a time synchronization daemon running in the hosted OS. So disable time synchronization daemon inside the hosted OS.
