### ISSUE TITLE
[WSL1] Upgrade to Ubuntu 24.04 from 22.04 fails with missing snap. Possible to work around?

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/WSL#11982]
### Windows Version

Microsoft Windows [Version 10.0.22631.4037]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 22.04

### Other Software

WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.4037

### Repro Steps

```
sudo do-release-upgrade

Traceback (most recent call last):
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/noble", line 8, in <module>
    sys.exit(main())
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/DistUpgrade/DistUpgradeMain.py", line 241, in main
    if app.run():
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/DistUpgrade/DistUpgradeController.py", line 2642, in run
    return self.fullUpgrade()
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/DistUpgrade/DistUpgradeController.py", line 2447, in fullUpgrade
    if not self.doPostInitialUpdate():
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/DistUpgrade/DistUpgradeController.py", line 1438, in doPostInitialUpdate
    self.quirks.run("PostInitialUpdate")
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/DistUpgrade/DistUpgradeQuirks.py", line 102, in run
    func()
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/DistUpgrade/DistUpgradeQuirks.py", line 127, in noblePostInitialUpdate
    self._test_and_fail_on_tpm_fde()
  File "/tmp/ubuntu-release-upgrader-uqmd8iby/DistUpgrade/DistUpgradeQuirks.py", line 1898, in _test_and_fail_on_tpm_fde
    snap_list = subprocess.check_output(['snap', 'list'])
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['snap', 'list']' returned non-zero exit status 1.
```

### Expected Behavior

Ubuntu 24.04 installs in one way or another

### Actual Behavior

Complete breakage as it seems to depend on `snap list` which prints this:
```
Interacting with snapd is not yet supported on Windows Subsystem for Linux 1.
This command has been left available for documentation purposes only.
```

I would propose at least `snap list` prints an empty list or something else reasonable.

Is it possible to upgrade to Ubuntu 24.04 in some other way to bypass `snap` problems?

I like WSLv1 on my Laptop because it's fast, lightweight and doesn't require Hyper-V or a full VM and uses the regular processes without a separate memory allocated for the VM.

**Comment by zcobol** [comment]
`snap` needs `systemd` and `wsl1` doesn't support it.

**Comment by vadimkantorov** [comment]
I mean, is it possible to stub out (or uninstall it) `snap` in such a way so that the upgrader moves on?

Maybe even `snap list` could return 0 exit code and print nothing?

**Comment by flydt** [comment]
> After the hack I described in [ubuntu/WSL#493](https://github.com/ubuntu/WSL/issues/493), the upgrade fails with trying to run some systemd-using postinstall scripts

run command:
cd /bin && mv -f systemd-sysusers{,.org} && ln -s echo systemd-sysusers && cd -

then run do-release-upgrade

then success, I had already upgrade from 22.04->24.04->24.10

root@FUJITSU:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.10
Release:        24.10
Codename:       oracular
root@FUJITSU:~# uname -a
Linux FUJITSU 4.4.0-19041-Microsoft #4355-Microsoft Thu Apr 12 17:37:00 PST 2024 x86_64 x86_64 x86_64 GNU/Linux
root@FUJITSU:~#

**Comment by viniciusvillas** [comment]
JFYI, this method still works in Nov/24:

1) Apply the changes to `bin/systemd-sysusers` suggested by flydt on the comment above;
2) Run the `do-release-upgrade` command until it fails. **Don't exit the window.**
3) In the console history, copy the path to the temporary file `DistUpgradeQuirks.py`.
4) In another terminal, edit the `DistUpgradeQuirks.py` file. Find the line relative to the exception handling for the command `snap list` (search for `['snap', 'list']`) mentioned by vadimkantorov, and apply his suggestion of changing the exception handling from `except FileNotFoundError:` by only `exception:`, making the code ignore any exceptions from this command.
5) Go back to the `do-release-upgrade` window and chose to resurrect the current window. It will try the upgrading process again using the same temporary file (that's what we want).
6) Continue the installation!

Thank you all for the knowledge!! WSL1 is a very impressive tech. I'm really sad that it's been discontinued by MS.

**Comment by herrmanthegerman** [comment]
I observed the same issue with "snap".
On my WSL1 system, I was able to simply remove "snapd" using apt-get:
`# apt-get remove snapd`
Then I could perform the release upgrade.


**Addendum**:
After some time I noticed that I was unable to install packages to Ubuntu 24.04 as `apt-get install` complained about "snapd" not running. I fixed this error message with moving away this file
`# mv /etc/apt/apt.conf.d/20snapd.conf /tmp/`
Thereafter, apt-get balked at missing dependencies and suggested to run `apt-get --fix-broken install`. However, this failed when setting up systemd. This boiled down to the command `# dpkg --configure systemd` aborting with the message 
"/usr/lib/tmpfiles.d/polkitd.conf:2: Failed to resolve group 'polkitd': No such process"
I was able to fix this error message with again moving this file away:
`# mv /usr/lib/tmpfiles.d/polkitd.conf /tmp`
Thereafter  `# dpkg --configure systemd` stopped with a new error message
"Failed to take /etc/passwd lock: Invalid argument"
I figured that some postinstallation scripts where trying to get at lock on /etc/passwd using filecontrols that are not supported by WSL1, see this [discussion and solution](https://superuser.com/a/1912487/342233). 
I applied the solution (a one liner `sed` script, see link above) and then configuring systemd succeeded. Returning to executing `apt-get --fix-broken install`, the process failed with 
"Setting up polkitd (124-2ubuntu1.24.04.2) ...
Failed to take /etc/passwd lock: Invalid argument"
I used `vim /var/lib/dpkg/info/polkitd.postinst` to edit the script: I commented out the part where systemd-sysusers is called so that the classical adduser/addgroup command are used instead.
Finally, `apt-get --fix-broken install` ran successfully and I was able to use `apt-get install` again.
