### ISSUE TITLE
I can't run ccsm and compiz on Bash

### ISSUE THREAD

**Issue by ghost** [Microsoft/WSL#1454]
**root@DESKTOP-3BI943B:/mnt/c/Users/NEON# export DISPLAY=localhost:0
root@DESKTOP-3BI943B:/mnt/c/Users/NEON# ccsm**

```
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
Traceback (most recent call last):
  File "/usr/bin/ccsm", line 94, in <module>
    import ccm
  File "/usr/lib/python2.7/dist-packages/ccm/__init__.py", line 1, in <module>
    from ccm.Conflicts import *
  File "/usr/lib/python2.7/dist-packages/ccm/Conflicts.py", line 26, in <module>
    from ccm.Constants import *
  File "/usr/lib/python2.7/dist-packages/ccm/Constants.py", line 30, in <module>
    CurrentScreenNum = gtk.gdk.display_get_default().get_default_screen().get_number()
AttributeError: 'NoneType' object has no attribute 'get_default_screen'
```

**Some time later, I restart the command** ## 
**It is launched without problem**

**root@DESKTOP-3BI943B:/mnt/c/Users/NEON# export DISPLAY=localhost:0
root@DESKTOP-3BI943B:/mnt/c/Users/NEON# ccsm**

```
compizconfig - Info: Backend     : ini
compizconfig - Info: Integration : true
compizconfig - Info: Profile     : default
Loading icons...
```

**But, Compiz does not launch**

**root@DESKTOP-3BI943B:/mnt/c/Users/NEON# compiz**

```
compiz (core) - Info: Loading plugin: core
compiz (core) - Info: Starting plugin: core
compiz (core) - Info: Loading plugin: ccp
compiz (core) - Info: Starting plugin: ccp
compizconfig - Info: Backend     : ini
compizconfig - Info: Integration : true
compizconfig - Info: Profile     : default

STOP, VcXsr Server is started but in black

```

**Comment by therealkenc** [comment]
The `compiz` people hang out in #637.
