### ISSUE TITLE
React-Native on WSL, Crunching Cruncher failed on valid *.png file.

### ISSUE THREAD

**Issue by ThaJay** [Microsoft/WSL#1523]
I want to develop with React-Native on WSL.

After installing all the dependencies
https://facebook.github.io/react-native/docs/getting-started.html (select linux)

Everything is in place, I even have android studio running through VcXsrv (although it does have memory errors; https://github.com/Microsoft/BashOnWindows/issues/1479, https://github.com/Microsoft/BashOnWindows/issues/1403, https://github.com/Microsoft/BashOnWindows/issues/922, https://github.com/Microsoft/BashOnWindows/issues/851, these issues make me think a fix is inbound. Not needed to build react-native apps anyway.)

```bash
PS> bash
$ react-native init test
$ cd test
$ react-native run-android
```
results in:
```bash
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Crunching Cruncher abc_btn_rating_star_on_mtrl_alpha.png failed, see logs
```

I don't know why Crunching Cruncher errors on perfectly valid files. They are put in place by react-native init itself. Will provide the logs I'm asked for.

*Additional Information*

- React Native -v tells me I'm not inside a React Native directory. after I let it init and cd in there.
- tried on react-native 0.39.2 and 0.36.0
https://github.com/facebook/react-native/issues/11483

I don't have my work laptop at hand atm but I can check the windows build later. It's the latest slow ring build from 5 days ago.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Can you please take a strace of the failing command so we have more information for triage?  The contributing directions have the steps under 7 and 8 - https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md.

**Comment by peterlau** [comment]
Hi there, I'm attempting to do the same thing (react-native on WSL) and ran into this problem also.
Rather than try to make Android Studio work, I got the standalone linux Android SDK tools cli. Here's my output.

```
:app:mergeDebugResources
AAPT err(Facade for 99504610): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
AAPT err(Facade for 1548069168): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
AAPT err(Facade for 1824115808): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
AAPT err(Facade for 1943320656): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
AAPT err(Facade for 963677941): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Thread(png-cruncher_5): Stream closed
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Thread(png-cruncher_1): Stream closed
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Thread(png-cruncher_4): Stream closed
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Thread(png-cruncher_2): Stream closed
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Thread(png-cruncher_3): Stream closed
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
AAPT err(Facade for 701060539): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
AAPT err(Facade for 1232572856): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
AAPT err(Facade for 1278116890): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
AAPT err(Facade for 1817900584): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Thread(png-cruncher_8): Broken pipe
java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Thread(png-cruncher_10): Broken pipe
java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Thread(png-cruncher_7): Stream closed
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Thread(png-cruncher_6): Stream closed
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
AAPT err(Facade for 1383730891): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Thread(png-cruncher_9): Broken pipe
java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
AAPT err(Facade for 1585781499): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
AAPT err(Facade for 1048155502): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
AAPT err(Facade for 2082165956): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
AAPT err(Facade for 2043722358): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Thread(png-cruncher_13): Broken pipe
java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Thread(png-cruncher_12): Broken pipe
java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Thread(png-cruncher_14): Broken pipe
java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Thread(png-cruncher_11): Stream closed
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
AAPT err(Facade for 950731733): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Thread(png-cruncher_15): Broken pipe
java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
AAPT err(Facade for 998697396): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
AAPT err(Facade for 455568591): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
AAPT err(Facade for 1798668517): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
AAPT err(Facade for 1502650515): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Thread(png-cruncher_17): Stream closed
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Thread(png-cruncher_18): Stream closed
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Thread(png-cruncher_19): Stream closed
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
AAPT err(Facade for 411183403): /usr/local/lib/android/build-tools/23.0.1/aapt: 2: /usr/local/lib/android/build-tools/23.0.1/aapt: Syntax error: newline unexpected (expecting ")")
Exception while processing task java.lang.RuntimeException: AAPT process not ready to receive commands
Thread(png-cruncher_20): Broken pipe
java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Thread(png-cruncher_16): Stream closed
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
        at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
        at java.lang.Thread.run(Thread.java:748)
Error: java.util.concurrent.ExecutionException: java.lang.RuntimeException: AAPT process not ready to receive commands
:app:mergeDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: java.lang.RuntimeException: AAPT process not ready to receive commands

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7 mins 38.685 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
pe
```

**Comment by peterlau** [comment]
This is not a direct solution to your problem, I've found a reasonably smooth workflow for working with react-native on WSL. Realistically, you'll want install native Windows Android Studio installed anyway for the Intellij IDE and the emulator. The trick is to separate out the Gradle based Android compile.

Workflow:
1) All project setup and package management performed in WSL with npm/yarn. react-native-cli installed globally in WSL. No need for a duplicate windows binary node/npm stack.

2) Don't use `react-native run-android`, instead compile and deploy from cmd using `gradlew.bat debugInstall`, or with the Creator's Update, you can do this from inside your bash shell `/mnt/c/Windows/System32/cmd.exe /C gradlew.bat installDebug`.  This can be done from the ./android directory within the project. Don't use the unix gradle script.

3) Once the APK has been assembled and uploaded to your device or emulator, run the node debug server from within WSL using the command `react-native start`.

Hope this helps.

**Comment by PhilT** [comment]
@peterlau  thanks for sharing this. I managed to get up and running with this setup. One thing that got me being new to Android and gradle was that you have to be in the android folder to run `gradlew` with the `installDebug` task.

**Comment by peterlau** [comment]
No problem! One thing I forgot to mention (for anyone wanting to replicate this workflow) is of course you'll need to have your react-native/android project set up on your windows file system (/mnt/c) where it is visible to native windows programs - I have my symlinked from ~/workspace.

**Comment by DavidLi-Minxiao** [comment]
@PhilT, how would you do debugging?

**Comment by elforce001** [comment]
Hi @peterlau. I did all that and it's still not working yet. When I run "react-native start" from wsl on vs code, the server starts but doesn't pass from the following message:

"Metro Bundler ready.

Loading dependency graph, done."

**Comment by peterlau** [comment]
Sounds like the bundler is ready but not getting any requests. Have you enabled your tcp tunnel as @dlimx suggested?

**Comment by williscool** [comment]
All have react native running consistently on WSL

Check out my notes on it here

https://github.com/facebook/react-native/issues/16798#issuecomment-430460451 

Would love to help get 

```
react-native run-android
```

across the finish line on WSL,

**Comment by therealkenc** [comment]
This one is sitting in the same [spot it](https://github.com/Microsoft/WSL/issues/1523#issuecomment-270959175) was in January 2017. Needs (1) CLI repro steps from clean install (2) the failure mode and (3) a threaded strace log in a gist. From the looks of your react-native link it probably deserves a new issue tracker. The OP on this one was some kind of build fail that never got attention for lack.
