### ISSUE TITLE
Gradle throws an Exception when run with the --no-daemon option

### ISSUE THREAD

**Issue by jverne** [microsoft/WSL#1593]
* A brief description
Gradle (or gradlew) will throw an IllegalArgumentException when you pass the --no-daemon option. The Gradle command will complete, but it looks like some cleanup code bails at the end. It doesn't even need to run any tasks successfully -- i.e., you can just run "gradle --no-daemon tasks" anywhere and it always throws an Exception.

I have not tried a different version of the JVM, other than the default Java 8ish that Xenial provides.

* Expected results
Gradle runs without throwing an exception when using the --no-daemon option

* Actual results (with terminal output if applicable)
```
jverne@frigga:~/John/01-create-build-scan$ gradle tasks
:tasks

------------------------------------------------------------
All tasks runnable from root project
------------------------------------------------------------

Build tasks
-----------
assemble - Assembles the outputs of this project.
build - Assembles and tests this project.
buildDependents - Assembles and tests this project and all projects that depend on it.
buildNeeded - Assembles and tests this project and all projects it depends on.
classes - Assembles main classes.
clean - Deletes the build directory.
jar - Assembles a jar archive containing the main classes.
testClasses - Assembles test classes.

Build Scan tasks
----------------
buildScanPublishPrevious - Publishes the data captured by the last build to the Build Scan server.

Build Setup tasks
-----------------
init - Initializes a new Gradle build. [incubating]
wrapper - Generates Gradle wrapper files. [incubating]

Documentation tasks
-------------------
javadoc - Generates Javadoc API documentation for the main source code.

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project '01-create-build-scan'.
components - Displays the components produced by root project '01-create-build-scan'. [incubating]
dependencies - Displays all dependencies declared in root project '01-create-build-scan'.
dependencyInsight - Displays the insight into a specific dependency in root project '01-create-build-scan'.
dependentComponents - Displays the dependent components of components in root project '01-create-build-scan'. [incubating]
help - Displays a help message.
model - Displays the configuration model of root project '01-create-build-scan'. [incubating]
projects - Displays the sub-projects of root project '01-create-build-scan'.
properties - Displays the properties of root project '01-create-build-scan'.
tasks - Displays the tasks runnable from root project '01-create-build-scan'.

Verification tasks
------------------
check - Runs all checks.
test - Runs the unit tests.

Rules
-----
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
Pattern: upload<ConfigurationName>: Assembles and uploads the artifacts belonging to a configuration.

To see all tasks and more detail, run gradle tasks --all

To see more detail about a task, run gradle help --task <task>

BUILD SUCCESSFUL

Total time: 1.064 secs
jverne@frigga:~/John/01-create-build-scan$ gradle --no-daemon tasks
:tasks

------------------------------------------------------------
All tasks runnable from root project
------------------------------------------------------------

Build tasks
-----------
assemble - Assembles the outputs of this project.
build - Assembles and tests this project.
buildDependents - Assembles and tests this project and all projects that depend on it.
buildNeeded - Assembles and tests this project and all projects it depends on.
classes - Assembles main classes.
clean - Deletes the build directory.
jar - Assembles a jar archive containing the main classes.
testClasses - Assembles test classes.

Build Scan tasks
----------------
buildScanPublishPrevious - Publishes the data captured by the last build to the Build Scan server.

Build Setup tasks
-----------------
init - Initializes a new Gradle build. [incubating]
wrapper - Generates Gradle wrapper files. [incubating]

Documentation tasks
-------------------
javadoc - Generates Javadoc API documentation for the main source code.

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project '01-create-build-scan'.
components - Displays the components produced by root project '01-create-build-scan'. [incubating]
dependencies - Displays all dependencies declared in root project '01-create-build-scan'.
dependencyInsight - Displays the insight into a specific dependency in root project '01-create-build-scan'.
dependentComponents - Displays the dependent components of components in root project '01-create-build-scan'. [incubating]
help - Displays a help message.
model - Displays the configuration model of root project '01-create-build-scan'. [incubating]
projects - Displays the sub-projects of root project '01-create-build-scan'.
properties - Displays the properties of root project '01-create-build-scan'.
tasks - Displays the tasks runnable from root project '01-create-build-scan'.

Verification tasks
------------------
check - Runs all checks.
test - Runs the unit tests.

Rules
-----
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
Pattern: upload<ConfigurationName>: Assembles and uploads the artifacts belonging to a configuration.

To see all tasks and more detail, run gradle tasks --all

To see more detail about a task, run gradle help --task <task>

BUILD SUCCESSFUL

Total time: 4.33 secs
Problems handling incoming cache access requests.
java.lang.IllegalArgumentException: Unexpected protocol version 0 received in lock contention notification message
        at org.gradle.cache.internal.FileLockCommunicator.decode(FileLockCommunicator.java:88)
        at org.gradle.cache.internal.FileLockCommunicator.receive(FileLockCommunicator.java:61)
        at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler$1.doRun(DefaultFileLockContentionHandler.java:67)
        at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler$1.run(DefaultFileLockContentionHandler.java:54)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
jverne@frigga:~/John/01-create-build-scan$
```
* Your Windows build number
Microsoft Windows [Version 10.0.14986]

* Steps / All commands required to reproduce the error from a brand new installation 
1. Install any recent (v2.x all the way to v3.x) version of Gradle. I'm using "sdkman" but it doesn't matter.
2. Run Gradle in any directory with any trivial built-in task (e.g., "help" or "tasks")

* Strace of the failing command
strace.zip attached in a follow on comment.

* Required packages and commands to install
gradle, java 8

**Comment by therealkenc** [comment]
There's no `EINVAL` in your `strace` to match the Java `IllegalArgumentException`. Probably going to need `strace -f`.

**Comment by jverne** [comment]
Here's an strace caught with -f.

[strace.zip](https://github.com/Microsoft/BashOnWindows/files/704342/strace.zip)

**Comment by nirfun** [comment]
I'm facing the same issue (version 1709).
Looks related to [issue 1712](https://github.com/Microsoft/WSL/issues/1712 ).
Maybe @benhillis can shed some light on this

**Comment by noel-yap** [comment]
I'm seeing the same behavior on `Microsoft Windows [Version 10.0.16299.309]`.

**Comment by therealkenc** [comment]
> java.lang.IllegalArgumentException: Unexpected protocol version 0 received in lock contention notification message

forward /dupe #1900
