### ISSUE TITLE
"sudo do-release-upgrade" gave GLIBCXX_3.4.21 not defined in file libstdc++.so.6 error messages

### ISSUE THREAD

**Issue by tommai78101** [Microsoft/WSL#1865]
### Brief Description:

I have Creator's Update. I have done a `sudo do-release-upgrade` from Trusty to Xenial in Bash. The installation succeeded, but at the very end of the installation process, it asked me if I want to restart the system.

I don't know if "restarting the system" meant it will restart Windows 10, or it will restart Bash. Nonetheless, I confirmed it to restart, and then it started throwing error messages.

These error messages are the same as the output of doing another `sudo do-release-upgrade` after I restarted Windows 10 and launched Bash.

### Expected Results:

As far as I can tell, I believed it should notify me that there is nothing left to upgrade, or some other messages saying that I'm on the latest version available.

### Actual Results (with terminal output if applicable):

```
Nintendo@NorthAmerica: ~
$ sudo do-release-upgrade
[sudo] password for Nintendo:
Traceback (most recent call last):
  File "/usr/bin/do-release-upgrade", line 11, in <module>
    from UpdateManager.Core.MetaRelease import MetaReleaseCore
  File "/usr/lib/python3/dist-packages/UpdateManager/Core/MetaRelease.py", line 25, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0: symbol _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0: symbol _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/do-release-upgrade", line 11, in <module>
    from UpdateManager.Core.MetaRelease import MetaReleaseCore
  File "/usr/lib/python3/dist-packages/UpdateManager/Core/MetaRelease.py", line 25, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0: symbol _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
Nintendo@NorthAmerica: ~
$
```

### Your Windows build number:

Version 1703 (OS Build 15063.13)

### Steps / All commands required to reproduce the error from a brand new installation:

1. Start from Bash on Windows, Ubuntu version, Trusty (14.04 LTS).
2. Do `sudo do-release-upgrade` and then complete the entire kernel upgrade to Xenial (16.04 LTS).
3. Once it reaches the end, and it asks you if you wished to restart the system, type `Y` and continue.
4. It should throw the error messages, mentioned above.

### Strace of the failing command:

I don't know if this is `strace`, but here it is:

```
Nintendo@NorthAmerica: ~
$ sudo strace -c do-release-upgrade
[sudo] password for Nintendo:
Traceback (most recent call last):
  File "/usr/bin/do-release-upgrade", line 11, in <module>
    from UpdateManager.Core.MetaRelease import MetaReleaseCore
  File "/usr/lib/python3/dist-packages/UpdateManager/Core/MetaRelease.py", line 25, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0: symbol _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0: symbol _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/do-release-upgrade", line 11, in <module>
    from UpdateManager.Core.MetaRelease import MetaReleaseCore
  File "/usr/lib/python3/dist-packages/UpdateManager/Core/MetaRelease.py", line 25, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0: symbol _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
  0.00    0.000000           0       328           read
  0.00    0.000000           0        32           write
  0.00    0.000000           0       212         2 open
  0.00    0.000000           0       225           close
  0.00    0.000000           0       712       102 stat
  0.00    0.000000           0       363           fstat
  0.00    0.000000           0        11           lstat
  0.00    0.000000           0       182         6 lseek
  0.00    0.000000           0       103           mmap
  0.00    0.000000           0        54           mprotect
  0.00    0.000000           0        20           munmap
  0.00    0.000000           0        38           brk
  0.00    0.000000           0        68           rt_sigaction
  0.00    0.000000           0         1           rt_sigprocmask
  0.00    0.000000           0        27        15 ioctl
  0.00    0.000000           0        23        23 access
  0.00    0.000000           0         3           dup
  0.00    0.000000           0         1           execve
  0.00    0.000000           0        25           fcntl
  0.00    0.000000           0        48           getdents
  0.00    0.000000           0         4         2 readlink
  0.00    0.000000           0         1           getrlimit
  0.00    0.000000           0         1           sysinfo
  0.00    0.000000           0         1           getuid
  0.00    0.000000           0         1           getgid
  0.00    0.000000           0         1           geteuid
  0.00    0.000000           0         1           getegid
  0.00    0.000000           0         1           sigaltstack
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         2           time
  0.00    0.000000           0         2           futex
  0.00    0.000000           0         1           set_tid_address
  0.00    0.000000           0         3           clock_gettime
  0.00    0.000000           0         1           set_robust_list
  0.00    0.000000           0         2           getrandom
------ ----------- ----------- --------- --------- ----------------
100.00    0.000000                  2499       150 total
Nintendo@NorthAmerica: ~
$
```

* Required packages and commands to install

If you consider the Ubuntu Xenial 16.04 LTS as the required packages, and yes, those are required.

The command to install the new kernel (or do an upgrade) is `sudo do-release-upgrade`.

**Comment by fpqc** [comment]
There shouldn't be a kernel package at all...

**Comment by tommai78101** [comment]
Is that a good thing or a bad thing?

**Comment by fabiodbr** [comment]
I've just had this problem when upgrading ubuntu distribution on linux
I saw that:
```
# ls /usr/lib/x86_64-linux-gnu/libstdc++.so.6*
libstdc++.so.6 -> libstdc++.so.6cd*
libstdc++.so.6.0.20*
libstdc++.so.6.0.21
libstdc++.so.6cd -> libstdc++.so.6.0.20*
```
libstdc++.so.6 -> libstdc++.so.6cd -> **libstdc++.so.6.0.20**

But there were two files: libstdc++.so.6.0.21 and libstdc++.so.6.0.20

I've changed the symbolic link to point to latest version libstdc++.so.6.0.21

```
# cd /usr/lib/x86_64-linux-gnu
# rm libstdc++.so.6cd
# chmod +x libstdc++.so.6.0.21
# ln -s  libstdc++.so.6.0.21 libstdc++.so.6cd
```

```
libstdc++.so.6 -> libstdc++.so.6cd*
libstdc++.so.6.0.20*
libstdc++.so.6.0.21*
libstdc++.so.6cd -> libstdc++.so.6.0.21*
```

and everything came back to normal

**Comment by aseering** [comment]
@fabiodbr -- hm...  Do you have any PPAs configured in `/etc/apt/sources.list.d/`?  This kind of failure often happens on regular Ubuntu if you have a PPA installed and that PPA doesn't handle release upgrades correctly.

If Ubuntu's `do-release-upgrade` script doesn't work, you can use Microsoft's script:  From a Windows Command Prompt, do `lxrun /uninstall`, then `lxrun /install`.  This will remove the entire WSL system and install the latest version.  But it should keep all files in `/home`.

**Comment by fabiodbr** [comment]
Hello @aseering, this bug happened to me in a Linux server and I got here while trying to search for a fix. The error was the same so I thought I would share my fix :)

Bash for windows is doing fine.

**Comment by tommai78101** [comment]
> This will remove the entire WSL system and install the latest version. But it should keep all files in /home.

That's enough for me to go reinstall WSL. Thanks.

**Comment by fabiodbr** [comment]
Sure, never rename... .21 was on my machine...

**Comment by jemerocay** [comment]
> @fabiodbr -- hm... Do you have any PPAs configured in `/etc/apt/sources.list.d/`? This kind of failure often happens on regular Ubuntu if you have a PPA installed and that PPA doesn't handle release upgrades correctly.
> 
> If Ubuntu's `do-release-upgrade` script doesn't work, you can use Microsoft's script: From a Windows Command Prompt, do `lxrun /uninstall`, then `lxrun /install`. This will remove the entire WSL system and install the latest version. But it should keep all files in `/home`.

Unfortunately, I think this is my last resort as I had a lot of stuff installed :/

Thanks .
