### ISSUE TITLE
java.io.RandomAccessFile.setLength() failed when Kafka shutting down

### ISSUE THREAD

**Issue by YihaoPeng** [Microsoft/WSL#2281]
I run Apache Kafka 2.12 at WSL at Windows 10 version 1703 build 15063.413.

When Kafka shutting down (with `kill <kafka-pid>`), it throws a lot of exceptions:
```log
...
[2017-07-04 02:24:38,547] INFO [Replica Manager on Broker 1]: Shut down completely (kafka.server.ReplicaManager)
[2017-07-04 02:24:38,548] INFO Shutting down. (kafka.log.LogManager)
[2017-07-04 02:24:38,576] WARN Invalid argument (kafka.utils.CoreUtils$)
java.io.IOException: Invalid argument
        at java.io.RandomAccessFile.setLength(Native Method)
        at kafka.log.AbstractIndex.$anonfun$resize$1(AbstractIndex.scala:114)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:213)
        at kafka.log.AbstractIndex.resize(AbstractIndex.scala:105)
        at kafka.log.AbstractIndex.$anonfun$trimToValidSize$1(AbstractIndex.scala:167)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:213)
        at kafka.log.AbstractIndex.trimToValidSize(AbstractIndex.scala:167)
        at kafka.log.AbstractIndex.close(AbstractIndex.scala:178)
        at kafka.log.LogSegment.$anonfun$close$2(LogSegment.scala:477)
        at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:78)
        at kafka.utils.Logging.swallowWarn(Logging.scala:94)
        at kafka.utils.Logging.swallowWarn$(Logging.scala:93)
        at kafka.utils.CoreUtils$.swallowWarn(CoreUtils.scala:48)
        at kafka.utils.Logging.swallow(Logging.scala:96)
        at kafka.utils.Logging.swallow$(Logging.scala:96)
        at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:48)
        at kafka.log.LogSegment.close(LogSegment.scala:477)
        at kafka.log.Log.$anonfun$close$2(Log.scala:530)
        at kafka.log.Log.$anonfun$close$2$adapted(Log.scala:530)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at kafka.log.Log.close(Log.scala:530)
        at kafka.log.LogManager.$anonfun$shutdown$7(LogManager.scala:280)
        at kafka.utils.CoreUtils$$anon$1.run(CoreUtils.scala:57)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
[2017-07-04 02:24:38,625] WARN Invalid argument (kafka.utils.CoreUtils$)
java.io.IOException: Invalid argument
        at java.io.RandomAccessFile.setLength(Native Method)
        at kafka.log.AbstractIndex.$anonfun$resize$1(AbstractIndex.scala:114)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:213)
        at kafka.log.AbstractIndex.resize(AbstractIndex.scala:105)
        at kafka.log.AbstractIndex.$anonfun$trimToValidSize$1(AbstractIndex.scala:167)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
...
```

The exception `java.io.IOException: Invalid argument` was repeated hundreds of times.
It looks like calling `java.io.RandomAccessFile.setLength()` failed.

When the Kafka start at the next time, it will fail with the same exception and crash:
```log
[2017-07-04 02:38:20,588] INFO [ThrottledRequestReaper-Fetch]: Starting (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2017-07-04 02:38:20,590] INFO [ThrottledRequestReaper-Produce]: Starting (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2017-07-04 02:38:20,592] INFO [ThrottledRequestReaper-Request]: Starting (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2017-07-04 02:38:20,703] INFO Loading logs. (kafka.log.LogManager)
[2017-07-04 02:38:20,781] WARN Found a corrupted index file due to requirement failed: Corrupt index found, index file (/var/lib/kafka/data/CommonEvents-0/00000000000000000000.index) has non-zero size but the last offset is 0 which is no larger than the base offset 0.}. deleting /var/lib/kafka/data/CommonEvents-0/00000000000000000000.timeindex, /var/lib/kafka/data/CommonEvents-0/00000000000000000000.index, and /var/lib/kafka/data/CommonEvents-0/00000000000000000000.txnindex and rebuilding index... (kafka.log.Log)
[2017-07-04 02:38:20,858] ERROR There was an error in one of the threads during logs loading: java.io.IOException: Invalid argument (kafka.log.LogManager)
[2017-07-04 02:38:20,862] FATAL [Kafka Server 1], Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.io.IOException: Invalid argument
        at java.io.RandomAccessFile.setLength(Native Method)
        at kafka.log.AbstractIndex.$anonfun$resize$1(AbstractIndex.scala:114)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:213)
        at kafka.log.AbstractIndex.resize(AbstractIndex.scala:105)
        at kafka.log.AbstractIndex.$anonfun$trimToValidSize$1(AbstractIndex.scala:167)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:213)
        at kafka.log.AbstractIndex.trimToValidSize(AbstractIndex.scala:167)
        at kafka.log.LogSegment.recover(LogSegment.scala:300)
        at kafka.log.Log.recoverSegment(Log.scala:335)
        at kafka.log.Log.$anonfun$loadSegmentFiles$3(Log.scala:314)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
        at kafka.log.Log.loadSegmentFiles(Log.scala:272)
        at kafka.log.Log.loadSegments(Log.scala:376)
        at kafka.log.Log.<init>(Log.scala:179)
        at kafka.log.Log$.apply(Log.scala:1581)
        at kafka.log.LogManager.$anonfun$loadLogs$12(LogManager.scala:172)
        at kafka.utils.CoreUtils$$anon$1.run(CoreUtils.scala:57)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
[2017-07-04 02:38:20,862] WARN Found a corrupted index file due to requirement failed: Corrupt index found, index file (/var/lib/kafka/data/NMCAuxBlock-0/00000000000000000000.index) has non-zero size but the last offset is 0 which is no larger than the base offset 0.}. deleting /var/lib/kafka/data/NMCAuxBlock-0/00000000000000000000.timeindex, /var/lib/kafka/data/NMCAuxBlock-0/00000000000000000000.index, and /var/lib/kafka/data/NMCAuxBlock-0/00000000000000000000.txnindex and rebuilding index... (kafka.log.Log)
[2017-07-04 02:38:20,881] INFO [Kafka Server 1], shutting down (kafka.server.KafkaServer)
[2017-07-04 02:38:20,895] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2017-07-04 02:38:20,903] INFO Session: 0x15d0b654d220003 closed (org.apache.zookeeper.ZooKeeper)
[2017-07-04 02:38:20,905] WARN Found a corrupted index file due to requirement failed: Corrupt index found, index file (/var/lib/kafka/data/NMCSolvedShare-0/00000000000000000000.index) has non-zero size but the last offset is 0 which is no larger than the base offset 0.}. deleting /var/lib/kafka/data/NMCSolvedShare-0/00000000000000000000.timeindex, /var/lib/kafka/data/NMCSolvedShare-0/00000000000000000000.index, and /var/lib/kafka/data/NMCSolvedShare-0/00000000000000000000.txnindex and rebuilding index... (kafka.log.Log)
[2017-07-04 02:38:20,908] INFO EventThread shut down for session: 0x15d0b654d220003 (org.apache.zookeeper.ClientCnxn)
[2017-07-04 02:38:20,920] INFO [Kafka Server 1], shut down completed (kafka.server.KafkaServer)
[2017-07-04 02:38:20,922] FATAL Exiting Kafka. (kafka.server.KafkaServerStartable)
[2017-07-04 02:38:20,933] WARN Found a corrupted index file due to requirement failed: Corrupt index found, index file (/var/lib/kafka/data/RawGbt-0/00000000000000000000.index) has non-zero size but the last offset is 0 which is no larger than the base offset 0.}. deleting /var/lib/kafka/data/RawGbt-0/00000000000000000000.timeindex, /var/lib/kafka/data/RawGbt-0/00000000000000000000.index, and /var/lib/kafka/data/RawGbt-0/00000000000000000000.txnindex and rebuilding index... (kafka.log.Log)
[2017-07-04 02:38:20,938] INFO [Kafka Server 1], shutting down (kafka.server.KafkaServer)

[1]  + 2144 exit 1     /work/kafka/bin/kafka-server-start.sh /work/kafka/config/server.properties
```

Both OpenJDK and Sun JDK have the same issue.
```log
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```
```log
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by sunilmut** [comment]
@YihaoPeng - Thanks for your post. Can you please collect a strace of the failing command and share out the trace files?
`strace -o <trace_file> -ff <failing_cmd>`

**Comment by YihaoPeng** [comment]
```bash
# switch to root
sudo -i

# install & setup zookeeper
apt install zookeeper zookeeper-bin zookeeperd
mv /etc/zookeeper/conf/zoo.cfg /etc/zookeeper/conf/zoo.cfg.default
echo 'initLimit=1
syncLimit=1
clientPort=2181
clientPortAddress=127.0.0.1
dataDir=/var/lib/zookeeper
server.1=127.0.0.1:2888:3888' > /etc/zookeeper/conf/zoo.cfg
echo 1 > /var/lib/zookeeper/myid
service zookeeper start

# install & setup kafka
cd /root
wget http://ftp.cuhk.edu.hk/pub/packages/apache.org/kafka/0.11.0.0/kafka_2.12-0.11.0.0.tgz
cd /usr/local
tar zxf /root/kafka_2.12-0.11.0.0.tgz
cd kafka_2.12-0.11.0.0/config
mv server.properties server.properties.default
echo 'broker.id=1
offsets.topic.replication.factor=1
message.max.bytes=20000000
replica.fetch.max.bytes=30000000
log.dirs=/var/lib/kafka/data
listeners=PLAINTEXT://127.0.0.1:9092
zookeeper.connect=127.0.0.1:2181
' > server.properties
mkdir -p /var/lib/kafka

# run kafka
cd ..
mkdir -p strace/1
strace -o strace/1/trace.log -ff ./bin/kafka-server-start.sh ./config/server.properties | tee strace/stdout-1.log
```

Now wait until `INFO [Kafka Server 1], started (kafka.server.KafkaServer)`.

Then, open a new `bash` and product some message to kafka:
```bash
cd /usr/local/kafka_2.12-0.11.0.0
# create topic
./bin/kafka-topics.sh --create --topic test --zookeeper 127.0.0.1:2181 --replication-factor 1 --partitions 1
# product message
echo -e 'a\nb\nc\nd\ne\nf\ng\nh\ni\nj\nk' | ./bin/kafka-console-producer.sh --broker-list 127.0.0.1:9092 --topic test
# stop kafka
./bin/kafka-server-stop.sh ./config/server.properties
# and kafka will shutdown with some exceptions.
```

Now start Kafka again.
```bash
mkdir -p strace/2
strace -o strace/2/trace.log -ff ./bin/kafka-server-start.sh ./config/server.properties | tee strace/stdout-2.log
```

Kafka will crash with the same exception.

There is my strace files:
[strace.zip](https://github.com/Microsoft/BashOnWindows/files/1129949/strace.zip)

**Comment by andrey-savov** [comment]
I can add that after this happens, Kafka 0.11 would no longer start so you would have to `rm -fr /tmp/kafka-logs` (delete all data) to recover.  This is pretty severe limitation IMHO.

**Comment by gao4263** [comment]
i meet same errors,  WLS has too many bugs

**Comment by therealkenc** [comment]
Your necropost worked.

PID 11426:
```
open("/var/lib/kafka/data/test-0/00000000000000000000.timeindex", O_RDWR|O_CREAT|O_EXCL, 0666) = 122
fstat(122, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
close(122)                              = 0
open("/var/lib/kafka/data/test-0/00000000000000000000.timeindex", O_RDWR|O_CREAT, 0666) = 122
fstat(122, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
lseek(122, 0, SEEK_CUR)                 = 0
ftruncate(122, 10485756)                = 0
lseek(122, 0, SEEK_SET)                 = 0
lseek(122, 0, SEEK_CUR)                 = 0
lseek(122, 0, SEEK_END)                 = 10485756
lseek(122, 0, SEEK_SET)                 = 0
fstat(122, {st_mode=S_IFREG|0644, st_size=10485756, ...}) = 0
mmap(NULL, 10485756, PROT_READ|PROT_WRITE, MAP_SHARED, 122, 0) = 0x7f57fac00000
close(122) 
```
PID 12453:
```
open("/var/lib/kafka/data/test-0/00000000000000000000.index", O_RDWR|O_CREAT, 0666) = 100
fstat(100, {st_mode=S_IFREG|0644, st_size=10485760, ...}) = 0
lseek(100, 0, SEEK_CUR)                 = 0
ftruncate(100, 0)                       = -1 EINVAL (Invalid argument)
```

#902

**Comment by bad-blood** [comment]
I have the same problem in WSL now, is there a solution？ @YihaoPeng

**Comment by RchrdMgwtz** [comment]
I'm still facing that issue too, also working in WSL on Windows 10 1809. The workaround by removing the `kafka-logs` works but is a really unpleasant solution.

**Comment by sasakitoa** [comment]
I had a same issue but resolved by updating WSL from version 1 to 2.

**Comment by chenjing1294** [comment]
I have the same problem in WSL now, is there a solution？
```
Windows: Microsoft Windows 10 10.0.19044
WSL: Ubuntu 18.04.5 LTS on Windows 10 x86_64
```

**Comment by SergeSavel** [comment]
I am having this issue too on Windows 11 Pro 22H2 (ARM64).
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22621.4037
