### ISSUE TITLE
EACCES: permission denied installing on mnt for NPM and virtualenv

### ISSUE THREAD

**Issue by ishraqiyun77** [Microsoft/WSL#2610]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing the GitHub bug number. Ideally, please [configure your machine to capture minidumps](https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a), repro the issue, and send the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16299.19]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

`npm install`

* What's wrong / what should be happening instead:

The Bash on Ubuntu on Windows environment I have been using for most of the year broke when I came in Tuesday after the Fall update was applied. `virutalenv` quit working primarily and I couldn't fix it.  Couldn't do `lxrun /uninstall /full`, nor `lxrun /uninstall`, to start setting up the environment again. Deleted `AppData\Local\lxss` manually. Error codes when trying `lxrun /install`.  Ran as admin which seemed to work but just told me to go to the Windows Store.

Go to Windows Store. Eventually it let me download and install it after about an hour of "error installing messages". Start to setup the environment again. 

Mind you, I had my `virtualenv` and `node_modules` on the C:\ in the previous setup without issue. Permission issues for `virtualenv` when I try to add a new machine and end up just putting them in `/home/ishraqiyun77/.venvs`. Basically have the directories wide open for everyone to access and am admin.

Move onto `npm`. The result is below for that endeavor. Permissions on C:\ are unchanged and the directory is `777` where `node_modules` is trying to install.

Seems like it is related to this topic:

https://github.com/Microsoft/WSL/issues/3

Guess I can put the `node_modules` globally, but want to package them with the app which is on C:\. (Also want to do the same with `venvs`).

Not sure why this broke and why I was having zero issues when I set this up earlier this year. Getting zero done now. Awesome.

`lxrun /install` is working now in `cmd.exe`, but same issues.

```
[npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN ClientPortal@1.0.0 No repository field.
npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /mnt/c/Users/ishraqiyun77/dev/current/client/node_modules/.staging/acorn-8644ee2c
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rename

npm ERR! Error: EACCES: permission denied, rename '/mnt/c/Users/ishraqiyun77/dev/current/client/node_modules/.staging/acorn-8644ee2c' -> '/mnt/c/Users/ishraqiyun77/dev/current/client/node_modules/acorn'
npm ERR!     at destStatted (/usr/share/npm/lib/install/action/finalize.js:25:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR!
npm ERR! Error: EACCES: permission denied, rename '/mnt/c/Users/ishraqiyun77/dev/current/client/node_modules/.staging/acorn-8644ee2c' -> '/mnt/c/Users/ishraqiyun77/dev/current/client/node_modules/acorn'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, rename '/mnt/c/Users/ishraqiyun77/dev/current/client/node_modules/.staging/acorn-8644ee2c' -> '/mnt/c/Users/ishraqiyun77/dev/current/client/node_modules/acorn'] parent: 'ClientPortal' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/ishraqiyun77/dev/current/client/npm-debug.log](url)
```

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by ishraqiyun77** [comment]
Just tested on a computer that (I don't think) has received the update and everything is still working fine: 

`Microsoft Windows [Version 10.0.15063]`

`npm install` works fine on a mounted drive as does `virtualenv`.

**Comment by ishraqiyun77** [comment]
Had to roll back the update and now I am able to get some work done.
