### ISSUE TITLE
bash spawn node.exe "PIPE ERROR"

### ISSUE THREAD

**Issue by 131** [Microsoft/WSL#2629]
* Your Windows build number:  Microsoft Windows [version 10.0.16299.19]

* What you're doing and what's happening:  
```
#in WSL bash
node.exe -e "console.log(42)"
```

* What's wrong / what should be happening instead:
Crashes complaining about proces pipes, should output dummy 42.
Works fine in cmd.exe (outside WSL)

Full trace (nodejs 8.9.0.exe trace, yet might be usefull) 
```
net.js:200
    this._handle.open(options.fd);
                 ^
Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:200:18)
    at createWritableStdioStream (internal/process/stdio.js:164:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:14:14)
    at console.js:243:38
    at NativeModule.compile (bootstrap_node.js:596:7)
    at Function.NativeModule.require (bootstrap_node.js:541:18)
    at setupGlobalConsole (bootstrap_node.js:310:41)
    at startup (bootstrap_node.js:70:7)
    at bootstrap_node.js:608:3
```

**Comment by 131** [comment]
Dupe #2370
