### ISSUE TITLE
Can't run node.exe in WSL with latest builds (ubuntu)

### ISSUE THREAD

**Issue by marchaos** [Microsoft/WSL#2828]
There are some existing issues for this that have been closed. This still seems to happen with 162899 + node version 9.4.0

Microsoft Windows [Version 10.0.16299.192]

$ node.exe -v
> v9.4.0

$ node.exe
net.js:214
    this._handle.open(options.fd);
                 ^
Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:214:18)
    at createWritableStdioStream (internal/process/stdio.js:164:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:14:14)
    at console.js:251:38
    at NativeModule.compile (bootstrap_node.js:605:7)
    at Function.NativeModule.require (bootstrap_node.js:550:18)
    at setupGlobalConsole (bootstrap_node.js:320:41)
    at startup (bootstrap_node.js:76:7)
    at bootstrap_node.js:617:3
marchaos@DESKTOP-Q36F1A9:~$

**Comment by therealkenc** [comment]
Ben will have to confirm but this is the same backtrace as #2370 which is open.

**Comment by benhillis** [comment]
Yes this is the same issue.
