### ISSUE TITLE
WSL ubuntu commands intermittently fail with access denied error

### ISSUE THREAD

**Issue by mattmon1** [microsoft/WSL#2931]
This issue was moved from #2323. I believe that I'm seeing a variant of #2323 and thought that I'd contribute my findings to see if they can help expedite a resolution.

I'm running windows 10 preview OS build 17074.1002. My application is a .NET 4.7 windows service, which executes 'ubuntu run [linuxCommand]' in a diagnostics process and collects results from standard output and standard error.

The application performs exceptionally well for days on end with no Linux errors. However, occasionally the application hits a time window (for example: last night between 1AM and 9AM) where Linux commands fail with the following exception:

System.ComponentModel.Win32Exception (0x80004005): The file cannot be accessed by the system
 at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
 at System.Diagnostics.Process.Start()

Only new command invocations fail. Linux commands that were running prior to the initial exception, at the start of the time window, continue to execute without error and I can find their pid's by running ps -x from an ubuntu window. My machine was running windows defender when the exception occurred. After reading the suggestions in #2323, I've turned defender off in hopes that this will prevent the exceptions from occurring in the future.

My hopes are that the WSL community can provide a fix or workaround for this issue.

**Comment by mattmon1** [comment]
For the time being, I installed the workaround defined in #2577 and rolled back my settings, which disabled defender since it is good to have some type of virus protection these days. Also, if both are applied simultaneously and the issue doesn't reappear, it will be hard to tell if the disabling defender worked or if applying the workaround worked.

Since the issue is intermittent, my plans are to monitor for the issue and report back with findings.

My hopes are that the WSL community can provide a fix or identify when a fix will be available for this issue.

**Comment by mattmon1** [comment]
Update: All my machines have been upgraded to the spring creators update RTM build 17133 at this point. I've run with the workaround in #2577 on multiple machines and have not encountered this issue on any machine where the workaround is applied. 

Just posting to reach out and see if the WSL team can provide an update on a fix for this issue?

Looking forward to getting on the official GA: Windows 10 Spring Creators Update / Windows 10 version 1803, Cumulative Update for Windows 10 Version Next, Redstone 4 - my hopes are that a fix for this issue will be in 1803.
