### ISSUE TITLE
Socket closed on rabbitmq-server

### ISSUE THREAD

**Issue by JetUni** [Microsoft/WSL#3376]
* Your Windows build number:  `Microsoft Windows [Version 10.0.17134.165]`

* What you're doing and what's happening: Running the website and clicking on a link that sends a task via Python celery to `rabbitmq-server`. This results in the following error

```
ERROR:django.request:Internal Server Error: /claim/i/3955345/
Traceback (most recent call last):
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jet/sites/str-prod/tracking/views.py", line 1915, in buyitem
    form.instance.send_buy_email(request)
  File "/home/jet/sites/str-prod/tracking/models.py", line 2330, in send_buy_email
    html_message=html_msg)
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/celery/app/task.py", line 565, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/celery/app/amqp.py", line 310, in publish_task
    **kwargs
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/kombu/connection.py", line 457, in _ensured
    interval_max)
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/kombu/connection.py", line 742, in connection
    self._connection = self._establish_connection()
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/kombu/connection.py", line 697, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/amqp/connection.py", line 180, in __init__
    (10, 30),  # tune
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 67, in wait
    self.channel_id, allowed_methods, timeout)
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/amqp/connection.py", line 241, in _wait_method
    channel, method_sig, args, content = read_timeout(timeout)
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/amqp/connection.py", line 330, in read_timeout
    return self.method_reader.read_method()
  File "/home/jet/sites/str-prod/env/local/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
    raise m
IOError: Socket closed
```

* What's wrong / what should be happening instead: Our website is coded in Python and uses celery to send tasks to `rabbitmq-server`. On a regular linux server running Ubuntu 16.04, no configuration is needed and the website works as soon as `rabbitmq-server` is installed. I expect that the same should happen when I install `rabbitmq-server` on WSL.

**Comment by therealkenc** [comment]
CONTRIBUTING.md. Please link a [gist](https://gist.github.com/) of a [`strace(1)`](http://man7.org/linux/man-pages/man1/strace.1.html) output log and repro steps. Smaller the test case that exhibits the problem the better.

> uses celery to send tasks

Celery with Cheese Whiz... _mmmm_

**Comment by benhillis** [comment]
@therealkenc -

> Celery with ~~Cheese Whiz~~ Peanut Butter... mmmm

**Comment by stratoukos** [comment]
This is still happening and seems to be an issue with RabbitMQ rather than with celery and the rest of the python stack.

A smaller test case is:

-  install and run rabbitmq (on debian `apt install rabbitmq-server; /etc/init.d/rabbtimq-server start`)
-  connect with netcat (`nc localhost 5672`)

In WSL the connection is closed immediately instead of waiting for input.

Strace is extremely noisy, since you're basically stracing the Erlang VM.
