### ISSUE TITLE
Problem with Alfa device

### ISSUE THREAD

**Issue by SCREAM2017** [Microsoft/WSL#3488]
```
scream@ADWAA:/mnt/c/Users/Ad$ sudo wifite
  .               .
.´  ·  .     .  ·  `.  wifite 2.1.6
:  :  :  (¯)  :  :  :  automated wireless auditor
`.  ·  ` /¯\ ´  ·  .´  https://github.com/derv82/wifite2
  `     /¯¯¯\     ´


 [+] looking for wireless interfaces

 [!] airmon-ng did not find any wireless interfaces
 [!] make sure your wireless device is connected
 [!] see http://www.aircrack-ng.org/doku.php?id=airmon-ng for more info

 [!] Error: airmon-ng did not find any wireless interfaces

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/share/wifite/wifite/wifite.py", line 258, in run
 [!]        w.main()
 [!]    File "/usr/share/wifite/wifite/wifite.py", line 46, in main
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/usr/share/wifite/wifite/config.py", line 121, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/usr/share/wifite/wifite/tools/airmon.py", line 295, in ask
 [!]        raise Exception('airmon-ng did not find any wireless interfaces')
 [!]  Exception: airmon-ng did not find any wireless interfaces

 [!] Exiting

```

```
scream@ADWAA:/mnt/c/Users/Ad$ sudo airmon-ng

PHY     Interface       Driver          Chipset


scream@ADWAA:/mnt/c/Users/Ad$

```

Image :

https://f.top4top.net/p_962u0yl31.png

**Comment by therealkenc** [comment]
#2598 #1077

**Comment by SCREAM2017** [comment]
@therealkenc

 Hi, Please I do not speak English very well, my English is weak,

Give me a summary of the subject, and whether it has a solution or not, if it has a solution please I put it here

**Comment by SCREAM2017** [comment]
@therealkenc
--up
