### ISSUE TITLE
WSL not opening socket to RabbitMQ

### ISSUE THREAD

**Issue by alvarolloret** [Microsoft/WSL#3799]
# Checklist

- [ ]  output of ``celery -A proj report``:

```
software -> celery:3.1.26.post2 (Cipater) kombu:3.0.37 py:3.6.7
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:disabled
BROKER_URL: 'amqp://guest:********@localhost:5672//'
```

- [ ]contents of ``pip freeze`` in the issue.

I am using pipenv. Pipfile:
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
django = "*"
django-allauth = "*"
django-crispy-forms = "*"
django-debug-toolbar = "==1.10."
numpy = "==1.15.3"
colorama = "==0.4.0"
dateparser = "==0.7.0"
django-extensions = "*"
python-binance = "*"
misaka = "*"
django-celery = "*"
celery = "*"

[requires]
python_version = "3.6"
```

# Steps to Reproduce
I am in WSL:
1. sudo apt-get install rabbitmq-server
2. sudo service rabbitmq-server restart
3. chmod -R 777 ./     ## otherwise I don't have permissions

### Other infos
tasks.py:

```
from celery import Celery

# app = Celery('tasks', broker='amqp://jm-user1:sample@localhost/jm-vhost')
# app = Celery('tasks', broker='amqp://guest@localhost//')
app = Celery('tasks', broker='pyamqp://guest@localhost//')

@app.task
def add(x, y):
    return x + y
```

rabbitmqctl status:

```
[{pid,1716},
 {running_applications,
     [{rabbit,"RabbitMQ","3.6.10"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.3.0"},
      {ssl,"Erlang/OTP SSL application","8.2.3"},
      {public_key,"Public key infrastructure","1.5.2"},
      {asn1,"The Erlang ASN1 compiler version 5.0.4","5.0.4"},
      {rabbit_common,
          "Modules shared by rabbitmq-server and rabbitmq-erlang-client",
          "3.6.10"},
      {xmerl,"XML parser","1.3.16"},
      {crypto,"CRYPTO","4.2"},
      {os_mon,"CPO  CXC 138 46","2.4.4"},
      {compiler,"ERTS  CXC 138 10","7.1.4"},
      {mnesia,"MNESIA  CXC 138 12","4.15.3"},
      {syntax_tools,"Syntax tools","2.1.4"},
      {sasl,"SASL  CXC 138 11","3.1.1"},
      {stdlib,"ERTS  CXC 138 10","3.4.3"},
      {kernel,"ERTS  CXC 138 10","5.4.1"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:192] [kernel-poll:true]\n"},
 {memory,
     [{total,55943096},
      {connection_readers,0},
      {connection_writers,0},
      {connection_channels,0},
      {connection_other,0},
      {queue_procs,2744},
      {queue_slave_procs,0},
      {plugins,0},
      {other_proc,19080304},
      {mnesia,65712},
      {metrics,184888},
      {mgmt_db,0},
      {msg_index,42728},
      {other_ets,1769840},
      {binary,62120},
      {code,21390833},
      {atom,891849},
      {other_system,12634158}]},
 {alarms,[]},
 {listeners,[{clustering,25672,"::"},{amqp,5672,"::"}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,6791299072},
 {disk_free_limit,50000000},
 {disk_free,100481589248},
 {file_descriptors,
     [{total_limit,924},{total_used,2},{sockets_limit,829},{sockets_used,0}]},
 {processes,[{limit,1048576},{used,165}]},
 {run_queue,0},
 {uptime,4073},
 {kernel,{net_ticktime,60}}]
```

## Output:
when run: ` celery -A tasks worker --loglevel=info` I get the following output:

```
/home/alpha/.local/share/virtualenvs/alpha_trader-Ygew-b14/lib/python3.6/site-packages/celery/platforms.py:812: RuntimeWarning: You are running the worker with superuser privileges, which is
absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2019-01-23 08:38:30,353: WARNING/MainProcess] /home/alpha/.local/share/virtualenvs/alpha_trader-Ygew-b14/lib/python3.6/site-packages/celery/apps/worker.py:161: CDeprecationWarning:
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

 -------------- celery@Alvaro-Laptop v3.1.26.post2 (Cipater)
---- **** -----
--- * ***  * -- Linux-4.4.0-17763-Microsoft-x86_64-with-Ubuntu-18.04-bionic
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x7fd7952bcf60
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 12 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery


[tasks]
  . tasks.add

[2019-01-23 08:38:30,538: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: Socket closed.
Trying again in 2.00 seconds...

[2019-01-23 08:38:32,543: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: Socket closed.
Trying again in 4.00 seconds...
```

How can I open the socket to allow the communications?

**Comment by Biswa96** [comment]
Windows 10 build.number? Any strace? Any event log?

**Comment by alvarolloret** [comment]
Windows 10 build number: 
Version 1809 (OS Build 17763.253)

**Comment by alvarolloret** [comment]
It seems to be impossible to open the ports using rabbitMQ using WSL.
I have managed to recreate [this](https://groups.google.com/forum/#!topic/pika-python/_guKwF6RK-k) problem:

I did:

```
import pika
import logging
logging.basicConfig(level=logging.DEBUG)
connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
```

Which gave me the following error:

```
DEBUG:pika.adapters.select_connection:Using EPollPoller
DEBUG:pika.callback:Added: {'callback': <bound method Connection._on_connection_start of <SelectConnection CLOSED socket=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>, 'one_shot': True, 'only': None, 'arguments': None, 'calls': 1}
DEBUG:pika.callback:Added: {'callback': <bound method Connection._on_connection_close of <SelectConnection CLOSED socket=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>, 'one_shot': True, 'only': None, 'arguments': None, 'calls': 1}
DEBUG:pika.callback:Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7fd6d50b89c8>>, 'one_shot': False, 'only': None, 'arguments': None}
DEBUG:pika.callback:Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7fd6d50b8cc8>>, 'one_shot': False, 'only': None, 'arguments': None}
DEBUG:pika.callback:Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7fd6d50b8648>>, 'one_shot': False, 'only': None, 'arguments': None}
DEBUG:pika.adapters.select_connection:call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7fd6d50b49b0> with deadline=1548250839.2800937 and callback=<bound method Connection._on_connect_timer of <SelectConnection INIT socket=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>; now=1548250839.2800937; delay=0
INFO:pika.adapters.base_connection:Pika version 0.13.0 connecting to 127.0.0.1:5672
ERROR:pika.adapters.base_connection:Read empty data, calling disconnect
INFO:pika.connection:Disconnected from RabbitMQ at localhost:5672 (-1): EOF
ERROR:pika.connection:Incompatible Protocol Versions
ERROR:pika.connection:Connection setup failed due to The protocol returned by the server is not supported: (-1, 'EOF')
DEBUG:pika.callback:Processing 0:_on_connection_error
DEBUG:pika.callback:Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7fd6d50b89c8>> for "0:_on_connection_error"
DEBUG:pika.callback:Processing 0:_on_connection_closed
DEBUG:pika.callback:Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7fd6d50b8648>> for "0:_on_connection_closed"
DEBUG:pika.callback:Incremented callback reference counter: {'callback': <bound method Connection._on_connection_start of <SelectConnection CLOSED socket=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>, 'one_shot': True, 'only': None, 'arguments': None, 'calls': 2}
DEBUG:pika.callback:Incremented callback reference counter: {'callback': <bound method Connection._on_connection_close of <SelectConnection CLOSED socket=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>, 'one_shot': True, 'only': None, 'arguments': None, 'calls': 2}
ERROR:pika.adapters.blocking_connection:Connection open failed - The protocol returned by the server is not supported: (-1, 'EOF')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alpha/.local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 377, in __init__
    self._process_io_for_connection_setup()
  File "/home/alpha/.local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 417, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/home/alpha/.local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 469, in _flush_output
    raise maybe_exception
pika.exceptions.IncompatibleProtocolError: (-1, 'EOF')
```

**Comment by alvarolloret** [comment]
@Biswa96 Which strace command would you like me to run?

**Comment by therealkenc** [comment]
The `strace` is a start, but really what is needed here is repro steps. They look something like:
```
$ cat /proc/version
$ sudo apt install <something something something>
$ mkdir somewhere && cd somewhere
$ git clone somestuff # or curl or wget
$ somecommand
$ morecommands ...
$ strace -f -o somecommand.strace somecommand args args args
[link somecommand.strace to a gist]
```

**Comment by alvarolloret** [comment]
It seems to be a rabbitmq problem rather than one coming from windows. I was able to configure everything using Redis instead of Rabbitmq:

```
sudo apt-get install redis-server
sudo service redis-server restart
pip install celery
chmod -R 777 ./
```

Place on any folder you want to execute the worker the file `tasks.py`:

```
from celery import Celery

app = Celery('tasks', broker='redis://localhost:6379')

@app.task
def add(x, y):
    return x + y
```

Then execute the following:

`> celery -A tasks worker --loglevel=info
`

The socket is now open!

**Comment by florent-izypay** [comment]
Just in case someone lands here, struggling with rabbitmq and WSL, with bare config, my 2 cent:

Default listening port for AMQP seems to be an IPv6 binding `[::]` on port 5672
You can add this configuration to your rabbitmq.conf file to instruct RabbitMQ to listen on IPv4

`listeners.tcp.default = 127.0.0.1:5672`

https://stackoverflow.com/questions/54322974/wsl-error-mainprocess-consumer-cannot-connect-to-amqp-guest127-0-0-156

**Comment by ckhadye** [comment]
Thanks @florent-izypay it worked.

**Comment by therealkenc** [comment]
> Default listening port for AMQP seems to be an IPv6 binding [::] on port 5672

/dupe #4851 #5298

**Comment by viebel** [comment]
@florent-izypay you saved me lot of frustration. Thank you!
