### ISSUE TITLE
add-apt-repository not working with Ubuntu & Pengwin

### ISSUE THREAD

**Issue by Gil-1** [microsoft/WSL#4486]
Windows build number : 18975.1000
WSL version : 2

I was using wsl 1 without any issue before and was able to add some ppa with a command like the following
```
sudo add-apt-repository ppa:ondrej/nginx
```

Yesterday I went to Windows Fast Ring to test WSL2.
I removed the Ubuntu distro which was working before and started fresh to see what improvements could have been made.

Whenever I'm trying to add a ppa it always hang.
I cancel the operation with ctrl+c to see some python errors:
```
 sudo add-apt-repository ppa:ondrej/nginx
 This branch follows latest NGINX Stable packages compiled against latest OpenSSL for HTTP/2 and TLS 1.3 support.

BUGS&FEATURES: This PPA now has a issue tracker: https://deb.sury.org/#bug-reporting

PLEASE READ: If you like my work and want to give me a little motivation, please consider donating: https://donate.sury.org
 More info: https://launchpad.net/~ondrej/+archive/ubuntu/nginx
Press [ENTER] to continue or ctrl-c to cancel adding it


^CTraceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 168, in <module>
    if not sp.add_source_from_shortcut(shortcut, options.enable_source):
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 737, in add_source_from_shortcut
    worker = self.check_and_add_key_for_whitelisted_shortcut(shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 678, in check_and_add_key_for_whitelisted_shortcut
    codename=self.distro.codename, distro=self.distro.id.lower())
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 371, in expand
    codename = get_current_series_from_lp(self._info["distribution"])
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 96, in get_current_series_from_lp
    return os.path.basename(get_info_from_lp(lp_url)["current_series_link"])
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 88, in get_info_from_lp
    return _get_https_content_py3(lp_url)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 102, in _get_https_content_py3
    lp_page = urllib.request.urlopen(request, cafile=LAUNCHPAD_PPA_CERT)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 1406, in connect
    super().connect()
  File "/usr/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```

I tested on Ubuntu (18.04 & 19.10) & with Pengwin.
Note that on pengwin I was needed to install this package:
```
sudo apt install -y software-properties-common
```

I have Kaspersky and tried to disable it, it didn't change anything.
At some point, some ppa's get added but I have no idea why as usually it fails with some errors.

Any idea if it's a bug or something else ?

**Comment by sirredbeard** [comment]
This may be telling:

>   File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)

Can you access other apt resources?

Also Kaspersky is known for causing issues with networking on WSL so it's good you disabled that to try and reproduce.

**Comment by Gil-1** [comment]
I can do apt update & upgrade.
Everything seems to update & I can install new packages.

Just not add ppa.

**Comment by sirredbeard** [comment]
I unfortunately cannot reproduce on Pengwin (with `sudo apt-get install -y software-properties-common`) on a fresh install of 18975.

I tried twice.

![Annotation 2019-09-10 164414](https://user-images.githubusercontent.com/33820650/64649333-ad036680-d3ea-11e9-9632-f20caa545868.png)

I see the socket error in your log and I know dbus is a dependency for software-properties-common (which is why Pengwin does not ship it by default) so I'm wondering if there's some remnant of your Kaspersky firewall maybe hanging around causing an issue.

Also just to rule it out, nuke resolve.conf with `sudo rm -r /etc/resolv.conf` exit and re-open Pengwin and try again.

**Comment by therealkenc** [comment]
Was able to reproduce this on Ubuntu Disco and 18975. My mode of fail was slightly different. It is resolver related alright, but I can't say wut. Tried the usual big hammer `sudo sh -c echo 8.8.8.8 > /etc/resolv.conf` but no joy.

![image](https://user-images.githubusercontent.com/7049700/64723729-ee951f80-d485-11e9-8905-4b915476d5c1.png)

**Comment by clockelliptic** [comment]
`sudo apt install -y software-properties-common` fixed this for me in Pengwin.

**Comment by irimia** [comment]
Disabling IPV6 in Windows fixed this.

**Comment by andrei0x309** [comment]
If you don't want to disable IPV6 in Windows, you can change the precedence in the WSL disto to iv4.

use:
`sudo nano /etc/gai.cong `
Uncomment line:
`precedence ::ffff:0:0/96  100`

Tested on WSL with Ubuntu 18.04

**Comment by brianpetro** [comment]
> Disabling IPV6 in Windows fixed this.

For others using WSL version 1, this was the only solution that worked from those mentioned above.

**Comment by apatuka** [comment]
None of those solutions worked for me, but what worked is doing `apt update && apt upgrade`
