### ISSUE TITLE
WSL1: uv_pipe_open when calling Windows node in command substitution 

### ISSUE THREAD

**Issue by aeschli** [microsoft/WSL#4511]
WSL1, Ubuntu 18.04 LTS, Windows 18970

- install NodeJS in Windows
- from a WSL1 shell, run `'/mnt/c/Program Files/nodejs/node.exe' -e 'console.log("hello")'`.  This works, 'hello' is printed
- now try 
`FOO=$('/mnt/c/Program Files/nodejs/node.exe' -e 'console.log("hello")'); echo "$FOO"`

Fails with error
```
net.js:264
    err = this._handle.open(fd);
                       ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:264:24)
    at createWritableStdioStream (internal/process/stdio.js:197:18)
    at process.getStdout [as stdout] (internal/process/stdio.js:20:14)
    at console.js:451:19
    at NativeModule.compile (internal/bootstrap/loaders.js:297:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:166:18)
    at setupGlobalConsole (internal/bootstrap/node.js:399:41)
    at startup (internal/bootstrap/node.js:137:7)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
```

works in WSL2

also tested in 1903 (18362), same behaviour

**Comment by therealkenc** [comment]
I was able to reproduce this on 19002 WSL1 but not WSL2. Windows NodeJS available [here](https://nodejs.org/dist/v13.0.1/node-v13.0.1-x64.msi).

![image](https://user-images.githubusercontent.com/7049700/67632357-75982e80-f85f-11e9-87c7-ef0af66b082b.png)

**Comment by asurkov** [comment]
I get the very same error when running:
``>bash -c "node -e 'console.log(3)' | tee tmp"``

```
net.js:314
      err = this._handle.open(fd);
                         ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:314:26)
    at createWritableStdioStream (internal/process/stdio.js:179:18)
    at process.getStdout [as stdout] (internal/process/stdio.js:28:14)
    at Object.get (internal/console/constructor.js:149:38)
    at Object.Console.<computed> (internal/console/constructor.js:271:46)
    at Object.log (internal/console/constructor.js:282:61)
    at [eval]:1:9
    at Script.runInThisContext (vm.js:116:20)
    at Object.runInThisContext (vm.js:306:38)
    at Object.<anonymous> ([eval]-wrapper:9:26) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'uv_pipe_open'
}
```

Is it same issue I suppose?

**Comment by asurkov** [comment]
> I get the very same error when running:
> `>bash -c "node -e 'console.log(3)' | tee tmp"`

btw, wsl2 fixes the problem (https://docs.microsoft.com/en-us/windows/wsl/wsl2-install)

**Comment by BrianVia** [comment]
Any update on this?  My work machine is on an older windows build so I'm unable to install WSL2 and would love to resolve this

**Comment by shogs** [comment]
Getting this on wsl 2 with a react app and trying to add electron to it.

For steps follow the following post: https://www.codementor.io/@randyfindley/how-to-build-an-electron-app-using-create-react-app-and-electron-builder-ss1k0sfer

**Comment by therealkenc** [comment]
This might end up destined for "use WSL2", but it isn't clear why it (the OP repro) shouldn't work on WSL1.
