### ISSUE TITLE
how can i fix this?

### ISSUE THREAD

**Issue by chen731** [microsoft/WSL#4552]
I am using spyder for the first time but when I finished all the installation the following error message occurs:

The error is:

Traceback (most recent call last):
File "C:\Users\w8ulrick8w\Anaconda3\envs\tensorflow\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\w8ulrick8w\Anaconda3\envs\tensorflow\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\w8ulrick8w\Anaconda3\envs\tensorflow\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\w8ulrick8w\Anaconda3\envs\tensorflow\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\w8ulrick8w\Anaconda3\envs\tensorflow\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\w8ulrick8w\Anaconda3\envs\tensorflow\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\w8ulrick8w\\AppData\\Roaming\\jupyter\\runtime\\kernel‑a574ea7d3239.json'

How can i fix this problem??

**Comment by therealkenc** [comment]
There is no CLI repro here to answer the question. Those `C:\` paths aren't WSL paths, they are Windows paths. If you've got a Windows install of Python, you'll probably find a better WSL experience if you purge your Windows path from $PATH. For example:
```
$ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
When running Python on WSL, you'll have correct paths, and permission to those paths. 

You will probably get more eyeballs on [stackoverflow](http://stackoverflow.com) or a Anaconda, Python, tensorflow, etc forum. This is not WSL actionable.
