### ISSUE TITLE
Gentoo GNU/Linux Portage: random permission denied issue

### ISSUE THREAD

**Issue by nE0sIghT** [microsoft/WSL#4639]
* Your Windows build number:  10.0.18362.418

* What you're doing and what's happening: 

Get any Gentoo current stage4 tarball here: http://distfiles.gentoo.org/releases/amd64/autobuilds/. I used systemd one.
Unpack tar from tar.xz to c:\
```
cmd
wsl --import gentoo c:\gentoo stage4-amd64-systemd-yyyymmdd.tar
wsl -d gentoo
```
Add/replace to/in ```/etc/portage/make.conf```:
```
COMMON_FLAGS="-march=native -O2 -pipe"
MAKEOPTS="-j2"
FEATURES="-ipc-sandbox -pid-sandbox -mount-sandbox -network-sandbox"
```

```
emerge-webrsync
emaint sync -a
emerge -ev @world
```

* What's wrong / what should be happening instead:
Error occured:
```
>>> Emerging (1 of 272) virtual/libintl-0-r2::gentoo
 * Fetching files in the background.
 * To view fetch progress, run in another terminal:
 * tail -f /var/log/emerge-fetch.log
>>> Unpacking source...
>>> Source unpacked in /tmp/portage/virtual/libintl-0-r2/work
>>> Preparing source in /tmp/portage/virtual/libintl-0-r2/work ...
>>> Source prepared.
Traceback (most recent call last):
  File "/var/tmp/portage/._portage_reinstall_.6o2a_lwh/lib/portage/locks.py", line 181, in _lockfile_iteration
    myfd = os.open(lockfilename, os.O_CREAT|os.O_RDWR, 0o660)
  File "/var/tmp/portage/._portage_reinstall_.6o2a_lwh/lib/portage/__init__.py", line 246, in __call__
    rval = self._func(*wrapped_args, **wrapped_kwargs)
PermissionError: [Errno 13] Permission denied: b'/tmp/portage/virtual/libintl-0-r2/.ipc_lock'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/tmp/portage/._portage_reinstall_.6o2a_lwh/bin/ebuild-ipc.py", line 277, in <module>
    sys.exit(ebuild_ipc_main(sys.argv[1:]))
  File "/var/tmp/portage/._portage_reinstall_.6o2a_lwh/bin/ebuild-ipc.py", line 273, in ebuild_ipc_main
    return ebuild_ipc.communicate(args)
  File "/var/tmp/portage/._portage_reinstall_.6o2a_lwh/bin/ebuild-ipc.py", line 130, in communicate
    lock_obj = portage.locks.lockfile(self.ipc_lock_file, unlinkfile=True)
  File "/var/tmp/portage/._portage_reinstall_.6o2a_lwh/lib/portage/locks.py", line 113, in lockfile
    unlinkfile=unlinkfile, waiting_msg=waiting_msg, flags=flags)
  File "/var/tmp/portage/._portage_reinstall_.6o2a_lwh/lib/portage/locks.py", line 187, in _lockfile_iteration
    _raise_exc(e)
  File "/var/tmp/portage/._portage_reinstall_.6o2a_lwh/lib/portage/util/install_mask.py", line 157, in _raise_exc           raise wrapper
portage.exception.PermissionDenied: [Errno 13] Permission denied: b'/tmp/portage/virtual/libintl-0-r2/.ipc_lock'         * The ebuild phase 'prepare' has exited unexpectedly. This type of
 * behavior is known to be triggered by things such as failed variable
 * assignments (bug #190128) or bad substitution errors (bug #200313).
 * Normally, before exiting, bash should have displayed an error message
 * above. If bash did not produce an error message above, it's possible
 * that the ebuild has called `exit` when it should have called `die`
 * instead. This behavior may also be triggered by a corrupt bash binary or
 * a hardware problem such as memory or cpu malfunction. If the problem is
 * not reproducible or it appears to occur randomly, then it is likely to
 * be triggered by a hardware problem. If you suspect a hardware problem
 * then you should try some basic hardware diagnostics such as memtest.
 * Please do not report this as a bug unless it is consistently
 * reproducible and you are sure that your bash binary and hardware are
 * functioning properly.

>>> Failed to emerge virtual/libintl-0-r2, Log file:
```

This error may occur for any package, but it always about ```PermissionError: [Errno 13] Permission denied:``` and ``` b'/tmp/portage/.../.ipc_lock'```
It may occur for any single emerges, but it always occurs for me trying ```emerge -ev @world```.

It also reported 2 years ago at reddit: https://www.reddit.com/r/bashonubuntuonwindows/comments/66mzgk/gentoo_userland_on_wsl/

Emerging some single packages works fine almost always.
I never hit such error on my Gentoo amd64 box for 10+ years.

* Strace of the failing command, if applicable:  Sadly, I cann't reproduce this under strace. Looks like some race condition specific to WSL.

* Also: I don't have any antivirus sofware except Windows Defender. ```c:\gentoo``` added to Defender exclusion list. I also tryed to disable real time protection without success.

**Comment by therealkenc** [comment]
> 10.0.18362.418
> [...]
> I used systemd one.
> [...]
> FEATURES="-ipc-sandbox -pid-sandbox -mount-sandbox -network-sandbox"

Scenario won't fly on WSL1 for a plethora of duplicate reasons. This could be filed under a different cover on WSL2 if someone was motivated to do so, however n.b. CLI repro steps. I almost did one but effort. Starts with something like (under powershell):
```
PS> cd $home
PS> curl.exe --output gentoo.tar.xz http://distfiles.gentoo.org/releases/amd64/autobuilds/current-stage4-amd64-minimal/stage4-amd64-minimal-20191030T214502Z.tar.xz
PS> curl --output xz.zip https://tukaani.org/xz/xz-5.2.4-windows.zip
PS> Expand-Archive xz.zip
PS> .\xz\bin_x86-64\xz.exe -d gentoo.tar.xz
PS> wsl.exe --import gentoo $home\gentoo $home\gentoo.tar
[... all the things]
```

Too swamped this afternoon to fill it out.
