### ISSUE TITLE
Ubuntu 20.04 WSL installation 0x8007023e error code

### ISSUE THREAD

**Issue by wd-omegacode** [microsoft/WSL#5323]
Windows:

OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.19608 N/A Build 19608
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Product ID:                00330-80836-74436-AA949
Original Install Date:     25.04.2020, 00:35:07
System Boot Time:          03.06.2020, 09:36:07
System Manufacturer:       ASUSTeK COMPUTER INC.
System Model:              VivoBook_ASUSLaptop X512FL_R564FL
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 12 GenuineIntel ~1600 Mhz
BIOS Version:              American Megatrends Inc. X512FL.204, 08.04.2019

-----

Ubunutu 20.04 startup error:

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007023e
Error: 0x8007023e
Press any key to continue...

**Comment by benhillis** [comment]
STATUS_VIRTUAL_DISK_LIMITATION                                 ntstatus.h
# The requested operation could not be completed due to a
# virtual disk system limitation.  Virtual hard disk files
# must be uncompressed and unencrypted and must not be
# sparse.

Hyper-V doesn't currently support VHD's that are in compressed or encrypted folders.

**Comment by wd-omegacode** [comment]
This is not a problem of STATUS_VIRTUAL_DISK_LIMITATION since:

Ubuntu (%USERPROFILE%\AppData\Local\Packages\CanonicalGroupLimited\LocalState) folder is niether compressed nor encrypted as per Windows Advanced properties.

**Comment by kmmizouri** [comment]
this is really too much to ignore that windows can't be a dev environment THANK YOU WINDOWS FOR MAKING IT NEVER BUGSFREE

**Comment by abtsalvado** [comment]
I am also facing this issue, no workaround. Any solutions?

**Comment by wd-omegacode** [comment]
Nothing so far :/

**Comment by eo1989** [comment]
Any news on this? For whatever reason microsoft store states I can launch the OS, and it gets "installed" onto my system (as in I can uninstall it via add/remove programs), yet when I attempt to launch the terminal popup states: 0x8007023e {Application Error}. My Canonical folder isn't compressed nor encrypted either. I think I've actually made things worse by trying to fix it. I ran into this issue before and decided to uninstall Ubuntu 20.04, re-installation led me to where i am now. Even an windows update downgrade didnt fix the issue (simply removed the 2 most recent windows updates) -_-

**Comment by kmmizouri** [comment]
> I am also facing this issue, no workaround. Any solutions?
> 
> ![image](https://user-images.githubusercontent.com/50082059/93030283-b8025f80-f619-11ea-8729-b0df8ba273c5.png)
> 
> At the same time this issue also affected my previous docker installations, and tried both with Docker Desktop 2.3.0.4 and Docker Desktop 2.0.0.3; but both returned different errors.
> 
> _Docker Desktop 2.3.0.4 error:_
> ```
> System.InvalidOperationException:
> Failed to deploy distro docker-desktop to C:\Users\Beatriz Salvado\AppData\Local\Docker\wsl\distro: exit code: -1
>  stdout: {Application Error}
> 
> The exception s (0x
>  stderr: 
>    at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
>    at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 94
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
> ```
> 
> _Docker Desktop 2.0.0.3 error:_
> ```
> Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
> at New-Switch, <No file>: line 121
> at <ScriptBlock>, <No file>: line 411
>    at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
>    at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
>    at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
>    at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
> ```

Go to windows Features disable every single Hyper-V / Virtualization feature (Hyper-V, platform Hyper-V, Containers...wsl...etc) then reboot. After rebooting re-activate your WSL only

**Comment by abtsalvado** [comment]
> > I am also facing this issue, no workaround. Any solutions?
> > ![image](https://user-images.githubusercontent.com/50082059/93030283-b8025f80-f619-11ea-8729-b0df8ba273c5.png)
> > At the same time this issue also affected my previous docker installations, and tried both with Docker Desktop 2.3.0.4 and Docker Desktop 2.0.0.3; but both returned different errors.
> > _Docker Desktop 2.3.0.4 error:_
> > ```
> > System.InvalidOperationException:
> > Failed to deploy distro docker-desktop to C:\Users\Beatriz Salvado\AppData\Local\Docker\wsl\distro: exit code: -1
> >  stdout: {Application Error}
> > 
> > The exception s (0x
> >  stderr: 
> >    at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
> >    at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
> > --- End of stack trace from previous location where exception was thrown ---
> >    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> >    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> >    at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
> > --- End of stack trace from previous location where exception was thrown ---
> >    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> >    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> >    at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 94
> > --- End of stack trace from previous location where exception was thrown ---
> >    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> >    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> >    at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
> > --- End of stack trace from previous location where exception was thrown ---
> >    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> >    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> >    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
> > --- End of stack trace from previous location where exception was thrown ---
> >    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> >    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
> > ```
> > 
> > 
> > _Docker Desktop 2.0.0.3 error:_
> > ```
> > Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
> > at New-Switch, <No file>: line 121
> > at <ScriptBlock>, <No file>: line 411
> >    at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
> >    at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
> >    at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
> >    at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
> > ```
> 
> Go to windows Features disable every single Hyper-V / Virtualization feature (Hyper-V, platform Hyper-V, Containers...wsl...etc) then reboot. After rebooting re-activate your WSL only and once again reboot. The error appears to be a conflict between the Hyper-V & wsl 2.
> If you don't want to use the WSL 2 you can just pass the fellowing command on you PowerShell as Administrator
> `wsl --set-default-version 1`
> And you will downgrade to wsl 1

Yes! This solved the problem. Having both Hyper-V and WSL features On will run into a conflict. Now I have only WSL feature on and wsl2 is up and running. Thank you very much @kmmizouri

**Comment by Myron-S** [comment]
Right. This is inconvenient. I need Hyper-V. Looks like I'll need to stick to WSL1 until Microsoft finds a solution for this bug.  Of Oracle can get VirtualBox to work alongside Hyper-V then I really hope that Microsoft can make WSL2 work alongside Hyper-V too.

**Comment by kmmizouri** [comment]
@Myron-S Hey, as I mentioned in my previous comment, it is not a workaround but it is the solution itself, the error is due to the conflict between the Hyper-V feature & WSL2 Feature. And there is probably (from System Architecture perspective) no solution for now for this (it costs too much money).

**Comment by Myron-S** [comment]
In trying to troubleshoot, now the Windows Sandbox is broken too.  :-(  Fault reported to the Feedback Hub.
At least VirtualBox is still working.

**Comment by kmmizouri** [comment]
Can you please show me the following commands output:
```
Wsl -v
```
```
 wsl --list --verbose
```
@Myron-S

**Comment by Myron-S** [comment]
```
Microsoft Windows [Version 10.0.19042.685]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\{Redacted}>wsl -v
Invalid command line option: -v
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d <Distro>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

Arguments for managing Windows Subsystem for Linux:

    --export <Distro> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

        Options:
            --version <Version>
                Specifies the version to use for the new distribution.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are currently
                being installed or uninstalled.

            --running
                List only distributions that are currently running.

            --quiet, -q
                Only show distribution names.

            --verbose, -v
                Show detailed information about all distributions.

    --set-default, -s <Distro>
        Sets the distribution as the default.

    --set-default-version <Version>
        Changes the default install version for new distributions.

    --set-version <Distro> <Version>
        Changes the version of the specified distribution.

    --shutdown
        Immediately terminates all running distributions and the WSL 2 lightweight utility virtual machine.

    --terminate, -t <Distro>
        Terminates the specified distribution.

    --unregister <Distro>
        Unregisters the distribution.

    --help
        Display usage information.

C:\Users\{Redacted}>wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Stopped         1

C:\Users\{Redacted}>
```

**Comment by Myron-S** [comment]
If I try and change the version to 2, and I have updated the kernel.  Stripped the WSL and VM features out and put them back in.

Right now ....

```
C:\Users\{Redacted}>wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Stopped         1

C:\Users\{Redacted}>wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
{Application Error}
The exception s (0x
C:\Users\mts>wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Stopped         1

C:\Users\{Redacted}>
```

@kmmizouri

**Comment by Myron-S** [comment]
It's not better.  In my attempt at removing and replacing the features, making sure updates are reapplied at each step now the Windows Sandbox feature is broken.  See: https://aka.ms/AAaktan

Even broke Hyper-V's network virtual switch broke.  See: https://aka.ms/AAaktaq

I do have a PC here, lower spec, updates match the main PC where Hyper-V, the sandbox and WSL are working.

Below is from the other laptop.

```
Microsoft Windows [Version 10.0.19042.685]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\{redacted}>wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Stopped         2
  Legacy    Stopped         1

C:\Users\{redacted}>wsl
Welcome to Ubuntu 20.04.1 LTS (GNU/Linux 4.19.128-microsoft-standard x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Thu Dec 10 15:13:40 GMT 2020

  System load:  0.37               Processes:             8
  Usage of /:   0.5% of 250.98GB   Users logged in:       0
  Memory usage: 1%                 IPv4 address for eth0: 172.22.249.72
  Swap usage:   0%

0 updates can be installed immediately.
0 of these updates are security updates.


The list of available updates is more than a week old.
To check for new updates run: sudo apt update


This message is shown once a day. To disable it please create the
/home/myron/.hushlogin file.
myron@Narada:/mnt/c/Users/Myron$ logout

C:\Users\{redacted}>wsl -v
Invalid command line option: -v
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d <Distro>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

Arguments for managing Windows Subsystem for Linux:

    --export <Distro> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

        Options:
            --version <Version>
                Specifies the version to use for the new distribution.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are currently
                being installed or uninstalled.

            --running
                List only distributions that are currently running.

            --quiet, -q
                Only show distribution names.

            --verbose, -v
                Show detailed information about all distributions.

    --set-default, -s <Distro>
        Sets the distribution as the default.

    --set-default-version <Version>
        Changes the default install version for new distributions.

    --set-version <Distro> <Version>
        Changes the version of the specified distribution.

    --shutdown
        Immediately terminates all running distributions and the WSL 2 lightweight utility virtual machine.

    --terminate, -t <Distro>
        Terminates the specified distribution.

    --unregister <Distro>
        Unregisters the distribution.

    --help
        Display usage information.

C:\Users\{redacted}>
```

What gives?  Why one broken and the other not?  Anyone know?

@kmmizouri

**Comment by kmmizouri** [comment]
@Myron-S can you please show me you windows features list

**Comment by Myron-S** [comment]
Sure.

```
> Get-WindowsOptionalFeature -Online | ? State -eq Enabled


FeatureName : Printing-PrintToPDFServices-Features
State       : Enabled

FeatureName : Printing-XPSServices-Features
State       : Enabled

FeatureName : SearchEngine-Client-Package
State       : Enabled

FeatureName : MSRDC-Infrastructure
State       : Enabled

FeatureName : TelnetClient
State       : Enabled

FeatureName : TFTP
State       : Enabled

FeatureName : TIFFIFilter
State       : Enabled

FeatureName : LegacyComponents
State       : Enabled

FeatureName : DirectPlay
State       : Enabled

FeatureName : Printing-Foundation-Features
State       : Enabled

FeatureName : Printing-Foundation-InternetPrinting-Client
State       : Enabled

FeatureName : SimpleTCP
State       : Enabled

FeatureName : NetFx4-AdvSrvs
State       : Enabled

FeatureName : WCF-Services45
State       : Enabled

FeatureName : WCF-TCP-PortSharing45
State       : Enabled

FeatureName : NetFx3
State       : Enabled

FeatureName : MediaPlayback
State       : Enabled

FeatureName : WindowsMediaPlayer
State       : Enabled

FeatureName : SmbDirect
State       : Enabled

FeatureName : Internet-Explorer-Optional-amd64
State       : Enabled

FeatureName : SMB1Protocol
State       : Enabled

FeatureName : SMB1Protocol-Client
State       : Enabled

FeatureName : MicrosoftWindowsPowerShellV2Root
State       : Enabled

FeatureName : MicrosoftWindowsPowerShellV2
State       : Enabled

FeatureName : ServicesForNFS-ClientOnly
State       : Enabled

FeatureName : ClientForNFS-Infrastructure
State       : Enabled

FeatureName : NFS-Administration
State       : Enabled

FeatureName : Microsoft-Windows-Subsystem-Linux
State       : Enabled

FeatureName : HypervisorPlatform
State       : Enabled

FeatureName : VirtualMachinePlatform
State       : Enabled

FeatureName : Containers-DisposableClientVM
State       : Enabled

FeatureName : Microsoft-Hyper-V-All
State       : Enabled

FeatureName : Microsoft-Hyper-V
State       : Enabled

FeatureName : Microsoft-Hyper-V-Tools-All
State       : Enabled

FeatureName : Microsoft-Hyper-V-Management-PowerShell
State       : Enabled

FeatureName : Microsoft-Hyper-V-Hypervisor
State       : Enabled

FeatureName : Microsoft-Hyper-V-Services
State       : Enabled

FeatureName : Microsoft-Hyper-V-Management-Clients
State       : Enabled

FeatureName : Containers
State       : Enabled
```

@kmmizouri

**Comment by kmmizouri** [comment]
> 
> Go to windows Features disable every single Hyper-V / Virtualization feature (Hyper-V, platform Hyper-V, Containers...wsl...etc) then reboot. After rebooting re-activate your WSL only and once again reboot. The error appears to be a conflict between the Hyper-V & wsl 2.
> If you don't want to use the WSL 2 you can just pass the fellowing command on you PowerShell as Administrator
> `wsl --set-default-version 1`
> And you will downgrade to wsl 1

You should disable the Hyper-V..containers...etc and do as I mentioned here. It is normal that it crashes because as I early in the comments it's a functional conflict between the Hyper-V and the Wsl2.
@Myron-S

**Comment by Myron-S** [comment]
That is what I did, but the problem did not go away without the Hyper-V feature installed.

**Comment by kmmizouri** [comment]
No you didn't @Myron-S 😅

**Comment by kmmizouri** [comment]
@Myron-S contact me on my E-mail:
Kmmizouri@gmail.com

**Comment by Myron-S** [comment]
I'll e-mail later, but just for now I'll take some time to compare the two Windows 10 Pro installations.  Features installed are identical.  One machine works.  Virtual Box, Hyper-V and WSL2.  I've successfully fired up VB, HV and Ubuntu.  Unfortunately that laptop is the slower less capable laptop.

I'll put-up with WSL1 for now on the more capable machine as I do require Hyper-V and VirtualBox to work together as well as a Linux Distro.

**Comment by Myron-S** [comment]
Ah drat. I've accidentally fixed the issue without removing any features, but unfortunately I've messed up recording all my investigation notes as I was trying to find out where the actual fault(s) lie. I'm going to leave this issue now. I don't want to mess up my production laptop. I don't dispute that your method works.  I just some how fix the issue another way.  I just don't know what step(s) make it work.

I guess Microsoft can work on this bug if they so desire.

**Comment by andrewpalumbo** [comment]
I could use an answer here

**Comment by kmmizouri** [comment]
> I could use an answer here
> ```
> PS C:\windows\system32> Get-WindowsOptionalFeature -Online | ? State -eq Enabled                                        
> 
> FeatureName : Printing-PrintToPDFServices-Features
> State       : Enabled
> 
> FeatureName : Printing-XPSServices-Features
> State       : Enabled
> 
> FeatureName : TelnetClient
> State       : Enabled
> 
> FeatureName : TFTP
> State       : Enabled
> 
> FeatureName : NetFx3
> State       : Enabled
> 
> FeatureName : WCF-Services45
> State       : Enabled
> 
> FeatureName : WCF-TCP-PortSharing45
> State       : Enabled
> 
> FeatureName : MediaPlayback
> State       : Enabled
> 
> FeatureName : WindowsMediaPlayer
> State       : Enabled
> 
> FeatureName : SmbDirect
> State       : Enabled
> 
> FeatureName : Internet-Explorer-Optional-amd64
> State       : Enabled
> 
> FeatureName : MicrosoftWindowsPowerShellV2Root
> State       : Enabled
> 
> FeatureName : MicrosoftWindowsPowerShellV2
> State       : Enabled
> 
> FeatureName : SearchEngine-Client-Package
> State       : Enabled
> 
> FeatureName : MSRDC-Infrastructure
> State       : Enabled
> 
> FeatureName : WorkFolders-Client
> State       : Enabled
> 
> FeatureName : Printing-Foundation-Features
> State       : Enabled
> 
> FeatureName : FaxServicesClientPackage
> State       : Enabled
> 
> FeatureName : Printing-Foundation-InternetPrinting-Client
> State       : Enabled
> 
> FeatureName : Microsoft-Windows-Subsystem-Linux
> State       : Enabled
> 
> FeatureName : VirtualMachinePlatform
> State       : Enabled
> 
> FeatureName : Microsoft-Windows-NetFx3-OC-Package
> State       : Enabled
> 
> FeatureName : Microsoft-Windows-NetFx4-US-OC-Package
> State       : Enabled
> 
> FeatureName : Microsoft-Windows-Client-EmbeddedExp-Package
> State       : Enabled
> 
> FeatureName : Microsoft-Windows-NetFx3-WCF-OC-Package
> State       : Enabled
> 
> FeatureName : Microsoft-Windows-NetFx4-WCF-US-OC-Package
> State       : Enabled
> 
> FeatureName : Windows-Defender-ApplicationGuard
> State       : Enabled
> 
> FeatureName : NetFx4-AdvSrvs
> State       : Enabled
> 
> FeatureName : NetFx4Extended-ASPNET45
> State       : Enabled
> 
> FeatureName : Containers
> State       : Enabled
> 
> 
> 
> PS C:\windows\system32> wsl --set-version Ubuntu 2
> Conversion in progress, this may take a few minutes...
> For information on key differences with WSL 2 please visit https://aka.ms/wsl2
> {Application Error}
> The exception s (0x
> PS C:\windows\system32>     
> ```
Try this one

https://github.com/microsoft/WSL/issues/5323#issuecomment-742601073

**Comment by mschaeffter** [comment]
Thanks. This made  my day - just set wsl v1 as the default :-)
