### ISSUE TITLE
Secure communication between processes cannot be established when both running on WSL and use dotnet dev certs

### ISSUE THREAD

**Issue by mjarosie** [microsoft/WSL#5500]
# Environment

```none
Windows build number: `10.0.19041.329`
Your Distribution version: `Ubuntu 20.04`
Whether the issue is on WSL 2 and/or WSL 1: `WSL 2`
```

# Steps to reproduce

Clone this repo: https://github.com/mjarosie/wsl-dotnet-cert-issues. The repo contains 2 simple applications:
- Api (created by running `dotnet new web -n Api` and simplifying `launchSettings.json`). Responds with "Hello world" at `https://localhost:6001/`.
- Client (created by running `dotnet new console -n Client` and adding code which calls the Api)

Following steps mentioned in https://docs.microsoft.com/en-gb/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#trust-https-certificate-from-windows-subsystem-for-linux:
- in Windows `cmd` export "Windows version" of dotnet-generated dev certificates:
```
dotnet dev-certs https -ep %USERPROFILE%\.aspnet\https\aspnetapp.pfx -p <cryptic-password>
```

- in WSL cd to the root directory of the cloned repository, set up the Api app to use exported certificate and run the app itself:
```
ASPNETCORE_Kestrel__Certificates__Default__Password="<cryptic-password>" 
ASPNETCORE_Kestrel__Certificates__Default__Path=/mnt/c/Users/user-name/.aspnet/https/aspnetapp.pfx # Change "user-name" as required
# First, trust the Windows certificate:
# It will ask you for a certificate password mentioned above and then put a .crt file from where it can be imported by the system using the next command
sudo openssl pkcs12 -in $ASPNETCORE_Kestrel__Certificates__Default__Path -clcerts -nokeys -out /usr/local/share/ca-certificates/aspnetapp.crt 
sudo update-ca-certificates

cd src/Api
dotnet run # Will start serving an API on https://localhost:6001/
```
This will make the application hosting the API to use the Windows-generated self-signed dotnet dev certificates.

-  open another instance of WSL, cd to the root directory of the cloned repository and run the Client app which will try to call the Api:
```
cd src/Client
dotnet run
```

#  Expected behavior

I'd expect the client app to trust the certificate as it was imported with `sudo update-ca-certificates` command. As a result I'd expect it to securely connect to the Api endpoint. Client is able to connect to the Api when both apps run on Windows (Powershell) with no issues.

# Actual behavior

I'm getting a SSL connection exception:

```
Unhandled exception. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Client.Program.Main(String[] args) in /home/mjarosie/source/IdentityServerSandbox/wsl-dotnet-cert-issues/src/Client/Program.cs:line 12
   at Client.Program.<Main>(String[] args)
```

**Comment by Joe-Pena** [comment]
Any update or solution to this issue? I'm running into the same problem, also running WSL2.
