### ISSUE TITLE
ImportError: libd3d12.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zyc-ai** [microsoft/WSL#5630]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.20170.0 Microsoft Windows NT 10.0.20170.0

Release:        20.04

Linux version 4.19.121-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Fri Jun 19 21:06:10 UTC 2020

# Steps to reproduce

```shell
 zyc@Zhiyuan-SurfaceBook  ~  python                                                           125 ↵  67  16:31:10
Python 3.7.7 (default, May  7 2020, 21:25:33)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
```

#  Expected behavior

```python

```

# Actual behavior

```python
Traceback (most recent call last):
  File "/home/zyc/.local/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/zyc/.local/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/zyc/.local/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/conda/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libd3d12.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zyc/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 110, in <module>
    from tensorflow_core import *
  File "/home/zyc/.local/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/zyc/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 58, in __getattr__
    module = self._load()
  File "/home/zyc/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 52, in _load
    module = _importlib.import_module(self.__name__)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zyc/.local/lib/python3.7/site-packages/tensorflow_core/python/__init__.py", line 55, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/zyc/.local/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/zyc/.local/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/zyc/.local/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/zyc/.local/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/conda/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libd3d12.so: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by therealkenc** [comment]
What is the contents of your `ls /usr/lib/wsl/lib`. Assuming it is empty, check `dmesg` and see if there are any mount related errors. The `libd3d12.so` shared library should be there and (in principle) automagically picked by the loader, but in your case it is not.

**Comment by zyc-ai** [comment]
> What is the contents of your `ls /usr/lib/wsl/lib`. Assuming it is empty, check `dmesg` and see if there are any mount related errors. The `libd3d12.so` shared library should be there and (in principle) automagically picked by the loader, but in your case it is not.

There were four files including `libd3d12.so`

**Comment by SionHu** [comment]
I'm experiencing the exact same issue when I tried to install tensorflow on WSL2 with DirectML.

**Comment by pierrechopin** [comment]
Experiencing same issue, except there is no such directory as /usr/lib/wsl

**Comment by sunayana** [comment]
same here I am experiencing the same issue as well and I do not have `/usr/lib/wsl`

**Comment by shokoluv** [comment]
Had the same issues, resolved after enabling VM options on BIOS and re-running 
` wsl --set-version <DISTRO> 2  | wsl --update` 
to validate it works, you must be able to see /dev/dxg
