### ISSUE TITLE
[WSL1] Operation not permitted on socket when application performs setting IP ToS

### ISSUE THREAD

**Issue by DjArt** [microsoft/WSL#6222]
# Environment

```
Windows build number: Windows Server 2019 Standard Insider Preview 20251
Your Distribution version: Ubuntu 18.10
Whether the issue is on WSL 2 and/or WSL 1: WSL 1
```

# Steps to reproduce

How I ran into this problem: I tried to run [PaperMC](https://papermc.io/) Minecraft Server with [Geyser](https://github.com/GeyserMC/Geyser) and [Floodgate](https://github.com/GeyserMC/Floodgate) plugins inside WSL. Here is stacktrace of error:

```
[11:58:31 WARN]: [org.geysermc.platform.spigot.shaded.netty.channel.ChannelInitializer] Failed to initialize a channel. Closing: [id: 0x67437701]
org.geysermc.platform.spigot.shaded.netty.channel.ChannelException: java.net.SocketException: Operation not permitted
        at org.geysermc.platform.spigot.shaded.netty.channel.socket.DefaultSocketChannelConfig.setTrafficClass(DefaultSocketChannelConfig.java:267) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.socket.DefaultSocketChannelConfig.setOption(DefaultSocketChannelConfig.java:118) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelConfig.setOption(NioSocketChannel.java:491) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpClientSession$1.initChannel(TcpClientSession.java:63) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:964) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:613) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1475) ~[?:?]
>       at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1127) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:654) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:503) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:416) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:475) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?>
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.net.SocketException: Operation not permitted
        at sun.nio.ch.Net.setIntOption0(Native Method) ~[?:?]
        at sun.nio.ch.Net.setSocketOption(Net.java:450) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:254) ~[?:?]
        at sun.nio.ch.SocketAdaptor.setIntOption(SocketAdaptor.java:243) ~[?:?]
        at sun.nio.ch.SocketAdaptor.setTrafficClass(SocketAdaptor.java:360) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.socket.DefaultSocketChannelConfig.setTrafficClass(DefaultSocketChannelConfig.java:265) ~[?:?]
        ... 21 more
```
Connection performs inside loopback, if it matters (127.0.0.1:XXXX -> 127.0.0.1:YYYY).
Of course, it's not easiest way to reproduce this bug. But I think the class of the problem is clear.

#  Expected behavior

Connection must work fine.

# Actual behavior

Connection abandoned.

# Some additional info

Okay, some questions may appear.
Why WSL1? Because my platform doesn't support Hyper-V.
Why JVM runs inside WSL instead pure Windows? There some specific software (aka plugins), that runs only on Linux.

**Comment by therealkenc** [comment]
> `sun.nio.ch.SocketAdaptor.setTrafficClass(SocketAdaptor.java:360)`

Almost certainly #1869 (or something close to it). There is no repro here, but if you are academically motivated you can post a link to a [gist](https://gist.github.com/) of a threaded [`strace(1)`](https://man7.org/linux/man-pages/man1/strace.1.html) output of the failing command to confirm.
