### ISSUE TITLE
start wsl error: OSError

### ISSUE THREAD

**Issue by RitaRuan** [microsoft/WSL#6382]
I use "wsl"  to start wsl2 on PowerShell
there's error:
Original exception was:
Traceback (most recent call last):
  File "/usr/bin/landscape-sysinfo", line 11, in <module>
    from twisted.internet import reactor
  File "/usr/lib/python3/dist-packages/twisted/internet/reactor.py", line 38, in <module>
  File "/usr/lib/python3/dist-packages/twisted/internet/default.py", line 56, in <module>
  File "/usr/lib/python3/dist-packages/twisted/internet/default.py", line 44, in _getInstallFunction
  File "/usr/lib/python3/dist-packages/twisted/internet/epollreactor.py", line 24, in <module>
  File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 18, in <module>
  File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 31, in <module>
  File "/usr/lib/python3/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
  File "/usr/lib/python3/dist-packages/twisted/protocols/tls.py", line 63, in <module>
  File "/usr/lib/python3/dist-packages/twisted/internet/_sslverify.py", line 158, in <module>
  File "/usr/lib/python3/dist-packages/twisted/internet/_sslverify.py", line 141, in _selectVerifyImplementation
  File "/usr/lib/python3/dist-packages/service_identity/__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1342, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1314, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1443, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1483, in _fill_cache
OSError: [Errno 5] Input/output error: '/usr/lib/python3/dist-packages/service_identity'
run-parts: /etc/update-motd.d/50-landscape-sysinfo exited with return code 1

**Comment by OneBlue** [comment]
Looks like there is another 'wsl' binary or alias that comes before wsl.exe.
You can figure out what it is by running `Get-Command wsl`.


Closing as this is not a WSL issue.

**Comment by Dweeberly** [comment]
Well that's super not helpful.  If I do a Get-Command wsl it returns C:\WINDOWS\system32\wsl.exe, the traceback (I have something different but similar, contains all unix paths (& python scripts).  End result is WSL is bricked but it's not a problem because it comes "before" wsl.exe.  So, I'm assume when I run wsl.exe in PS, unix magically starts, runs a bunch of python, _then_ the actual Windows exe called from the command line is run.  Wow, can't even imagine how that works.  At least WSL being bricked with no way to debug isn't a WSL issue.  Next search result please ...

**Comment by RitaRuan** [comment]
您好，我已收到您的邮件，我会尽快回复，谢谢！

**Comment by Zarar-Azwar** [comment]
This is due to **a version mismatch between pyOpenSSL and cryptography libraries.**
Please run following command
`sudo python3 -m pip install --upgrade pyOpenSSL cryptography`
or 
`sudo pip install --upgrade pyOpenSSL cryptography`

**Comment by RitaRuan** [comment]
您好，我已收到您的邮件，我会尽快回复，谢谢！
