### ISSUE TITLE
Ethernet Adapter vEthernet (WSL) missing/can not be created (-SwitchType Private)

### ISSUE THREAD

**Issue by waldyd** [microsoft/WSL#6775]
# Environment

```none
Windows build number: [Version 10.0.18363.1440]
Whether the issue is on WSL 2 and/or WSL 1: [WSL2]
```

# Steps to reproduce

1. Ethernet Adapter vEthernet (WSL) missing/not found using ipconfig
2. Try to recreate it via powershell comands:

```powershell
New-VMSwitch "WSL" -NetAdapterName "Ethernet"
set-vmswitch -name WSL -NetAdapterName Ethernet -AllowManagementOS 1
set-vmswitch 'WSL' -SwitchType Private
```
3. Hyper-V Switch created without Ethernet Adapter vEthernet (WSL)

![image](https://user-images.githubusercontent.com/1531796/113953509-9c40ef80-97dd-11eb-9a9e-d1ba674ff2bf.png)

```
NIC C4*-*-*-*-*B4 successfully disconnected from port .
The server could not bind to the transport \Device\NetBT_Tcpip_{D7*-*-*-*-*E8} because another computer on the network has the same name.  The server could not start.
The server could not bind to the transport \Device\NetBT_Tcpip_{79*-*-*-*-*9F} because another computer on the network has the same name.  The server could not start.
The server could not bind to the transport \Device\NetBT_Tcpip_{2A*-*-*-*-*05} because another computer on the network has the same name.  The server could not start.
The operation 'Delete' succeeded on nic C4*-*-*-*-*B4 (Friendly Name: WSL).
```

**WSL logs**: 

[wsl-etl.zip](https://github.com/microsoft/WSL/files/6306163/wsl-etl.zip)

#  Expected behavior

1. Ethernet Adapter vEthernet (WSL) created
2. WSL distro Conversion success

# Actual behavior

1. Ethernet Adapter vEthernet (WSL) not created
2. WSL distro Conversion failed
3. Already tried this: https://docs.microsoft.com/en-us/troubleshoot/windows-client/virtualization/cannot-create-hyper-v-virtual-switch

```powershell
 wsl  --set-version kali-linux 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The network was not found.
```

**Comment by craigloewen-msft** [comment]
Hello, could you please attach logs for when you're trying to convert WSL? 

You downloaded the html version of the log file, please save [this file](https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/wsl.wprp) and run logs using it and link them here.

Thank you!

**Comment by waldyd** [comment]
Hi,

This is log file:

[wsl-etl.zip](https://github.com/microsoft/WSL/files/6306164/wsl-etl.zip)

Thank you!

**Comment by OneBlue** [comment]
@waldyd : WSL internally identifies networks by GUID.

The network you manually created doesn't have the right GUID, but has the same name, WSL.
This causes WSL to think that the network already exists, but fails when the service actually tries to open it because its opened by GUID and not by name.

The 'WSL' network is created when the WSL service start, so the simplest way to fix this would be:

PS C:\>  Remove-VmSwitch "WSL"
PS C:\> Restart-Service lxssmanager 


Let us know if that worked for you.

**Comment by waldyd** [comment]
@OneBlue : Restarting the  lxssmanager service did not work for creating the Ethernet Adapter vEthernet (WSL) neither the WSL Virtual Switch:
![image](https://user-images.githubusercontent.com/1531796/114627864-959df680-9c7b-11eb-8ccd-ac55f474052f.png)

**Comment by OneBlue** [comment]
@waldyd: Sorry I realized that my previous reply wasn't clear.

The network is created on the first WSL startup, once per service start.

Can you run wsl once and check if that creates the network ?

**Comment by waldyd** [comment]
@OneBlue : NP. All my WSL distros are version 1, except the Docker related ones that are WSL 2:

```powershell
wsl --list --verbose
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         1
  kali-linux      Running         1
```

Once I start Docker Desktop, the following error is prompted:

```powershell
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\NW539AL\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: The network was not found.


 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<SwitchDaemonAsync>d__28.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 333
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Services.DesktopService.<SwitchDaemonAsync>d__4.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\Services\DesktopService.cs:line 36

```

In conclusion, virtual network interface can be created.

**Comment by OneBlue** [comment]
Ok this is interesting.

Can you take another trace after having the 'WSL' network deleted and lxssmanager restarted ? 
I'd like to see what happens when WSL tries to create it.

So can you please install a dummy WSL2 distro, set it as default, then run [these instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues) and share both the output and wsl.etl ?

**Comment by waldyd** [comment]
A crash report has been uploaded with diagnostic id:

582E1E1D-A6C2-40DA-A487-C572E949D458/20211029235328
