### ISSUE TITLE
Ansible / python UnicodeEncodeError

### ISSUE THREAD

**Issue by pgrm** [Microsoft/WSL#684]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description

running `ansible-playbook test.yaml` which works on native linux ans os x
- Expected results

it should also work on bash on windows
- Actual results (with terminal output if applicable)

```
peter@computer:~/SUB_DIR$ ansible-playbook test.yaml

PLAY [MY_SERVER] ****************************************************************

GATHERING FACTS ***************************************************************
ok: [server.MY_SERVER.com]

TASK: [test] ***********************************************************
fatal: [server.MY_SERVER.com] => Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 532, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 629, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 810, in _executor_internal_inner
    complex_args = template.template(self.basedir, complex_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/lib/python2.7/dist-packages/ansible/utils/template.py", line 349, in template
    d[k] = template(basedir, v, vars, lookup_fatal, depth, expand_lists, fail_on_undefined=fail_on_undefined)
  File "/usr/lib/python2.7/dist-packages/ansible/utils/template.py", line 345, in template
    return [template(basedir, v, vars, lookup_fatal, depth, expand_lists, fail_on_undefined=fail_on_undefined) for v in varname]
  File "/usr/lib/python2.7/dist-packages/ansible/utils/template.py", line 321, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/usr/lib/python2.7/dist-packages/ansible/utils/template.py", line 543, in template_from_string
    data = data.decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 11: ordinal not in range(128)


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/peter/test.yaml.retry

server.MY_SERVER.com         : ok=1    changed=0    unreachable=1    failed=0
```
- Your Windows build number

14393.3
- Steps / commands required to reproduce the error

`ansible-playbook ...` - I checked the playbook and didn't find any non ansi characters, maybe they come from the server response, but the very same playbook works fine with default configurations on linux and os x
- Strace of the failing command

it's 7000 lines, not sure which part is significant, you can find it here: https://gist.github.com/pgrm/8932b46d7c064de8eadc855291a512f2
- Required packages and commands to install

ansible (python2 is already installed by default)

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Going through the strace, there aren't any obvious syscall failures around the time that the task fails.  We'll have to setup a local repro to understand the difference on WSL.

**Comment by tara-raj** [comment]
The WSL world is different now and a lot nicer :). Closing out this issue. Please reopen if you hit this again.
