### ISSUE TITLE
java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.

### ISSUE THREAD

**Issue by sgireddy** [microsoft/WSL#7006]
### Windows Build Number

10.0.21390 Build 21390

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Other Software

IntelliJ Idea installed as 
sudo snap install intellij-idea-ultimate --classic

### Repro Steps

install intelliJ as snap
cd snap/intellij-idea-ultimate/current/bin
./idea.sh

### Expected Behavior

IDE opens

### Actual Behavior

$ ./idea.sh
May 30, 2021 9:33:38 PM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background /home/sg0218/.java/.userPrefs/prefs.xml

Start Failed
Failed to initialize graphics environment

java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:233)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:588)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:583)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
        at java.desktop/java.awt.Toolkit.getEventQueue(Toolkit.java:1499)
        at java.desktop/java.awt.EventQueue.invokeLater(EventQueue.java:1318)
        at com.intellij.idea.StartupUtil.lambda$scheduleInitUi$9(StartupUtil.java:347)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
        at java.base/java.lang.Thread.run(Thread.java:834)

-----
Your JRE: 11.0.10+9-b1341.41 amd64 (JetBrains s.r.o.)
/snap/intellij-idea-ultimate/295/jbr

**Comment by onomatopellan** [comment]
This issue should be posted in https://github.com/microsoft/wslg/issues

>5.4.72

Kernel is too old. Open an elevated cmd and run ` wsl.exe --update`

>install intelliJ as snap

Since you are using snap that means you are running systemd which erases /tmp folder and WSLg initialization.  You will need to run `ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix` before using an X11 application.

**Comment by sgireddy** [comment]
Looks like Kernel was auto-updated last night. issue resolved after the following steps:
1.  reset ubuntu (resetting ubuntu is not removing application shortcuts in windows)
2. Install IDE using jetbrains toolbox as described here https://www.jetbrains.com/help/idea/installation-guide.html#standalone

@onomatopellan thanks for the update, I will log future bugs at wslg

**Comment by mdashiff96** [comment]
wsl --update worked for me
