### ISSUE TITLE
Vagrant plugin installing error "parent directory is world writable but not sticky"

### ISSUE THREAD

**Issue by StalkAlex** [Microsoft/WSL#727]
Installed Vagrant 1.8.5, then tried to install some plugins, no matter what plugin was going to be installed I got this error in console.

```
vagrant plugin install vagrant-dotenv
Installing the 'vagrant-dotenv' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/tmpdir.rb:92:in `ensure in mktmpdir': parent directory is world writable but not sticky (ArgumentError)
        from /opt/vagrant/embedded/lib/ruby/2.2.0/tmpdir.rb:94:in `mktmpdir'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `each'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `block in index'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:206:in `index'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
        from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/bundler.rb:230:in `block in internal_install'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/bundler.rb:294:in `block in with_isolated_gem'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/user_interaction.rb:45:in `use_ui'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/bundler.rb:293:in `with_isolated_gem'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/bundler.rb:229:in `internal_install'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/bundler.rb:102:in `install'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/manager.rb:72:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/plugin/action/install_gem.rb:37:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/plugin/command/base.rb:14:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/plugin/command/install.rb:32:in `block in execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/plugin/command/install.rb:31:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/plugin/command/install.rb:31:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/plugin/command/root.rb:56:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:302:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/bin/vagrant:174:in `<main>'
```

**Comment by MikeTheCanuck** [comment]
Hi @StalkAlex - I don't have a solution, but in researching a vaguely-related issue I think I've stumbled on a workaround that might help you at least move forward temporarily:
http://stackoverflow.com/questions/37211007/installing-rails-on-ubuntu-bash-windows-10 (see Update: 2016-06-03).

(Any chance you could lend a hand to help figure out how to get vagrant to install on my Bash/Ubuntu/Win10?  I'm getting hung up on linux-headers, and I infer you found a way around it - or took a different install path.)

**Comment by StalkAlex** [comment]
Why  @MikeTheCanuck, thanks for information, I thought I've managed to solve the problem with sticky bit, I just commented those lines that throwed this exception in tmpdir.rb, all plugins were being installed successfully then,  but vagrant up/ssh throwed a new exception 'dotenv function is not defined'  like plugins haven't been installed or enabled.

**Comment by StalkAlex** [comment]
About way to install vagrant, I just used dpkg and deb package from vagrantup.com.

**Comment by MikeTheCanuck** [comment]
Fascinating...I should be asking more questions to dispel my assumptions.

What virtualization stack are you managing with vagrant (eg. VirtualBox or something else)? Is it local or remote?

For me, I installed VirtualBox and vagrant using apt-get, and found myself battling a non-existent /dev/vboxdrv.

**Comment by StalkAlex** [comment]
I'm just using vagrant, no virtual box, no docker locally. I think it's impossible to run those applications due to user mode only, no kernel stuff like working with sockets and physical devices. In my case it's ok because we're using vSphere, so I need vagrant and vsphere plugin only to communicte to our VMs.

**Comment by mfisher87** [comment]
I was able to get around this by:

```chmod -R +t ~/.bundle/cache```

After that I realized I also need `make` and `gcc` but that was just an `apt-get install` away.

**Comment by koppieesq** [comment]
I had to run a slightly different command in order to get this to work:
`chmod -R +t ~/.bundle`
I'm also trying to run Ubuntu on Windows 10.  Thanks mfisher87 for pointing us in the right direction!
