### ISSUE TITLE
Could not initialise Java graphics enviroment in WSL2

### ISSUE THREAD

**Issue by han94ros** [microsoft/WSL#7295]
### Windows Build Number

Microsoft Windows [10.0.19043 build 19043]

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu 20.04

### Repro Steps

I am trying to install the Xilinix Vivado Linux web extracter on the WSL2 using the Ubuntu distro. I understand that I need to connect the container to the X server and to do this I need to install a package which makes use of xhost as stated in this link (https://github.com/rycus86/docker-intellij-idea/issues/11), I have installed 

sudo apt-get update
sudo apt-get install x11-xserver-utils

then using xhost +local: to allow for all local connections. But this does not return and therefore I can exit this function.

Then set the display:
export DISPLAY=172.31.112.1:0
This uses the Windows PC IP address

and when executing the bin file, I get the following error:

ERROR: Installer could not be started. Could not initialize class java.awt.GraphicsEnvironment$LocalGE

### Expected Behavior

To be able to uncompress the Xilinix installer properly

### Actual Behavior

Results in the following error:
ERROR: Installer could not be started. Could not initialize class java.awt.GraphicsEnvironment$LocalGE
java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/java.awt.Window.initGC(Window.java:487)
        at java.desktop/java.awt.Window.init(Window.java:507)
        at java.desktop/java.awt.Window.<init>(Window.java:549)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/java.awt.Frame.<init>(Frame.java:388)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at h.b.<init>(Unknown Source)
        at com.xilinx.installer.gui.F.<init>(Unknown Source)
        at com.xilinx.installer.gui.InstallerGUI.<init>(Unknown Source)
        at com.xilinx.installer.gui.InstallerGUI.<clinit>(Unknown Source)
        at com.xilinx.installer.api.InstallerLauncher.main(Unknown Source)

**Comment by OneBlue** [comment]
Hello,

For X11 apps the recommendation is to use [wslG](https://github.com/microsoft/wslg) since we don't support third party x server.

**Comment by han94ros** [comment]
Thank you for your response.
