### ISSUE TITLE
Kali Linux on windows 10 WSL is not detecting WI-FI. cant able practice wifi hacking. 

### ISSUE THREAD

**Issue by firewall1337** [microsoft/WSL#7400]
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1165]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.4.72

### Distro Version

Release:        2021.2

### Repro Steps

1) First i run this command  "iwconfig" it will show : 
└─# iwconfig
sit0      no wireless extensions.

bond0     no wireless extensions.

lo        no wireless extensions.

eth0      no wireless extensions.

dummy0    no wireless extensions.

2. when I run 
└─# wifite 
   .               .    
 .´  ·  .     .  ·  `.  wifite2 2.5.8
 :  :  :  (¯)  :  :  :  a wireless auditor by derv82
 `.  ·  ` /¯\ ´  ·  .´  maintained by kimocoder
   `     /¯¯¯\     ´    https://github.com/kimocoder/wifite2

 [!] Warning: Recommended app pyrit was not found. install @ https://github.com/JPaulMora/Pyrit/wiki
 [!] Warning: Recommended app hcxdumptool was not found. install @ apt install hcxdumptool
 [!] Warning: Recommended app hcxpcapngtool was not found. install @ apt install hcxtools

 [+] Checking airmon-ng...
 [!] airmon-ng did not find any wireless interfaces
 [!] Make sure your wireless device is connected
 [!] See http://www.aircrack-ng.org/doku.php?id=airmon-ng for more info

 [!] Error: airmon-ng did not find any wireless interfaces

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/lib/python3/dist-packages/wifite/__main__.py", line 97, in entry_point
 [!]        wifite.start()
 [!]    File "/usr/lib/python3/dist-packages/wifite/__main__.py", line 51, in start
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/usr/lib/python3/dist-packages/wifite/config.py", line 167, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/usr/lib/python3/dist-packages/wifite/tools/airmon.py", line 313, in ask
 [!]        raise Exception('airmon-ng did not find any wireless interfaces')
 [!]  Exception: airmon-ng did not find any wireless interfaces

 [!] Exiting

so I cant able to use wifi of my windows in my wsl so that I can practice wifi hacking.

### Expected Behavior

evert wsl must and should have a feature of running the wifi of windows.
so that security researcher can perform wifi hacking with authorization

### Actual Behavior

cant able to use wifi of windows 10

**Comment by jalaka** [comment]
As far as I know, wsl2 runs within a VM. So you can't just use hardware devices like wireless cards directly from within wsl2.

**Comment by ThalusA** [comment]
Being able to do PCIE-Passthrough and USB-Passthrough would be awesome :/

**Comment by firewall1337** [comment]
@jalaka then how to use wifi from wsl2?

**Comment by ThalusA** [comment]
> @jalaka then how to use wifi from wsl2?

You just can't

**Comment by firewall1337** [comment]
@ThalusA that's what I am asking here to do something with this issue so that I can practice wifi pentesting

**Comment by SiNaPsEr0x** [comment]
when introduce the feature?

**Comment by tobiasfrei** [comment]
this would be useful

**Comment by VidarDev** [comment]
Hmh bump

**Comment by tiborkiss** [comment]
Still I would like to use this feature...

**Comment by frankpop10** [comment]
I'm wondering is this would be possible with a bus pass like USBIPD

**Comment by ldlb96** [comment]
i think there is a way. I found this answer on unixstackchange from a guy. He litteraly says "Okay so, I edited the kernel itself to allow you to actually be able to use WiFi adapters as well as loadable modules, etc in WSL2

If anyone's interested here you go https://github.com/EDLLT/WSL2-Linux-Kernel" 
here is my source https://unix.stackexchange.com/questions/626328/are-usb-wi-fi-adapters-compatible-with-kali-in-wsl2

**Comment by mcDandy** [comment]
can confirm not working.

**Comment by tiborkiss** [comment]
I also made the kernel configuration. Since I wished to use the latest WSL2 kernel, I did from the scratch. Moreover I have another dongle (Alfa AWUS036ACH) which seems to not compile into the kernel by adding it directly to the source, but it compiles as dkms module.
For me it works well, since then I can capture 802.11 packets with the above dongle and I can use WSL2 for hardware debuggers too.
Here are my changes over the current officially released WSL2
https://github.com/tiborkiss/WSL2-Linux-Kernel/tree/linux-msft-wsl-5.10.102.1-rtlwifidongle

**Comment by aleph23** [comment]
Diff (MSFT 5.10.y <-tiborkiss 5.10-mod) for above: [https://github.com/microsoft/WSL2-Linux-Kernel/compare/linux-msft-wsl-5.10.y...tiborkiss:WSL2-Linux-Kernel:linux-msft-wsl-5.10.102.1-rtlwifidongle](url)

Appears to be a copy of changes from [https://github.com/EDLLT/WSL2-Linux-Kernel](url) that @ldlb96 highlighted 3 comments up.  Notable differences are @EDLLT outlines his custom build instructions ([https://github.com/EDLLT/WSL2-Linux-Kernel/blob/linux-msft-wsl-5.10.y/README.md](url)) and shares his build here: [https://github.com/EDLLT/WSL2-Linux-Kernel/releases](url)

**Comment by tiborkiss** [comment]
There are more differences. First of all, the base from where it was made by @ldlb96 it was older than the current WSL2 kernel release. I manually configured the kernel config, like from the scratch, I have more things to use, plus my dongle is different. Hence is not a copy. But overall, is just a configuration of the kernel, it's normal that should look similar also the diff.

**Comment by aleph23** [comment]
His is the latest 5.10.0.102.1 kernel.  I bring it up because I am also wanting to upgrade to the 5.15 kernel and the only difference between your config and his is the one module -- so assuming that config works with 5.15 also.  Is 5.15 the kernel you compiled?

**Comment by FuriousSlothing** [comment]
I believe you can make this work by enabling hyper-v in Windows features. From there open wsl command prompt
From windows start menu open hyper-v program and enable external adapters from wsl and select your specific adapter.
Try reinstalling drivers
And hopefully this good to go.

Plan b- bootable USB or vmware

**Comment by R0K0R** [comment]
I'm in 2023, still not working :/

**Comment by NSouza23** [comment]
> @jalakaentão como usar o wifi do wsl2?

You need a ralink usb wifi rt5370 for network conection!!!

**Comment by ishaan-kapoor** [comment]
hey, could any of you get it to work?

**Comment by Harsh181882** [comment]
> As far as I know, wsl2 runs within a VM. So you can't just use hardware devices like wireless cards directly from within wsl2.

so can we use hardware devices with a live OS

**Comment by TheAjaykrishnanR** [comment]
> i think there is a way. I found this answer on unixstackchange from a guy. He litteraly says "Okay so, I edited the kernel itself to allow you to actually be able to use WiFi adapters as well as loadable modules, etc in WSL2
> 
> If anyone's interested here you go https://github.com/EDLLT/WSL2-Linux-Kernel" here is my source https://unix.stackexchange.com/questions/626328/are-usb-wi-fi-adapters-compatible-with-kali-in-wsl2

Absolutely worked with my tp link archer ac600 t2u Plus

**Comment by TheAjaykrishnanR** [comment]
> hey, could any of you get it to work?



> hey, could any of you get it to work?

yep

**Comment by ooplaza** [comment]
Still not working on 2024?

**Comment by craigloewen-msft** [comment]
Mirrored mode should show the different adapters in WSL, does this solve the use case?

https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking

**Comment by craigloewen-msft** [comment]
I'm closing out old issues. If you're still seeing this, please reopen a new issue! Thank you!

**Comment by dzhelek** [comment]
Still not working on 2025?
