### ISSUE TITLE
ChromeDriverManager doesn't work as expected on WSL2

### ISSUE THREAD

**Issue by irvifa** [microsoft/WSL#7755]
### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu 20.04

### Other Software

Selenium

### Repro Steps

```shell
vim requirements.txt
```

enter the following dependencies:
```
webdriver-manager   3.5.2
selenium            4.1.0
pytest              6.2.5
Django              3.2.9
```

install the dependencies
```shell
pip install requirements.txt
```

create a sample test:
```
from django.test import TestCase
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

class TestFoo(TestCase):

    def setUp(self):
        self.driver = webdriver.Chrome(ChromeDriverManager().install())
```

### Expected Behavior

I will be able to use webdriver-manager instead of pointing out the chromedriver directly.

### Actual Behavior

Selenium failed with the following error:
```
$ python manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
............

====== WebDriver manager ======
Could not get version for google-chrome with the any command: google-chrome --version || google-chrome-stable --version
Current google-chrome version is UNKNOWN
Get LATEST chromedriver version for UNKNOWN google-chrome
There is no [linux64] chromedriver for browser  in cache
Trying to download new driver from https://chromedriver.storage.googleapis.com/96.0.4664.45/chromedriver_linux64.zip
Driver has been saved in cache [/home/irvifa/.wdm/drivers/chromedriver/linux64/96.0.4664.45]
E...........
======================================================================
ERROR: test_signup_fire (tests.clubs.test_views.TestSignup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/irvif/dev/edinburgh/group_6/frontend/gamecollection_website/tests/clubs/test_views.py", line 8, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "/mnt/c/Users/irvif/dev/edinburgh/group_6/frontend/.env/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/mnt/c/Users/irvif/dev/edinburgh/group_6/frontend/.env/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/mnt/c/Users/irvif/dev/edinburgh/group_6/frontend/.env/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "/mnt/c/Users/irvif/dev/edinburgh/group_6/frontend/.env/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/mnt/c/Users/irvif/dev/edinburgh/group_6/frontend/.env/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/mnt/c/Users/irvif/dev/edinburgh/group_6/frontend/.env/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
```

**Comment by OneBlue** [comment]
Thanks for reporting this @irvifa.

Looking at the output, this doesn't look at a WSL issue, so closing this. 

You might want to look at [this thread](https://developercommunity.visualstudio.com/t/selenium-ui-test-can-no-longer-find-chrome-binary/1170486)

**Comment by Rafasmafa** [comment]
Did you happen to find a fix for this issue @irvifa? I'm experiencing the same issue the thread posted above did not help.

**Comment by irvifa** [comment]
No I still haven't find a fix for this issue

**Comment by raulpacheco2k** [comment]
I'm having the same issue when using WebDriverManager with Selenium in Java
