### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80070241 after install KB5003791

### ISSUE THREAD

**Issue by ftoyon** [microsoft/WSL#7843]
### Version

Microsoft Windows [version 10.0.19044.1415]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Any

### Repro Steps

Start with Microsoft Windows [version 10.0.19043.1415]
All are fine you can install any distro
Install KB5003791: Update to Windows 10, version 21H2 by using an enablement package
=> Microsoft Windows [version 10.0.19044.1415]
All try install any distro failed with message WslRegisterDistribution failed with error: 0x80070241
Uninstall KB5003791
Everything works perfectly again

### Expected Behavior

Installation succes like :

Installing, this may take a few minutes...
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username:

### Actual Behavior

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070241
Error: 0x80070241 Windows cannot verify the digital signature of this file. It is possible that a recent hardware or software modification installed a damaged or incorrectly signed file, or it could be malware from an unknown source.

Press any key to continue...

### Diagnostic Logs

[Feedback Hub](https://aka.ms/AAfaffk)

**Comment by superhero75** [comment]
wsl wont start and has exactly the same issue after update. cant access any distros. 

windows os build: 19044.1415

I have triple checked all my virtualisation settings in both BIOS and windows features have been enabled. I have also disabled them and re-enabled and rebooted several times too.

If I download any new distro from app store and install, here is the output: 

WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.

If I try to start my existing distro: 

Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install
Press any key to continue...

**Comment by ftoyon** [comment]
We have update the issue with the link on [Feedback Hub link](https://aka.ms/AAfaffk)

**Comment by OneBlue** [comment]
Thanks @ftoyon.

Looking at the logs, I can see:
```
366 |   | Error | win:Info | 0 | Unknown | Error | 0 | 6888 | onecore\vm\wsl\lxss\lxcmdlineshared\hcs.cpp | 244 | 0 | 1 | 6888 | 0x80070241 | (null) |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 | 16.860752200
```

The issue is that WSL fails to communicate to the HostCompute service, probably because it fails to start.

Can you share the output of `sc start vmcompute` in an elevated command prompt ?

**Comment by ftoyon** [comment]
Hi @OneBlue,

The service is started

```
sc start vmcompute
[SC] StartService échec(s) 1056 :

Une instance du service s’exécute déjà.
```

and if I restart it after stoping service dependecy CmService:
```
sc stop vmcompute

SERVICE_NAME: vmcompute
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 3  STOP_PENDING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

sc start vmcompute

SERVICE_NAME: vmcompute
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 27784
        FLAGS              :
```

**Comment by OneBlue** [comment]
Thank you @ftoyon. I had a deeper look and noticed this:

```
427, , , , , , ActivityError, 1, 9376, 16777216, {2147942977; onecore\vm\compute\shared\vmwp\lib\workerprocessdevice.cpp; 81; vmcompute.exe; 0; ; 9376; \VirtualMachine_ModifySettings\ComputeSystem_ConfigureGpu; 20; VirtualMachine_ModifySettings; ; 21; ComputeSystem_ConfigureGpu; ; 30; 20; }, , , , , , , , , , , , , , , , , , , , 1, 16.860577800

``` 

This error is thrown when WSL tries to attach virtual GPU's to the VM. 

Can you try to add:

```
[wsl2]
gpuSupport=false
```

To %userprofile%/.wslconfig, and see if that solves the issue ? 

Also, can you share the ouput of `Get-WmiObject Win32_VideoController` ? I wonder if the issue is caused by an specific GPU driver

**Comment by ftoyon** [comment]
Hi @OneBlue,

I'm create a file %userprofile%/.wslconfig, but that does not correct the problem.

![image](https://user-images.githubusercontent.com/1707426/147644593-0560102f-7120-48e9-b229-485209eca7a7.png)


The `Get-WmiObject Win32_VideoController` result
```
__GENUS                      : 2
__CLASS                      : Win32_VideoController
__SUPERCLASS                 : CIM_PCVideoController
__DYNASTY                    : CIM_ManagedSystemElement
__RELPATH                    : Win32_VideoController.DeviceID="VideoController1"
__PROPERTY_COUNT             : 59
__DERIVATION                 : {CIM_PCVideoController, CIM_VideoController, CIM_Controller, CIM_LogicalDevice...}
__SERVER                     : PC-FREDERIC
__NAMESPACE                  : root\cimv2
__PATH                       : \\PC-FREDERIC\root\cimv2:Win32_VideoController.DeviceID="VideoController1"
AcceleratorCapabilities      :
AdapterCompatibility         : Intel Corporation
AdapterDACType               : Internal
AdapterRAM                   : 1073741824
Availability                 : 3
CapabilityDescriptions       :
Caption                      : Intel(R) UHD Graphics 630
ColorTableEntries            :
ConfigManagerErrorCode       : 0
ConfigManagerUserConfig      : False
CreationClassName            : Win32_VideoController
CurrentBitsPerPixel          : 32
CurrentHorizontalResolution  : 1920
CurrentNumberOfColors        : 4294967296
CurrentNumberOfColumns       : 0
CurrentNumberOfRows          : 0
CurrentRefreshRate           : 60
CurrentScanMode              : 4
CurrentVerticalResolution    : 1080
Description                  : Intel(R) UHD Graphics 630
DeviceID                     : VideoController1
DeviceSpecificPens           :
DitherType                   : 0
DriverDate                   : 20210322000000.000000-000
DriverVersion                : 27.20.100.9415
ErrorCleared                 :
ErrorDescription             :
ICMIntent                    :
ICMMethod                    :
InfFilename                  : oem47.inf
InfSection                   : iCML_w10_DS
InstallDate                  :
InstalledDisplayDrivers      : C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3ea756ac68d34d21\igdum
                               dim64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3ea756ac68d3
                               4d21\igd10iumd64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3
                               ea756ac68d34d21\igd10iumd64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.
                               inf_amd64_3ea756ac68d34d21\igd12umd64.dll
LastErrorCode                :
MaxMemorySupported           :
MaxNumberControlled          :
MaxRefreshRate               : 75
MinRefreshRate               : 59
Monochrome                   : False
Name                         : Intel(R) UHD Graphics 630
NumberOfColorPlanes          :
NumberOfVideoPages           :
PNPDeviceID                  : PCI\VEN_8086&DEV_9BC5&SUBSYS_9BC51849&REV_05\3&11583659&0&10
PowerManagementCapabilities  :
PowerManagementSupported     :
ProtocolSupported            :
ReservedSystemPaletteEntries :
SpecificationVersion         :
Status                       : OK
StatusInfo                   :
SystemCreationClassName      : Win32_ComputerSystem
SystemName                   : PC-FREDERIC
SystemPaletteEntries         :
TimeOfLastReset              :
VideoArchitecture            : 5
VideoMemoryType              : 2
VideoMode                    :
VideoModeDescription         : 1920 x 1080 x 4294967296 couleurs
VideoProcessor               : Intel(R) UHD Graphics Family
PSComputerName               : PC-FREDERIC

__GENUS                      : 2
__CLASS                      : Win32_VideoController
__SUPERCLASS                 : CIM_PCVideoController
__DYNASTY                    : CIM_ManagedSystemElement
__RELPATH                    : Win32_VideoController.DeviceID="VideoController2"
__PROPERTY_COUNT             : 59
__DERIVATION                 : {CIM_PCVideoController, CIM_VideoController, CIM_Controller, CIM_LogicalDevice...}
__SERVER                     : PC-FREDERIC
__NAMESPACE                  : root\cimv2
__PATH                       : \\PC-FREDERIC\root\cimv2:Win32_VideoController.DeviceID="VideoController2"
AcceleratorCapabilities      :
AdapterCompatibility         : NVIDIA
AdapterDACType               : Integrated RAMDAC
AdapterRAM                   : 2147483648
Availability                 : 3
CapabilityDescriptions       :
Caption                      : NVIDIA Quadro P620
ColorTableEntries            :
ConfigManagerErrorCode       : 0
ConfigManagerUserConfig      : False
CreationClassName            : Win32_VideoController
CurrentBitsPerPixel          : 32
CurrentHorizontalResolution  : 1920
CurrentNumberOfColors        : 4294967296
CurrentNumberOfColumns       : 0
CurrentNumberOfRows          : 0
CurrentRefreshRate           : 60
CurrentScanMode              : 4
CurrentVerticalResolution    : 1080
Description                  : NVIDIA Quadro P620
DeviceID                     : VideoController2
DeviceSpecificPens           :
DitherType                   : 0
DriverDate                   : 20201211000000.000000-000
DriverVersion                : 27.21.14.6089
ErrorCleared                 :
ErrorDescription             :
ICMIntent                    :
ICMMethod                    :
InfFilename                  : oem30.inf
InfSection                   : Section046
InstallDate                  :
InstalledDisplayDrivers      : C:\Windows\System32\DriverStore\FileRepository\nv_dispwi.inf_amd64_6aff784835dbd902\nvld
                               umdx.dll,C:\Windows\System32\DriverStore\FileRepository\nv_dispwi.inf_amd64_6aff784835db
                               d902\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nv_dispwi.inf_amd64_6af
                               f784835dbd902\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nv_dispwi.inf_
                               amd64_6aff784835dbd902\nvldumdx.dll
LastErrorCode                :
MaxMemorySupported           :
MaxNumberControlled          :
MaxRefreshRate               : 75
MinRefreshRate               : 50
Monochrome                   : False
Name                         : NVIDIA Quadro P620
NumberOfColorPlanes          :
NumberOfVideoPages           :
PNPDeviceID                  : PCI\VEN_10DE&DEV_1CB6&SUBSYS_126410DE&REV_A1\4&30760922&0&0008
PowerManagementCapabilities  :
PowerManagementSupported     :
ProtocolSupported            :
ReservedSystemPaletteEntries :
SpecificationVersion         :
Status                       : OK
StatusInfo                   :
SystemCreationClassName      : Win32_ComputerSystem
SystemName                   : PC-FREDERIC
SystemPaletteEntries         :
TimeOfLastReset              :
VideoArchitecture            : 5
VideoMemoryType              : 2
VideoMode                    :
VideoModeDescription         : 1920 x 1080 x 4294967296 couleurs
VideoProcessor               : Quadro P620
PSComputerName               : PC-FREDERIC

```

PS : I wanted to add a new recording to my feeback hub and I get this error
![image](https://user-images.githubusercontent.com/1707426/147643776-3c22a6ff-2384-4387-999b-e51aee46cf6d.png)

**Comment by ftoyon** [comment]
Hi !
I worried about not seeing any new requests or information!
Do you have any clues for a solution?

**Comment by OneBlue** [comment]
Thanks for the update @ftoyon. I'm surprised that the .wslconfig change didn't help.

Can capture logs again with the .wslconfig change ?

**Comment by ftoyon** [comment]
Hi,

New try with manual trace because we can't make an log with hub !

See [wsl.zip](https://github.com/microsoft/WSL/files/7912184/wsl.zip)

Thank you!

**Comment by killshot13** [comment]
Same issue on:
Windows 11 Education
Version	21H2
Build 22000.526

I also tried the `.wslconfig` suggestion, but it changed nothing.

Output of `Get-WmiObject Win32_VideoController`

```
C:\Windows on ☁️ (US East (N. Virginia))
❯  Get-WmiObject Win32_VideoController

RunspaceId                   : fb605f84-5739-4bb0-869e-f0471264c33f
__GENUS                      : 2
__CLASS                      : Win32_VideoController
__SUPERCLASS                 : CIM_PCVideoController
__DYNASTY                    : CIM_ManagedSystemElement
__RELPATH                    : Win32_VideoController.DeviceID="VideoController1"
__PROPERTY_COUNT             : 59
__DERIVATION                 : {CIM_PCVideoController, CIM_VideoController, CIM_Controller, CIM_LogicalDevice…}
__SERVER                     : REDQUEEN1
__NAMESPACE                  : root\cimv2
__PATH                       : \\REDQUEEN1\root\cimv2:Win32_VideoController.DeviceID="VideoController1"
AcceleratorCapabilities      :
AdapterCompatibility         : Intel Corporation
AdapterDACType               : Internal
AdapterRAM                   : 1073741824
Availability                 : 3
CapabilityDescriptions       :
Caption                      : Intel(R) Iris(R) Plus Graphics
ColorTableEntries            :
ConfigManagerErrorCode       : 0
ConfigManagerUserConfig      : False
CreationClassName            : Win32_VideoController
CurrentBitsPerPixel          : 32
CurrentHorizontalResolution  : 2736
CurrentNumberOfColors        : 4294967296
CurrentNumberOfColumns       : 0
CurrentNumberOfRows          : 0
CurrentRefreshRate           : 59
CurrentScanMode              : 4
CurrentVerticalResolution    : 1824
Description                  : Intel(R) Iris(R) Plus Graphics
DeviceID                     : VideoController1
DeviceSpecificPens           :
DitherType                   : 0
DriverDate                   : 20210615000000.000000-000
DriverVersion                : 27.20.100.9621
ErrorCleared                 :
ErrorDescription             :
ICMIntent                    :
ICMMethod                    :
InfFilename                  : oem185.inf
InfSection                   : iICLD_w10_DS_N
InstallDate                  :
InstalledDisplayDrivers      : C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_d73f88d32ddb95d3\igdum
                               dim64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_d73f88d32ddb
                               95d3\igd10iumd64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_d
                               73f88d32ddb95d3\igd10iumd64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.
                               inf_amd64_d73f88d32ddb95d3\igd12umd64.dll
LastErrorCode                :
MaxMemorySupported           :
MaxNumberControlled          :
MaxRefreshRate               : 59
MinRefreshRate               : 59
Monochrome                   : False
Name                         : Intel(R) Iris(R) Plus Graphics
NumberOfColorPlanes          :
NumberOfVideoPages           :
PNPDeviceID                  : PCI\VEN_8086&DEV_8A5A&SUBSYS_00371414&REV_07\3&11583659&0&10
PowerManagementCapabilities  :
PowerManagementSupported     :
ProtocolSupported            :
ReservedSystemPaletteEntries :
SpecificationVersion         :
Status                       : OK
StatusInfo                   :
SystemCreationClassName      : Win32_ComputerSystem
SystemName                   : REDQUEEN1
SystemPaletteEntries         :
TimeOfLastReset              :
VideoArchitecture            : 5
VideoMemoryType              : 2
VideoMode                    :
VideoModeDescription         : 2736 x 1824 x 4294967296 colors
VideoProcessor               : Intel(R) Iris(R) Graphics Family
```

Output of `sc start vmcompute`

```
C:\Windows on ☁️  (US East (N. Virginia)) took 24s
❯ sc start vmcompute
[SC] StartService FAILED 1056:

An instance of the service is already running.
```

Output of `sc stop vmcompute`

```
C:\Windows on ☁️  (US East (N. Virginia))
❯ sc stop vmcompute
[SC] ControlService FAILED 1051:

A stop control has been sent to a service that other running services are dependent on.
```

**Comment by killshot13** [comment]
Additionally, my computer has experienced numerous BSODs since the first instance of the bug about three or four days ago. I have lost all ability to access my existing WSL2 builds. Here are some of the error messages I would receive.

```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\dmreh\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

For information please visit https://aka.ms/wsl2-install


 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-17132\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-17132\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-17132\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__28.MoveNext() in C:\workspaces\PR-17132\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 179
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-17132\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-17132\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-17132\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

This one was the most common, everytime I would run `wsl.exe` or `ubuntu.exe` it would say this no matter what terminal I used.

```
Overlapped I/O operation is in progress.

[process exited with code 1 (0x00000001)]
```

![wsl](https://user-images.githubusercontent.com/47695475/153810100-88a08bfd-415c-4046-be43-3d183451b1e7.png)

**Comment by killshot13** [comment]
I since tried turning all the optional features for WSL2 off and then re-enabling them, but it just says this.

```
C:\Windows on ☁️  (US East (N. Virginia))
❯ wsl.exe
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install
```

**Comment by OneBlue** [comment]
Thanks for the logs @ftoyon.

The latest logs show the same error so it looks like something is wrong with some of the system binaries.

What's the output of (elevated command prompt):
```
sfc /scannow
```` 
?

**Comment by ftoyon** [comment]
Hi @OneBlue.

sfc not found intigrity violation.

For information when I uninstall the KB5003791 everything works correctly again and when I reinstall the KB I have the problem.

**Comment by ftoyon** [comment]
Hi @OneBlue 

I can hope for a solution

**Comment by OneBlue** [comment]
@ftoyon: I looked at the logs again and it still looks like WSL is trying to configure the GPU, although .wslconfig has gpuSupport set to false, which is really weird.

Can you please try set this in .wslconfig again:

```
[wsl2]
gpuSupport=false
``` 

Then run: wsl --shutdown

And then try to start wsl with log collection again ? I suspect that the .wslconfig change wasn't taken into account.

**Comment by ftoyon** [comment]
Hi !

**As a reminder: in order to reproduce the error, I need to reinstall the KB5003791, then uninstalling this KB allows WSL to rework correctly again.**

Another point ; it is now impossible for me to reuse the feedback hub to collect information, I have to go through wsl.wprp!

[wsl crash info.zip](https://github.com/microsoft/WSL/files/8487073/wsl.crash.info.zip)

In this file you find:

- my ".wslconfig" file
- a screenshoot of  `wsl --instal -d ubuntu` window result
- a screenshoot of my %userprofile% folder
- a file with the `Get-WmiObject Win32_VideoController` output
- the wsl.wprp result

**Comment by OneBlue** [comment]
Thanks @ftoyon.

Looking at the logs, it looks like the signature of `C:\windows\System32\vmvpci.dll` isn't accepted.

Can you share the output of:

```
Get-AuthenticodeSignature C:\windows\System32\vmvpci.dll
```

And:

```
Get-AuthenticodeSignature C:\windows\System32\*.dll | where { $_.Status.ToString() -ne "Valid"}
Get-AuthenticodeSignature C:\windows\System32\drivers\*.sys | where { $_.Status.ToString() -ne "Valid"}
```

In an elevated powershell ? 
That should help us understand which signatures are rejected

**Comment by ftoyon** [comment]
Hi !

You can find the command with his result :

```
> Get-AuthenticodeSignature C:\windows\System32\vmvpci.dll

    Répertoire : C:\windows\System32

SignerCertificate                         Status                                 Path
-----------------                         ------                                 ----
                                          NotSigned                              vmvpci.dll

> Get-AuthenticodeSignature C:\windows\System32\*.dll | where { $_.Status.ToString() -ne "Valid"}

    Répertoire : C:\windows\System32

SignerCertificate                         Status                                 Path
-----------------                         ------                                 ----
                                          NotSigned                              appmgmts.dll
                                          NotSigned                              cewmdm.dll
                                          NotSigned                              clrhost.dll
                                          NotSigned                              CNC_CTC.dll
                                          NotSigned                              CNC_CTI.dll
                                          NotSigned                              CNC_CTL.dll
                                          NotSigned                              CNHMCA6.dll
                                          NotSigned                              CNMLMCT.DLL
                                          NotSigned                              cscui.dll
                                          NotSigned                              d2d1debug3.dll
                                          NotSigned                              d3d11_3SDKLayers.dll
                                          NotSigned                              d3d12SDKLayers.dll
                                          NotSigned                              d3dref9.dll
                                          NotSigned                              ddpchunk.dll
                                          NotSigned                              ddptrace.dll
                                          NotSigned                              ddputils.dll
                                          NotSigned                              ddp_ps.dll
                                          NotSigned                              DeviceUpdateCenterCsp.dll
                                          NotSigned                              dfshim.dll
                                          NotSigned                              DiagSvc.dll
                                          NotSigned                              DialogBlockerProc.dll
                                          NotSigned                              DialogBlockingManager.dll
                                          NotSigned                              DialogBlockingService.dll
                                          NotSigned                              DirectML.Debug.dll
                                          NotSigned                              DragDropExperienceCommon.dll
                                          NotSigned                              drt.dll
                                          NotSigned                              drtprov.dll
                                          NotSigned                              drttransport.dll
                                          NotSigned                              DucUpdateAgent.dll
                                          NotSigned                              DXCaptureReplay.dll
                                          NotSigned                              DXGIDebug.dll
                                          NotSigned                              DXToolsMonitor.dll
                                          NotSigned                              DXToolsOfflineAnalysis.dll
                                          NotSigned                              DxToolsReportGenerator.dll
                                          NotSigned                              DXToolsReporting.dll
                                          NotSigned                              gpprefcl.dll
                                          NotSigned                              gpscript.dll
                                          NotSigned                              Groupinghc.dll
                                          NotSigned                              inetpp.dll
                                          NotSigned                              inetppui.dll
                                          NotSigned                              KeyboardFilterManager.dll
                                          NotSigned                              libcrypto.dll
                                          NotSigned                              LSCSHostPolicy.dll
                                          NotSigned                              lstelemetry.dll
                                          NotSigned                              madrid.dll
                                          NotSigned                              MemoryDiagnostic.dll
                                          NotSigned                              mfdvdec.dll
                                          NotSigned                              mfvfw.dll
                                          NotSigned                              MFWMAAEC.DLL
                                          NotSigned                              MSAC3ENC.DLL
                                          NotSigned                              MSAlacEncoder.dll
                                          NotSigned                              mscoree.dll
                                          NotSigned                              mscorier.dll
                                          NotSigned                              MSFlacEncoder.dll
                                          NotSigned                              MSMPEG2ENC.DLL
                                          NotSigned                              msrahc.dll
                                          NotSigned                              msrdc.dll
                                          NotSigned                              mswmdm.dll
                                          NotSigned                              NcdAutoSetup.dll
                                          NotSigned                              netfxperf.dll
                                          NotSigned                              NlsData000c.dll
                                          NotSigned                              NlsLexicons000c.dll
                                          NotSigned                              OcpUpdateAgent.dll
                                          NotSigned                              OEMDefaultAssociations.dll
                                          NotSigned                              P2P.dll
                                          NotSigned                              P2PGraph.dll
                                          NotSigned                              p2pnetsh.dll
                                          NotSigned                              p2psvc.dll
                                          NotSigned                              pdfcmon.dll
                                          NotSigned                              perf_gputiming.dll
                                          NotSigned                              photowiz.dll
                                          NotSigned                              pmcsnap.dll
                                          NotSigned                              pnrpauto.dll
                                          NotSigned                              Pnrphc.dll
                                          NotSigned                              pnrpnsp.dll
                                          NotSigned                              pnrpsvc.dll
                                          NotSigned                              ppcsnap.dll
                                          NotSigned                              PresentationHostProxy.dll
                                          NotSigned                              ProjectedFSLib.dll
                                          NotSigned                              racpldlg.dll
                                          NotSigned                              RemoteAppLifetimeManagerProxyStub.dll
                                          NotSigned                              SecureAssessmentHandlers.dll
                                          NotSigned                              signdrv.dll
                                          NotSigned                              tscfgwmi.dll
                                          NotSigned                              tssrvlic.dll
                                          NotSigned                              umrdp.dll
                                          NotSigned                              vmvpci.dll
                                          NotSigned                              VSD3DWARPDebug.dll
                                          NotSigned                              VsGraphicsCapture.dll
                                          NotSigned                              VsGraphicsExperiment.dll
                                          NotSigned                              VsGraphicsProxyStub.dll
878CE7C28C8079F0117F65FA5A7742AD017EAB9D  UnknownError                           WdfCoInstaller01009.dll
                                          NotSigned                              WebcamUi.dll
                                          NotSigned                              WfHC.dll
                                          NotSigned                              Windows.Internal.Management.SecureA...
                                          NotSigned                              Windows.Internal.PredictionUnit.dll
                                          NotSigned                              Windows.Management.SecureAssessment...
                                          NotSigned                              Windows.Management.SecureAssessment...
                                          NotSigned                              Windows.Media.Renewal.dll
                                          NotSigned                              WindowsIoTCsp.dll
                                          NotSigned                              wmcodecdspps.dll
                                          NotSigned                              wmdmlog.dll
                                          NotSigned                              wmdmps.dll
                                          NotSigned                              WmpDui.dll
                                          NotSigned                              WMSPDMOE.DLL
                                          NotSigned                              wmvdspa.dll
                                          NotSigned                              WMVSENCD.DLL
                                          NotSigned                              WMVXENCD.DLL
                                          NotSigned                              WpdMtp.dll
                                          NotSigned                              WpdMtpUS.dll
                                          NotSigned                              wsepno.dll

> Get-AuthenticodeSignature C:\windows\System32\drivers\*.sys | where { $_.Status.ToString() -ne "Valid"}

    Répertoire : C:\windows\System32\drivers

SignerCertificate                         Status                                 Path
-----------------                         ------                                 ----
                                          NotSigned                              ew_usbccgpfilter.sys
                                          NotSigned                              hw_cdcacm.sys
                                          NotSigned                              hw_quusbmdm.sys
                                          NotSigned                              hw_quusbnet.sys
                                          NotSigned                              hw_usbdev.sys
                                          NotSigned                              rdpbus.sys
                                          NotSigned                              rdpdr.sys
                                          NotSigned                              smbdirect.sys
```

**Comment by ftoyon** [comment]
Hi @OneBlue 

Do you find anything?

**Comment by OneBlue** [comment]
Sorry @ftoyon, this issue fell off my radar.

Looking at the output you shared, I think the issue is that  C:\windows\System32\vmvpci.dll shows as 'Not signed'.
It should say 'Valid' for things to work correctly.

I'm not sure why this file shows up as not signed, I wonder if maybe a certificate is missing from the trusted root, or if maybe the time configured on your machine is off causing certificate validities to be wrong.

Does this file show up as signed if you uninstall KB5003791 ?

**Comment by ftoyon** [comment]
Don't worry it can happen.

Yes as I already said by uninstalling the KB5003791 it works again.

**Comment by ftoyon** [comment]
Hi @OneBlue !

This issue seems to have fallen off your radar again.

When I uninstall the KB5003791 I get the same results for `Get-AutheticodeSignature` and all working fine.

**Comment by ftoyon** [comment]
Hi @OneBlue you forgot me again?

**Comment by ftoyon** [comment]
Hi @OneBlue still no news !

**Comment by OneBlue** [comment]
Thanks for the ping @ftoyon. Unfortunately I don't have any good explanation to why vmvpci.dll isn't signed on your machine. 
One workaround I can think of would be to disable driver signature enforcement, via something like:

```bcdedit /set testsigning on```

Let me know if that helps.

**Comment by ftoyon** [comment]
Hi @OneBlue 

The installation of 22H2 patch solve all problems

Thank's for your help

**Comment by TimDeve** [comment]
For the people finding this thread and who already are on 22H2, I had the same problem (a bunch of unsigned dll in system32) and the solution was to do a clean "In-place Upgrade". Essentially to reinstall Windows while keeping the rest of the system intact. I followed step 3 of [this guide](https://www.computerworld.com/article/3080839/repair-windows-10-and-11-step-by-step-guide.html?page=2) and now both WSL and Easy Anticheat are happy.
