### ISSUE TITLE
Oddities with file locking or HTTP requests stalling

### ISSUE THREAD

**Issue by Helveg** [microsoft/WSL#8046]
### Version

Microsoft Windows [Version 10.0.22000.493]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

Python's `pip`, and other Python packages

### Repro Steps

```
sudo apt update
sudo apt install python3-pip
pip3 install numpy
```

I have completely reinstalled and updated WSL, tried multiple Ubuntu distributions. It seems to be tied more to maybe WSL not patching these requests through correctly to the host machine? I have had multiple machines with flawless WSL integration. What steps can I take to provide more debugging information?

### Expected Behavior

Install `numpy` smoothly

### Actual Behavior

About 4/5 times stalls indefinitely. The same behavior occurs whenever HTTP requests are made. Sometimes when I interrupt with `Ctrl+C` it shows that it was trying to acquire a file lock:

```
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://scipy.github.io/devdocs/objects.inv...
loading intersphinx inventory from https://errr.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://mpi4py.readthedocs.io/en/stable/objects.inv...
^C^C
Interrupted!
^CException ignored in: <module 'threading' from '/home/robin/.pyenv/versions/3.10.1/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/home/robin/.pyenv/versions/3.10.1/lib/python3.10/threading.py", line 1530, in _shutdown
    atexit_call()
  File "/home/robin/.pyenv/versions/3.10.1/lib/python3.10/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/home/robin/.pyenv/versions/3.10.1/lib/python3.10/threading.py", line 1089, in join
    self._wait_for_tstate_lock()
  File "/home/robin/.pyenv/versions/3.10.1/lib/python3.10/threading.py", line 1109, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
```

### Diagnostic Logs

Example of a series of attempts to run HTTP requests, each attempt was given 10 seconds before being terminated:

```
robin@LAPTOP-JF6T3PSU:~$ pip3 install numpy
Collecting numpy
^CERROR: Operation cancelled by user
robin@LAPTOP-JF6T3PSU:~$ pip3 install numpy
Collecting numpy
^CERROR: Operation cancelled by user
robin@LAPTOP-JF6T3PSU:~$ pip3 install numpy
^CERROR: Operation cancelled by user
robin@LAPTOP-JF6T3PSU:~$ pip3 install numpy
^CERROR: Operation cancelled by user
robin@LAPTOP-JF6T3PSU:~$ pip3 install numpy
Collecting numpy
  Downloading numpy-1.22.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     |████████████████████████████████| 16.8 MB 13.6 MB/s
Installing collected packages: numpy
Successfully installed numpy-1.22.2
```

When an attempt succeeds it succeeds immediately without delays. Things like `apt update` and `apt install` seem to work fine.

**Comment by owenschupp** [comment]
\logs
