### ISSUE TITLE
pip not giving any feedback on wsl and not working

### ISSUE THREAD

**Issue by mariobros2** [microsoft/WSL#8146]
### Version

[Version 10.0.19044.1586]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.4.72

### Distro Version

Ubuntu 20.04

### Other Software

visual studio code 1.65.2

### Repro Steps

pip install dnspython
or 
sudo pip install dnspython
or try to install any other modules with pip (even if the module do not exist)
pip install [anything]

### Expected Behavior

shows some errors or show the progress of the modules being installed

### Actual Behavior

it doesn't show anything, after 5 minutes i just stopped the execution with CTRL+C and that's the output(every time is the same output, no matter how many minutes )
```

^CTraceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    load_entry_point('pip==20.0.2', 'console_scripts', 'pip')()
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 19, in <module>
    from pip._internal.network.session import PipSession
  File "/usr/lib/python3/dist-packages/pip/_internal/network/session.py", line 26, in <module>
    from pip._internal.network.auth import MultiDomainBasicAuth
  File "/usr/lib/python3/dist-packages/pip/_internal/network/auth.py", line 36, in <module>
    import keyring  # noqa
  File "/usr/lib/python3/dist-packages/keyring/__init__.py", line 3, in <module>
    from .core import (
  File "/usr/lib/python3/dist-packages/keyring/core.py", line 189, in <module>
    init_backend()
  File "/usr/lib/python3/dist-packages/keyring/core.py", line 93, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/usr/lib/python3/dist-packages/keyring/util/__init__.py", line 21, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/keyring/backend.py", line 210, in get_all_keyring
    return list(rings)
  File "/usr/lib/python3/dist-packages/keyring/util/__init__.py", line 31, in suppress_exceptions
    for callable in callables:
  File "/usr/lib/python3/dist-packages/keyring/util/properties.py", line 26, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/lib/python3/dist-packages/keyring/backend.py", line 67, in viable
    cls.priority
  File "/usr/lib/python3/dist-packages/keyring/util/properties.py", line 26, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/lib/python3/dist-packages/keyring/backends/kwallet.py", line 37, in priority
    bus = dbus.SessionBus(mainloop=DBusGMainLoop())
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/exceptions.py", line 47, in __init__
    def __init__(self, *args, **kwargs):
KeyboardInterrupt
```

**Comment by elsaco** [comment]
@mariobros2 don't cancel it, just let it run. On my WSL2 Ubuntu it took longer than 5 min for the command to start executing. Can't say why. On the same WSL2 setup when using Arch `pip` runs immediately.

**Comment by mariobros2** [comment]
> @mariobros2 don't cancel it, just let it run. On my WSL2 Ubuntu it took longer than 5 min for the command to start executing. Can't say why. On the same WSL2 setup when using Arch `pip` runs immediately.

omg, thank you very much, i waited almost 10 minutes, but then it worked!!!

**Comment by Twenkid** [comment]
I am still having the same issue, same distro, latest Win 10. Yes, waiting "worked", but the delay is present after **each** following call, including feedback for errors. It's not just some weird "warm up" for the first call.

**Comment by Twenkid** [comment]
I found the solution somebody has found: it's the usage of an X-server.
https://github.com/pypa/pip/issues/9061

I have used XLaunch, too.

Run this in the WSL console:

export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0

Then pip returns quickly.
