### ISSUE TITLE
EmberJs serve not working

### ISSUE THREAD

**Issue by jrock2004** [Microsoft/WSL#877]
I am trying to get EmberJS to work and having problems running the server. 
- Expected results - Expected ember server to run on port 4200
- Actual results (with terminal output if applicable)

![image](https://cloud.githubusercontent.com/assets/655716/17636342/8065a4e6-60aa-11e6-8b60-800c6820f085.png)
- Your Windows build number - Version 1607 (OS Build 14393.51)
- Steps / commands required to reproduce the error

```
ember s
```
- Required packages and commands to install
- NodeJS
- bower
- ember-cli

After installing that, just generate a new project and try to run it

**Comment by aseering** [comment]
Hi @jrock2004 -- thanks for reporting this!  Hm...  At first glance, it looks very similar to ember-cli/ember-cli#115 .  Could you take a look?

**Comment by jrock2004** [comment]
Still the same results. No change

**Comment by jrock2004** [comment]
Ok, so I did a full reinstall of the linux environment. Installed node and ember. Now this time, I did not install watchman. Now I can start the server

```
❯ ember s                                                                                                     ✔ master
DEPRECATION: Node v0.10.25 is no longer supported by Ember CLI. Please update to a more recent version of Node
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.

Just getting started with Ember? Please visit http://localhost:4200/ember-getting-started to get going

The Broccoli Plugin: [object Object] failed with:
Error: watch EPERM
    at errnoException (fs.js:1024:11)
    at FSWatcher.start (fs.js:1056:11)
    at Object.fs.watch (fs.js:1081:11)
    at NodeWatcher.watchdir (/home/jcostanzo/Development/android/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/home/jcostanzo/Development/android/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:45:8)
    at new sane (/home/jcostanzo/Development/android/node_modules/ember-cli/node_modules/sane/index.js:17:12)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/home/jcostanzo/Development/android/node_modules/ember-cli/node_modules/broccoli-sane-watcher/index.js:93:17)
    at /home/jcostanzo/Development/android/node_modules/ember-cli/node_modules/ember-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/home/jcostanzo/Development/android/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jcostanzo/Development/android/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)

The broccoli plugin was instantiated at:
    at WatchedDir.Directory (/home/jcostanzo/Development/android/node_modules/ember-cli/node_modules/broccoli-source/index.js:14:31)
    at new WatchedDir (/home/jcostanzo/Development/android/node_modules/ember-cli/node_modules/broccoli-source/index.js:58:13)
    at EmberApp._initOptions (/home/jcostanzo/Development/android/node_modules/ember-cli/lib/broccoli/ember-app.js:200:17)
    at new EmberApp (/home/jcostanzo/Development/android/node_modules/ember-cli/lib/broccoli/ember-app.js:122:8)
    at module.exports (/home/jcostanzo/Development/android/ember-cli-build.js:6:13)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/home/jcostanzo/Development/android/node_modules/ember-cli/lib/models/builder.js:74:19)
    at CoreObject.module.exports.Task.extend.init (/home/jcostanzo/Development/android/node_modules/ember-cli/lib/models/builder.js:54:10)
    at CoreObject.superWrapper [as init] (/home/jcostanzo/Development/android/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/home/jcostanzo/Development/android/node_modules/ember-cli/node_modules/core-object/core-object.js:32:33)
    at CoreObject.module.exports.Task.extend.run (/home/jcostanzo/Development/android/node_modules/ember-cli/lib/tasks/serve.js:15:19)


Livereload server on http://localhost:49152
Serving on http://localhost:4200/
```

So it appears to be something on NodeWatcher and even more on Watchman.

**Comment by Nikoms** [comment]
Maybe the same issue as here: https://github.com/Microsoft/BashOnWindows/issues/899

**Comment by therealkenc** [comment]
#216
