### ISSUE TITLE
Windows Defender is fcking the performance of Windows 11 WSL2

### ISSUE THREAD

**Issue by gochev** [microsoft/WSL#8995]
### Version

Windows 11 22H2

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

all

### Repro Steps

turn off windows defender real protection
check any app using wsl2 network drive for indexing or reading.
Turn on windows Defender real protection
Try again.

### Expected Behavior

Windows Defender should NOT make WSL2 useless for IntelliJ IDEA , PhpStork , Raider IDE etc.

### Actual Behavior

the reindexing stuck on all none Microsoft IDEs

### Diagnostic Logs

I know Microsoft wants people to use VScode but this is just Ugly and super bad practice.

To force people to use stupid editor because Windows Defender is making other IDEs useless in WSL2 is just a dick move.

**Comment by gochev** [comment]
This was not an issue in Windows 10 before upgrade. Also it looks Windows Defender is not giving any shit about excluded folders since this doesn't helped only complete turn off of the Windows Defender Virus is the solution.

Good example of quality and improvement over time.

**Comment by gaborauth** [comment]
Oh, my whole day went to waste because I couldn't work with IntelliJ IDEA... then I ended up with this issue... :/

Yes, W11, 22H2, first cumulative update.

**Comment by bahag-xvisnei** [comment]
Dear WSL Team, please fix this asap

**Comment by Holy87** [comment]
Same problem here, Gradle project on WSL2 with IntelliJ.
This wasn't an issue before the upgrade to Windows 11.

**Comment by sefaYavuz** [comment]
Same problem here. Wasted like an entire week only to find out about this. Disabling realtime protection fixes it instantly with IntelliJ.

**Comment by ArjanShoj** [comment]
I had the same issue. This wasn't a problem on Windows 10. This occurred when I upgraded to Windows 11. By disabling Windows Defender it fixes the issue, but that shouldn't be a proper workaround, since my workstation is vulnerable now!

**Comment by lyleschemmerling** [comment]
I have the exact same problem, and can confirm turning off Defender takes care of it, but really don't consider that a solution.
Logs before disabling defender:

`2022-11-12 19:52:44,447 [ 464502]   INFO - #c.i.w.f.WslFsdServer - fsd standard output received: C:\WINDOWS\system32\wsl.exe [--distribution, Ubuntu-22.04, --exec, /bin/sh, -c, export RUST_LOG=info && cd /windows/c/myuser/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/plugins/wsl-fs-helper/bin && ./server --port 52444 --instance WSL-Ubuntu-22.04 --logs-path /windows/c/myuser/AppData/Local/JetBrains/IntelliJIdea2022.2/log/fsd]

2022-11-12 19:52:44,448 [ 464503]   INFO - #c.i.w.f.WslFsdServer - WSL fsd server started for Ubuntu-22.04 at port 52444
2022-11-12 19:52:44,448 [ 464503]   INFO - #f.r.c.Socket - Connecting to ws://localhost:52444
2022-11-12 19:52:44,460 [ 464515]   INFO - #c.i.w.f.WslContentLoader - Connection is not available. Current rpc strategy opted out waiting for reconnect.
fleet.rpc.client.RpcClientDisconnectedException: Connection is not available. Current rpc strategy opted out waiting for reconnect.
	at fleet.rpc.client.IRpcClientKt$reconnectingRpcClient$1$call$2.invokeSuspend(IRpcClient.kt:105)
	at fleet.rpc.client.IRpcClientKt$reconnectingRpcClient$1$call$2.invoke(IRpcClient.kt)
	at fleet.rpc.client.IRpcClientKt$reconnectingRpcClient$1$call$2.invoke(IRpcClient.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
`
`
2022-11-12 19:52:44,823 [ 464878]   INFO - #c.i.w.f.WslContentLoader - Permission denied (os error 13), path: /dev/kvm
java.io.IOException: Permission denied (os error 13), path: /dev/kvm
	at fleet.api.FsApiKt.ioException(FsApi.kt:429)
	at fleet.api.FsApiKt.unwrap(FsApi.kt:421)
	at com.intellij.wsl.fs.WslContentLoader$getInputStream$inputStream$1$1$1.invokeSuspend(WslContentLoader.kt:47)`

**Comment by Nastase** [comment]
+1

Same issue here. After upgrading to Windows 11, the whole JetBrains toolset is unusable for projects stored in WSL2. This is highly annoying as I simply cannot work in that setup.

For obvious reasons, disabling Windows Defender is not a solution.

**Comment by andruwa01** [comment]
+1 the same problem. Works only disable real time protection...

**Comment by baiyz0825** [comment]
+1 i have the same problem,when i using win11 and ubuntu22.04(wsl).the idea(2022.2.3) will frezen when indexing and scaning maven dependences . and i tried to close windows defender anti virus , that don't work for me . i hope this can be fix soon.
in the https://youtrack.jetbrains.com/issue/IDEA-286059/IDE-freezes-and-hangs-2021.3.1-on-indexing-of-WSL-project same most of user have same problem.
![image](https://user-images.githubusercontent.com/81071870/204027083-6b3306d2-af76-48c8-8f7f-1547e3d7dbe1.png)

**Comment by gaborauth** [comment]
Slow but good workaround: let the IntelliJ IDEA to update indexes, it takes a day or more. :/

**Comment by baiyz0825** [comment]
> 缓慢但很好的解决方法：让 IntelliJ IDEA 更新索引，这需要一天或更长时间。:/

you mean i spend some times to let the idea to update index , but when i create a new project , Whether it can be relieved ？or still have this problem.

**Comment by gaborauth** [comment]
> you mean i spend some times to let the idea to update index , but when i create a new project , Whether it can be relieved ？or still have this problem.

Yes, it's my workaround, fortunately I have old projects, so I let the IntelliJ IDEA to update the indexes and now it works. If you need a lot of new project, it is not a good workaround.

**Comment by baiyz0825** [comment]
> > you mean i spend some times to let the idea to update index , but when i create a new project , Whether it can be relieved ？or still have this problem.
> 
> Yes, it's my workaround, fortunately I have old projects, so I let the IntelliJ IDEA to update the indexes and now it works. If you need a lot of new project, it is not a good workaround.

ok,i know thank,hope wsl team can fix this

**Comment by gaborauth** [comment]
> ok,i know thank, hope wsl team can fix this

I hope too...

**Comment by no-ivan** [comment]
+1. Still performing real-time disabling

**Comment by Nastase** [comment]
Two months later and still no solution, neither from Microsoft nor Jetbrains. Seems they don't give two f**ks about their customers.

**Comment by ivanielin** [comment]
This is just vastly unacceptable - some reaction at least?

**Comment by SugarSpike** [comment]
+ Same here

**Comment by no-ivan** [comment]
![image](https://user-images.githubusercontent.com/5071221/208103363-cd49f4e2-491f-4ca9-aff1-80cb9f53e011.png)

**Comment by habnux** [comment]
If feel sometimes like Asterix... https://www.youtube.com/watch?v=ZHRGjfEQpy4

**Comment by joerosen** [comment]
FYI, on my machine I was able to fix this (with realtime protection enabled) by adding two exclusions to Windows Defender:

process: fsnotifier-wsl
process: idea64.exe

Running:

Windows 10 22H2 (19045.2364)
IntelliJ 2022.3 (community)
WSL version: 1.0.3.0

**Comment by adamwojszczyk** [comment]
@Nastase It works on win11. I tested that.

**Comment by Nastase** [comment]
It improves things but still get stuck on scanning index for maven dependencies

**Comment by joerosen** [comment]
@Nastase It took me a little while to get the right combo to exclude.  Maybe yours is slightly different?  Perhaps try a wildcard process exclusion on the entire intellij 'bin' directory?

https://support.microsoft.com/en-us/topic/how-to-add-a-file-type-or-process-exclusion-to-windows-security-e524cbc2-3975-63c2-f9d1-7c2eb5331e53

**Comment by andrewmmg** [comment]
Same here. The issue appeared after updating my WSL2 on Windows 10. 
Have spent a lot of time figuring this out until I found the solution proposed by @joerosen. Excluding those 2 processes did the trick.

For those who still experience some slowness in IDEA while indexing even after that fix - you might want to try disabling `wsl.fsd.content.loader` in the IDEA (Shift-Shift -> Experimantal Fetures -> Untick the Enabled checkbox next to the feature)

**Comment by Nastase** [comment]
Found another "solution": install a different antivirus. I installed the free version of Avast and all problems solved.

**Comment by vedrancu** [comment]
@joerosen 


> FYI, on my machine I was able to fix this (with realtime protection enabled) by adding two exclusions to Windows Defender:
> 
> process: fsnotifier-wsl process: idea64.exe
> 
> Running:
> 
> Windows 10 22H2 (19045.2364) IntelliJ 2022.3 (community) WSL version: 1.0.3.0

Thanks you a lot. 
After two day of strangling I found your solution. You saved me.

What is strange is that issue started about 10 days ago, before It worked fine.
Did windows defender make some changes recently?

**Comment by gochev** [comment]
Windows defender used to be a good app it's not anymore. Installing any other antivirus like avast fixes the issue

**Comment by eekboom** [comment]
I have the same (or a similar?) problem, even though using Sophos anti virus instead of Windows Defender.

Is there a way to downgrade back from the Microsoft Store version of WSL to the Windows WSL version?

**Comment by ivanielin** [comment]
Well, Avast Free Antivirus did the trick for me but this is is Just a workaround.
And still no answer here ?
this WSL support in 2023 is not encouraging to say the least...

**Comment by lukasamd** [comment]
I use 22H2 with WSL2 (Ubuntu 20.04) and phpstorm - no issues
Added some directories (docker, phpstorm, wsl, etc.) and processes (phpstorm, wsl) into exclusions, maybe it's a bit faster... Not sure.

It's faster if I use remote development on phpstorm or just use native linux instead of WSL, but it is not huge difference
Project is quite big and do not see indexing issues

You can also try disable interop in /etc/wsl.conf 
https://learn.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings

**Comment by vedrancu** [comment]
My problem was not in WSL2 but in Windows Defender.
After did exclusions as describe above, IDEA loads project quickly.

**Comment by lukasamd** [comment]
I also use Windows Defender - looks like it does not scan items inside WSL2 (tried to download eicar file - no reaction from Defender), but it can hits communication between host and linux distro. JetBrain's IDEs use a lot of communication in normal mode, different one is remote development or run it natively using WSLg, maybe it's the reason?

**Comment by GSuaki** [comment]
Plus one to Windows Defender problem! Fixed with exclusions.

**Comment by bademux** [comment]
Unfortunately windows is not intended to be used by humans.
It is the system for  updating, installing antiviruses and monitoring tools to have Sec team busy.

**Comment by lethunder** [comment]
Guys i excluded it from bitdefender and kaspersky but still not working. It's just too slow
![image](https://user-images.githubusercontent.com/6217812/211604941-2572cd34-e59a-40b4-adcb-823f19228010.png)

I'm on windows 11 with rubymine 2022.3.1

**Comment by dbalabka** [comment]
I added the following Windows Defender exclusion to fix IDEA performance issues:
Folders:
1. C:\Users\<username>\AppData\Local\JetBrains
2. C:\Programm Files\Docker

File types:
1. vhd
2. vhdx

Processes:
1. phpstorm64.exe
2. pycharm64.exe
3. dataspell64.exe
4. fsnotifier.exe
8. jcef_helper.exe
9. jetbrains-toolbox.exe
10. docker.exe
11. com.docker.*.*
12. Desktop Docker.exe
13. wsl.exe
14. wslhost.exe
15. vmmemWSL

**Comment by fikani** [comment]
> I added the following Windows Defender exclusion to fix IDEA performance issues: Folders:
> 
> 1. `C:\Users\<username>\AppData\Local\JetBrains`
> 2. `C:\Programm Files\Docker`
> 
> File types:
> 
> 1. vhd
> 2. vhdx
> 
> Processes:
> 
> 1. phpstorm64.exe
> 2. pycharm64.exe
> 3. dataspell64.exe
> 4. fsnotifier.exe
> 5. jcef_helper.exe
> 6. jetbrains-toolbox.exe
> 7. docker.exe
> 8. `com.docker.*.*`
> 9. Desktop Docker.exe
> 10. wsl.exe
> 11. wslhost.exe
> 12. vmmemWSL

Exclusively for intellij (my case) this worked.

I added the following Windows Defender exclusion to fix IDEA performance issues:

Folders:
C:\Users\<username>\AppData\Local\JetBrains

Processes:
idea64.exe



For PhpStorm I didnt need to do anything.

**Comment by joferrao** [comment]
Anyone else without an visibly active Antivirus with the same issue?

**Comment by lethunder** [comment]
It does the same thing if i disable bit defender and kaspersky. It keeps being slow

**Comment by lukasamd** [comment]
@lethunder It's normal - if you will disable 3party AV, defender will be activated, even in passive mode

**Comment by lethunder** [comment]
Thanks @lukasamd . Good to know. This issue makes my life much more difficult.

**Comment by dbalabka** [comment]
I've excluded WSL folders as well:
https://github.com/microsoft/WSL/issues/8995#issuecomment-1380187901

**Comment by lethunder** [comment]
for those using HP computer it was link to ironwolf. I disable it and it works

**Comment by Rattone** [comment]
> for those using HP computer it was link to ironwolf. I disable it and it works

can you please be more clear? which link?

**Comment by lethunder** [comment]
i have a HP Zbook. It comes by defaut with a software install HP Wolf Security. It was responsible for rubymine's slowness. As soon as i uninstall it everything went back

**Comment by Rattone** [comment]
> i have a HP Zbook. It comes by defaut with a software install HP Wolf Security. It was responsible for rubymine's slowness. As soon as i uninstall it everything went back

fucking ironwolf, i fixed it too by removing it

**Comment by khoandv** [comment]
Why don't you use real Linux instead? Or you can install [GUI on WSL2 ](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps) I installed ruby mine on WSL2 and it working fine.
Note the last point. No “performance across OS file systems”. That's a reason WSL2 is slow.

![image](https://user-images.githubusercontent.com/44995261/221737831-28a59a94-5c76-459a-9121-8ef4cd4f4a90.png)

**Comment by lyleschemmerling** [comment]
@khoandv or we could just use VS Code... Intellij on WSL is a totally viable, and to some even desirable, dev setup but on Windows 11 it is broken. Please don't clutter the thread with unhelpful noise.

**Comment by baiyz0825** [comment]
> I added the following Windows Defender exclusion to fix IDEA performance issues:
> Folders:
> 1. `C:\Users\<username>\AppData\Local\JetBrains`
> 2. `C:\Programm Files\Docker`
> 3. `\\wsl$\Ubuntu\home\user\src`
> 4. `\\wsl.localhost\Ubuntu\home\user\src`
> 
> File types:
> 1. vhd
> 2. vhdx
> 
> Processes:
> 1. phpstorm64.exe
> 2. pycharm64.exe
> 5. dataspell64.exe
> 6. fsnotifier.exe
> 8. jcef_helper.exe
> 9. jetbrains-toolbox.exe
> 10. docker.exe
> 11. `com.docker.*.*`
> 12. Desktop Docker.exe
> 13. wsl.exe
> 14. wslhost.exe
> 15. vmmemWSL 
> 
> 
> -----
> UPDATE: added WSL folders:
> 3. `\\wsl$\Ubuntu\home\user\src`
> 4. `\\wsl.localhost\Ubuntu\home\user\src`

it work for me

**Comment by vadviktor** [comment]
@baiyz0825 I can't select any WSL paths when I exclude a folder. Also, no virus scanning is done inside WSL when I test download a virus sample file that is used to test antivirus softwares. I'd say only suggest adding WSL folders when you have tested them actually being scanned by Defender.

**Comment by victorbjorn** [comment]
> 

I haven't seen any available WSL paths too but then I've just put \\wsl.localhost\ and got into it.

**Comment by miszczu** [comment]
> @khoandv or we could just use VS Code... Intellij on WSL is a totally viable, and to some even desirable, dev setup but on Windows 11 it is broken. Please don't clutter the thread with unhelpful noise.

How is it broken on Windows 11? I use it on Win11 machine for several months now. code and the IDE are in WSL, performance-wise it's very good.

**Comment by qwertynik** [comment]
Facing the same issue. WSL2 freezes after a period of inactivity, or, after logging back in.
Wondering if using Windows Home could be contributing to the issue.
Would appreciate it if someone from Windows can confirm.

**Comment by zhavir** [comment]
same issue here, is there any updates on it?

**Comment by shdblowers** [comment]
Also having this issue.

**Comment by gochev** [comment]
I believe the newest IntelliJ IDEA products have some workaround about this basically excluding a bunch of folders. However this is not ideal.

**Comment by Zack1550** [comment]
Would love to be able to code again.... Running windows 11 with the latest updates. 
I did notice that I can recreate the issue by attempting to save any file in pycharm. Every save causes 30-45 seconds of unresponsiveness.

**Comment by joaodejesus** [comment]
> FYI, on my machine I was able to fix this (with realtime protection enabled) by adding two exclusions to Windows Defender:
> 
> process: fsnotifier-wsl process: idea64.exe
> 
> Running:
> 
> Windows 10 22H2 (19045.2364) IntelliJ 2022.3 (community) WSL version: 1.0.3.0

Hey Bro, Thanks!! Works for me!

**Comment by ExplodingSalad** [comment]
More than half a year later and this is still an issue? Wow, amazing

**Comment by dkorobtsov** [comment]
> I added the following Windows Defender exclusion to fix IDEA performance issues: Folders:
> 
> 1. `C:\Users\<username>\AppData\Local\JetBrains`
> 2. `C:\Programm Files\Docker`
> 3. `\\wsl$\Ubuntu\home\user\src`
> 4. `\\wsl.localhost\Ubuntu\home\user\src`
> 
> File types:
> 
> 1. vhd
> 2. vhdx
> 
> Processes:
> 
> 1. phpstorm64.exe
> 2. pycharm64.exe
> 3. dataspell64.exe
> 4. fsnotifier.exe
> 5. jcef_helper.exe
> 6. jetbrains-toolbox.exe
> 7. docker.exe
> 8. `com.docker.*.*`
> 9. Desktop Docker.exe
> 10. wsl.exe
> 11. wslhost.exe
> 12. vmmemWSL
> 
> UPDATE: added WSL folders: 3. `\\wsl$\Ubuntu\home\user\src` 4. `\\wsl.localhost\Ubuntu\home\user\src`

To make it a bit less painful, added script to add exclusions :) 
Savel locally, adjust exclusions, run, enjoy. (at least for me it worked)
https://gist.github.com/dkorobtsov/963f3b90418e51d12aecb1eaf6106958#file-add_windowsdefender_exclusions-ps1

**Comment by itsmrhunter** [comment]
I cannot believe how much better PHPStorm's performance is after adding exclusions to Windows Defender... and I'm sure it's all just a complete random glitch that no on placed there on purpose to drive up VC Code marketshare and no one has bothered to investigate for years.

Microsoft should be thoroughly investigated for monopolization again.

**Comment by itsmrhunter** [comment]
I cannot believe how much better PHPStorm's performance is after adding exclusions to Windows Defender... and I'm sure it's all just a complete random glitch that no on placed there on purpose to drive up VS Code marketshare and no one has bothered to investigate for years.

Microsoft should be thoroughly investigated for monopolization.... again.

**Comment by moadle** [comment]
For those who use Maven, exclude your ".m2" directory also

**Comment by gochev** [comment]
I havent tried the powershell script but I can confirm that adding milion random things in exclusions list fixed the problem **without having AVG/AVAST installed** 

My exclusions list :

![image](https://github.com/microsoft/WSL/assets/5537142/5acd7402-7fc9-46aa-bfe2-011ae4376f88)
![image](https://github.com/microsoft/WSL/assets/5537142/60dd9f60-6394-43ac-868f-11015ec78f9c)


P.S. Strangely **Avira has the same issue it disables windows defender and** **breaks WSL2 as well.. if avira real time protection is enabled**. is Microsoft just selling us Avira ? anyway thats a different story

**Comment by ehmenzala** [comment]
Almost two years later and this is still a thing. LOL

**Comment by mfenderov** [comment]
+1 I've spent several days blaming Intellij for being "not good" and Windows 11 with WSL being unusable for development.
Things got fixed only after I disabled Windows Defender real-time protection. WTF?

**Comment by aaronshenhao** [comment]
What the actual heck? It worked (Windows 11 Version 10.0.22631 Build 22631).

IntelliJ was freezing whenever I had tried to add a JDK in WSL. Turned off Real Time protection via Windows Security > Virus & Thread Protection > Manage Settings, and killed the IntelliJ process on Task Manager. Then it instantly worked!

I don't get this behavior at all.

**Comment by gabrielfmagalhaes** [comment]
I gave up and changed to popOS. Honestly, this issue is absurd. Same as the guy above, I uninstalled IntelliJ multiple times before I realized that Windows is actively messing up, so you prioritize VSCode

**Comment by mikaelpeltier** [comment]
Hi,
Problem seems always the same, even with IntelliJ 2024.2.1, I need to turn off Real Time protection via Windows Security > Virus & Thread Protection > Manage Settings.
Is there some news about fixing this problem ?

**Comment by gochev** [comment]
hey there,
instead of "turning it off complete" you can exclude a bunch of folders which do the trick, just check my previous comment here https://github.com/microsoft/WSL/issues/8995#issuecomment-1828136060

However I also believe IntellIJ this days asks you to do this for you when you open a WSL folder/project for the first time, I think the popup says trust etc.. and I think it fixes the windows issues for you but not super sure, switched to mac and not gonna go back to the windows hell/nightmare ;)

**Comment by kaspian-xz** [comment]
Adding folders didn't help, only adding IDEA process to exclude solves the problem ...

**Comment by afoppa** [comment]
Hey there,

I've found this guide with a nice workaround https://superuser.com/questions/1714002/wsl2-connect-to-host-without-disabling-the-windows-firewall

It helped me to work with Intellij using the WSL2. The pain point is that you need to disable the firewall for vEthernet, but you can keep working without disable completely the firewall or Windows Defender real time protection.

**Comment by bhw-foss** [comment]
Adding exclusions removed input delay and sluggishness on WSL Emacs.
```
WSL version: 2.6.3.0
Kernel version: 6.6.87.2-1
WSLg version: 1.0.71
MSRDC version: 1.2.6353
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26200.7623

Linux bhw-yoga 6.6.87.2-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025 x86_64 GNU/Linux
```
Windows Security > Virus & threat protection settings > Exclusions > Add or remove exclusions > Add Folder "\\wsl.localhost\Debian" and Add Process "msrdc.exe". I then restarted my computer.

Either the performance degradation should go or the default should be to opt-out WSL drives. It makes the experience unbearably unresponsive.  WSL + Defender teams, please take note. Thank you.
