### ISSUE TITLE
Failed to change target system to 'WSL: Debian': Failed to start shell process

### ISSUE THREAD

**Issue by halim2209** [microsoft/WSL#9028]
### Version

Microsoft Windows [Version 10.0.19042.2130]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Debian 11

### Other Software

Visual Studio 2022 (17.3.6)
cmake version 3.18.4 (in Debian)

### Repro Steps

1. Open project folder using Visual Studio 2022
2. Try to switch target machine from "Local Machine" to "WSL: Debian"

### Expected Behavior

To be able to switch to Debian as the target running in WSL.

### Actual Behavior

CMake output window reads: "Failed to change target system to 'WSL: Debian': Failed to start shell process".

Additionally, cross platform logging window reads the following error:
```
21:13:46.7167564 [Info, Thread 10]	liblinux.Local.Services.WslEnumerator: Begin executing: C:\WINDOWS\System32\wsl.exe --list --verbose
21:13:46.7439176 [Info, Thread 21]	liblinux.Local.Services.WslEnumerator: End executing: C:\WINDOWS\System32\wsl.exe; exitcode: 0; duration: 00:00:00.0347345
21:13:47.6827132 [Info, Thread 6]	liblinux.Local.Services.WslEnumerator: Begin executing: C:\WINDOWS\System32\wsl.exe --list --verbose
21:13:47.7174335 [Info, Thread 61]	liblinux.Local.Services.WslEnumerator: End executing: C:\WINDOWS\System32\wsl.exe; exitcode: 0; duration: 00:00:00.0355494
21:13:47.7343265 [Info, Thread 20]	liblinux.Local.Services.WslEnumerator: Begin executing: C:\WINDOWS\System32\wsl.exe --list --verbose
21:13:47.7594819 [Info, Thread 62]	liblinux.Local.Services.WslEnumerator: End executing: C:\WINDOWS\System32\wsl.exe; exitcode: 0; duration: 00:00:00.0319021
21:13:47.7594819 [Info, Thread 1]	liblinux.Local.Shell.WindowsSubsystemShell: Connecting to shell at "C:\WINDOWS\System32\wsl.exe"
21:13:47.7594819 [Info, Thread 1]	liblinux.Local.Shell.WindowsSubsystemShell: VerifyEcho sentinel:9c00b7b8-03b2-468f-9e47-4a0ad9e23c54 id:242ac014-8208-45a1-9b60-e1329cafc4ce
21:13:47.7594819 [Info, Thread 1]	liblinux.Local.Shell.WindowsSubsystemShell: Writing "echo 9c00b7b8-03b2-468f-9e47-4a0ad9e23c54" to the 242ac014-8208-45a1-9b60-e1329cafc4ce shell
21:13:47.7594819 [Info, Thread 54]	liblinux.Local.Shell.WindowsSubsystemShell: Read async: 242ac014-8208-45a1-9b60-e1329cafc4ce
21:13:47.8018308 [Info, Thread 6]	liblinux.Local.Shell.WindowsSubsystemShell: Error Received: 'your 131072x1 screen size is bogus. expect trouble'
21:13:47.8018308 [Info, Thread 21]	liblinux.Local.Shell.WindowsSubsystemShell: Error Received: 'your 131072x1 screen size is bogus. expect trouble'
21:13:47.8376100 [Info, Thread 21]	liblinux.Local.Shell.WindowsSubsystemShell: Error Received: ''
21:13:47.8376100 [Info, Thread 59]	liblinux.Local.Shell.WindowsSubsystemShell: 242ac014-8208-45a1-9b60-e1329cafc4ce is exiting
21:13:47.8376100 [Info, Thread 80]	liblinux.Local.Shell.WindowsSubsystemShell: Disconnecting from shell 242ac014-8208-45a1-9b60-e1329cafc4ce
21:13:47.8531286 [Info, Thread 1]	liblinux.Local.Shell.WindowsSubsystemShell: VerifyEcho failed 242ac014-8208-45a1-9b60-e1329cafc4ce
21:13:47.8531286 [Error, Thread 1]	liblinux.Local.Shell.WindowsSubsystemShell: Exception starting shell process
21:13:47.8531286 [Error, Thread 1]	liblinux.Local.Shell.WindowsSubsystemShell: liblinux.Shell.ShellException: Echo command failing
   at liblinux.Shell.NativeShellBase.VerifyEcho(TimeSpan timeout)
   at liblinux.Shell.NativeShellBase.StartShellProcess(TimeSpan timeout)

```

**Comment by xyzhai-pro** [comment]
could you solve it?

**Comment by xyzhai-pro** [comment]
you have solved it?

**Comment by halim2209** [comment]
@xyzhai-pro: Unfortunately no.

I have configured openssh_server on port 23 in the WSL instance and use the Remote Manager in Visual Studio. Now VS can connect to WSL and run CMake commands but project still does not work correctly due to some other misbehaviour where the CMake targets are not properly detected and the project view shows only the CMake related files (CMakeLists.txt, CMakePresets.json and some included *.cmake files), but no .cpp or .h.

The same project can be configured on Windows without any issues.

**Comment by trojancai** [comment]
I happened to encounter the same error, have you solved it now?

**Comment by halim2209** [comment]
> I happened to encounter the same error, have you solved it now?

I could not find a solution to this problem. I have since switched to using VSCode via SSH instead of VS which makes it difficult to work with due to IntelliSense not behaving as maturely as it does with VS.

**Comment by SKYlake233** [comment]
when I use ubuntu20.04  it failed, i install ubuntu22 ,so it works ,I dont know why

**Comment by jjedwa165** [comment]
I did some googling on this and I think is what's happening is explained in the logs
```
Writing "echo 9c00b7b8-03b2-468f-9e47-4a0ad9e23c54" to the 242ac014-8208-45a1-9b60-e1329cafc4ce shell
Read async: 242ac014-8208-45a1-9b60-e1329cafc4ce
Error Received: 'your 131072x1 screen size is bogus. expect trouble'
```
VS is trying to complete an echo test, but getting back `your 131072x1 screen size is bogus`.  Best clue from [Here](https://unix.stackexchange.com/questions/259529/your-screen-size-is-bogus-expect-trouble) is the `procps` library completes a check of the screen width and gets echo's that error instead of what VS is expecting. 

Only way to reallly "fix" it would be to patch the library I think
