### ISSUE TITLE
wsl -u can only recognize users from /etc/passwd, not users existing elsewhere in the password database

### ISSUE THREAD

**Issue by cerebrate** [microsoft/WSL#9649]
### Version

Microsoft Windows [Version 10.0.22621.1105]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.1.0-rc6-20221125-1-microsoft-custom-WSL

### Distro Version

Debian sid

### Other Software

WSL version: 1.1.3.0
Kernel version: 5.15.90.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1105

### Repro Steps

1. To repro this issue, your system must have at least one user which is in the password database, but which originates from a source other than /etc/passwd. I originally ran into this issue when experimenting with configuring _systemd-homed_ to work under WSL, but the same issue occurs when attempting to use a dynamic user (for example, the _msmtpd_ user automatically created by _systemd_ when the _msmtp_ package is installed under Debian) or one created by any add-ons which extend the user database.

2. Having such a user created, attempt to start a shell as it:

`wsl -u username`

Such users cannot be used as the default user in `/etc/wsl.conf`; if one is set there, the same error message results as in "actual behavior", below, and "root" is substituted.

### Expected Behavior

Successful creation of a shell running as the specified user within WSL.

### Actual Behavior

```
C:\Users\avatar>wsl -u avatar
<3>WSL (221973) ERROR: CreateProcessEntryCommon:347: getpwnam(avatar) failed 0
User not found.
Error code: Wsl/WSL_E_USER_NOT_FOUND
```

It appears that the -u switch to `wsl` only recognizes users present in /etc/passwd, and not those present in the overall user database. As can be further seen, the Linux distribution itself has no problem logging in such users (run `wsl -u root /bin/login` and login manually), and such users do appear to the Linux-side `getpwnam` function call:

```
❯ python
Python 3.11.2 (main, Feb 12 2023, 00:48:52) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pwd
>>> pwd.getpwnam('avatar')
pwd.struct_passwd(pw_name='avatar', pw_passwd='x', pw_uid=1000, pw_gid=1000, pw_gecos='Alistair Young', pw_dir='/home/avatar', pw_shell='/bin/zsh')
```

(Presumably this may be an issue as WSL does not wait for systemd to start up before creating shells, and as such finding users located elsewhere than the local file may be problematic. Nonetheless, it's an issue.)

**Comment by benhillis** [comment]
WSL actually does wait for systemd to start before creating shells, and we're calling the getpwnam with whatever was passed to wsl.exe, so something funny is going on...

**Comment by cerebrate** [comment]
Hrm. I suspect we may be using different definitions of systemd having started up, because on my system (which is, granted, unusually slow), it can take some seconds for a system dbus to become available and rather longer for `systemctl status` to report _running_ .

(Indeed, if I don't start a persistent shell or other command, WSL will shut itself down before systemd even reaches _running_, although that says more about the antiquity of my hardware than anything else.)

But I note that calling getpwnam() from inside WSL immediately after WSL startup doesn't work either:

```
C:\Users\avatar>wsl python -c 'import pwd ; print (pwd.getpwnam("avatar"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: "getpwnam(): name not found: 'avatar'"

C:\Users\avatar>wsl systemctl is-system-running
Failed to connect to bus: No such file or directory
```

On the other hand, if I do create a persistent shell and then start entering commands immediately, I see this:

```
C:\Users\avatar>wsl /bin/sh
$ python -c 'import pwd ; print (pwd.getpwnam("avatar"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: "getpwnam(): name not found: 'avatar'"
$ systemctl is-system-running
Failed to connect to bus: No such file or directory
```

and then after a brief wait

```
$ python -c 'import pwd ; print (pwd.getpwnam("avatar"))'
pwd.struct_passwd(pw_name='avatar', pw_passwd='x', pw_uid=1000, pw_gid=1000, pw_gecos='Alistair Young', pw_dir='/home/avatar', pw_shell='/bin/zsh')
$  systemctl is-system-running
running
```

Which is consistent with systemd (or rather, systemd-homed) not having started up yet in the first instance and thus being able to supply its data to _nss(5)_.

**Comment by cerebrate** [comment]
...on the gripping hand, if I leave the above session running, go to a new command prompt, and try to start a new shell as the user in question, it still fails:

```
C:\Users\avatar>wsl -u avatar /bin/sh
<3>WSL (1201) ERROR: CreateProcessEntryCommon:347: getpwnam(avatar) failed 0
User not found.
Error code: Wsl/WSL_E_USER_NOT_FOUND

C:\Users\avatar>wsl id avatar
uid=1000(avatar) gid=1000(avatar) groups=1000(avatar),0(root),4(adm),20(dialout),24(cdrom),27(sudo),30(dip),40(src),46(plugdev),50(staff),100(users),999(docker),118(lpadmin),998(lxd),996(windows)

C:\Users\avatar>wsl -u avatar /bin/sh
<3>WSL (1232) ERROR: CreateProcessEntryCommon:347: getpwnam(avatar) failed 0
User not found.
Error code: Wsl/WSL_E_USER_NOT_FOUND
```

even though the distro itself demonstrably knows about the user. Which I suppose confirms the something funny hypothesis. :grin:

**Comment by rashedmyt** [comment]
I am also facing the same error. However my use case is different

The username which I am using is associated with Active Directory. I've configured the WSL image with all the necessary configs for kerberos, sssd etc.

Does this issue cover this use case also?

**Comment by cerebrate** [comment]
I suspect that it's the same underlying issue, but I don't know how the WSL team are going to want to treat it.

**Comment by rashedmyt** [comment]
Hi @benhillis @pmartincic, Any update regarding this issue?

**Comment by cerebrate** [comment]
So I've been looking at this again, prompted by @rashedmyt 's comment over on #9650, with the benefit of delicious, delicious source code, and the conclusion I've come to is that this and various other issues I've raised in the past all come down to the same issue: namely, _systemd_-startup race conditions.

I was wrong about the cause, though. I had previously thought it was because of the timeout for _systemd_ to have started up, but that seems fine: on my current hardware, my _systemd_ and all its services starts up in 6.8 seconds (per _systemd-analyze_), and the default timeout for _systemd_ startup is 10 seconds (per [WslDistributionConfig.h here](https://github.com/microsoft/WSL/blob/e8145a7ee9fd4334e6235383c5380b6f82fa2350/src/linux/init/WslDistributionConfig.h#L55) and its use over in [init.cpp here](https://github.com/microsoft/WSL/blob/e8145a7ee9fd4334e6235383c5380b6f82fa2350/src/linux/init/init.cpp#L3375)). More to the point, you can lengthen this timeout with the currently undocumented setting:

```
[boot]
initTimeout=20
```

Without seeing any changes.

Where I _think_ the problem lies (and I say this tentatively, because C++/COM isn't my usual field and I'm still trying to figure out the intricacies here) is up here in [InitEntryUtilityVm in init.cpp](https://github.com/microsoft/WSL/blob/e8145a7ee9fd4334e6235383c5380b6f82fa2350/src/linux/init/init.cpp#L2303), where per a comment:

```
            //
            // Wait to boot the distro init process until the first session leader has been created.
            // This ensures that the entire boot is not done when a distro is trigger-started by accessing \\wsl.localhost.
            //
```

I'm still trying to trace my way through the relevant WSL code, but empirically, starting from the distribution not running, the **first** session I create with just `wsl` fails with the various signs of _systemd_ not being fully started up; usually, that it can't access my home directory because the NFS shares aren't mounted yet.

```
wsl: Failed to start the systemd user session for 'avatar'. See journalctl for more details.
<3>WSL (16 - Relay) ERROR: CreateProcessCommon:790: chdir(/home/avatar) failed 2
```

If I do nothing but wait and start a **second** session, again just with `wsl`, a few seconds later, it **succeeds**.

I attribute this to the first session triggering the distro init/_systemd_ boot and it not progressing fast enough to provide services to  that first session, but it completing and the various services being ready for the second session. (This behavior would also explain the _getpwnam()_ behavior seen earlier in this issue.)

Unfortunately, I haven't yet managed to figure out how to adjust the code to ensure that distro init always starts before any sessions do and thus test my hypothesis.

(And, frankly, doing the complete boot when I wander into \\wsl.localhost is not only something I'd find easier to live with - it's  probably up anyway, and quick enough when it isn't - but might even be desirable for me because having _systemd_ & services running lets me do things like access NFS shares in Debian where they live via Explorer, which is a nice bonus feature.)
