### ISSUE TITLE
[.vscode-server] Installing an extension creates EACCES error.

### ISSUE THREAD

**Issue by Lofty-Brambles** [microsoft/WSL#9712]
### Version

Microsoft Windows [Version 10.0.19044.2604]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC))

### Distro Version

Ubuntu 22.04

### Other Software

Visual Studio Code (1.75.1) with WSL extension v0.75.3

### Repro Steps

Not sure.
Simply install Ubuntu 22.04 as the distro, install the WSL extension, and tried to install another extension.

### Expected Behavior

N/A. Simple download.

### Actual Behavior

EACCES: EACCES: permission denied, rename '/root/.vscode-server/extensions/.dbcca4b5-7c2b-4473-ba38-6bad1c859460' -> '/root/.vscode-server/extensions/botloader.botloader-vscode-0.11.0'

### Diagnostic Logs

```
2023-02-28 18:15:04.072 [info] [remote-connection][ExtensionHost][b6ad5…] high roundtrip time: 1013ms (1 of 5 recent samples)
2023-02-28 18:18:27.041 [info] Electron sandbox mode is enabled!
2023-02-28 18:18:27.188 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'commentsResolvedState' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-02-28 18:18:28.471 [info] Invoking resolveAuthority(wsl)...
2023-02-28 18:18:28.474 [info] [LocalProcess0][resolveAuthority(wsl,1)][0ms] obtaining proxy...
2023-02-28 18:18:32.240 [info] [LocalProcess0][resolveAuthority(wsl,1)][3766ms] invoking...
2023-02-28 18:18:33.897 [info] [LocalProcess0][resolveAuthority(wsl,1)][5423ms] waiting...
2023-02-28 18:18:34.985 [info] [LocalProcess0][resolveAuthority(wsl,1)][6510ms] waiting...
2023-02-28 18:18:36.513 [info] [LocalProcess0][resolveAuthority(wsl,1)][8040ms] waiting...
2023-02-28 18:18:37.246 [info] [LocalProcess0][resolveAuthority(wsl,1)][8772ms] waiting...
2023-02-28 18:18:38.248 [info] [LocalProcess0][resolveAuthority(wsl,1)][9775ms] waiting...
2023-02-28 18:18:39.244 [info] [LocalProcess0][resolveAuthority(wsl,1)][10771ms] waiting...
2023-02-28 18:18:39.603 [info] [LocalProcess0][resolveAuthority(wsl,1)][11130ms] returned 127.0.0.1:57704
2023-02-28 18:18:39.605 [info] resolveAuthority(wsl) returned '127.0.0.1:57704' after 11133 ms
2023-02-28 18:18:39.926 [info] Creating a socket (renderer-Management-e7c99c9e-2df8-439d-a1ab-8a15f65c3590)...
2023-02-28 18:18:39.940 [info] Creating a socket (renderer-ExtensionHost-0bf9cbba-c04f-4ae6-82d7-bef273078f57)...
2023-02-28 18:18:41.113 [info] Creating a socket (renderer-Management-e7c99c9e-2df8-439d-a1ab-8a15f65c3590) was successful after 1187 ms.
2023-02-28 18:18:41.562 [info] Creating a socket (renderer-ExtensionHost-0bf9cbba-c04f-4ae6-82d7-bef273078f57) was successful after 1622 ms.
2023-02-28 18:18:46.146 [warning] Webgl could not be loaded. Falling back to the canvas renderer type. {}
2023-02-28 18:18:47.843 [error] Cannot read properties of undefined (reading 'setAtlas'): TypeError: Cannot read properties of undefined (reading 'setAtlas')
    at p._refreshCharAtlas (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/node_modules.asar/xterm-addon-webgl/lib/xterm-addon-webgl.js:1:20362)
    at p._handleOptionsChanged (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/node_modules.asar/xterm-addon-webgl/lib/xterm-addon-webgl.js:1:19062)
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/node_modules.asar/xterm-addon-webgl/lib/xterm-addon-webgl.js:1:15765
    at t.EventEmitter.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/node_modules.asar/xterm/lib/xterm.js:1:139525)
    at a.i (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/node_modules.asar/xterm/lib/xterm.js:1:266845)
    at e.Terminal.s (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/node_modules.asar/xterm/lib/xterm.js:1:273006)
    at new h (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1889:9476)
    at o.j (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:611:1296)
    at o.createInstance (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:611:788)
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2542:38375
    at g.invoke (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1882:21348
    at g.invoke (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at L.handleReady (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1092:20599)
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1697:8388
    at g.invoke (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at g.invoke (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at Z (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:793)
    at A.t (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:1577)
    at A.s (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:1471)
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:552:1351
    at g.invoke (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at r.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:15219)
    at E (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:19285)
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:17273
    at g.invoke (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at d.acceptChunk (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:12950)
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:12237
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:642:38242
    at g.invoke (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at i.onload (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:642:36509)
2023-02-28 18:18:48.187 [info] [perf] Render performance baseline is 662ms
2023-02-28 18:18:56.973 [error] Cannot read properties of undefined (reading 'setAtlas'): TypeError: Cannot read properties of undefined (reading 'setAtlas')
    at p._refreshCharAtlas (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/node_modules.asar/xterm-addon-webgl/lib/xterm-addon-webgl.js:1:20362)
    at p._handleOptionsChanged (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/node_modules.asar/xterm-addon-webgl/lib/xterm-addon-webgl.js:1:19062)
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/node_modules.asar/xterm-addon-webgl/lib/xterm-addon-webgl.js:1:15765
    at t.EventEmitter.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/node_modules.asar/xterm/lib/xterm.js:1:139525)
    at a.i (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/node_modules.asar/xterm/lib/xterm.js:1:266845)
    at e.Terminal.s (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/node_modules.asar/xterm/lib/xterm.js:1:273006)
    at new h (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1889:9476)
    at o.j (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:611:1296)
    at o.createInstance (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:611:788)
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2542:38375
    at g.invoke (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1882:21348
    at g.invoke (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at L.handleReady (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1092:20599)
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1697:8388
    at g.invoke (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at g.invoke (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at Z (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:793)
    at A.t (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:1577)
    at A.s (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:1471)
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:552:1351
    at g.invoke (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at r.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:15219)
    at E (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:19285)
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:17273
    at g.invoke (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at d.acceptChunk (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:12950)
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:12237
    at vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:642:38242
    at g.invoke (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at i.onload (vscode-file://vscode-app/c:/Users/hp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:642:36509)
2023-02-28 18:19:20.494 [error] EACCES: EACCES: permission denied, rename '/root/.vscode-server/extensions/.dbcca4b5-7c2b-4473-ba38-6bad1c859460' -> '/root/.vscode-server/extensions/botloader.botloader-vscode-0.11.0'
    at Y.t (/root/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/server/node/server.main.js:149:86362)
    at async Y.extractUserExtension (/root/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/server/node/server.main.js:149:83665)
    at async U.s (/root/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/server/node/server.main.js:149:89446)
    at async U.h (/root/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/server/node/server.main.js:149:90672)
2023-02-28 18:19:20.504 [error] EACCES: permission denied, rename '/root/.vscode-server/extensions/.dbcca4b5-7c2b-4473-ba38-6bad1c859460' -> '/root/.vscode-server/extensions/botloader.botloader-vscode-0.11.0': EACCES: EACCES: permission denied, rename '/root/.vscode-server/extensions/.dbcca4b5-7c2b-4473-ba38-6bad1c859460' -> '/root/.vscode-server/extensions/botloader.botloader-vscode-0.11.0'
    at Y.t (/root/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/server/node/server.main.js:149:86362)
    at async Y.extractUserExtension (/root/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/server/node/server.main.js:149:83665)
    at async U.s (/root/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/server/node/server.main.js:149:89446)
    at async U.h (/root/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out/vs/server/node/server.main.js:149:90672)
2023-02-28 18:22:43.026 [info] [remote-connection][Management   ][e7c99…] high roundtrip time: 1011ms (1 of 5 recent samples)
2023-02-28 18:22:43.027 [info] [remote-connection][ExtensionHost][0bf9c…] high roundtrip time: 1096ms (1 of 5 recent samples)
2023-02-28 18:23:43.058 [info] [remote-connection][Management   ][e7c99…] high roundtrip time: 1120ms (2 of 5 recent samples)
2023-02-28 18:23:43.060 [info] [remote-connection][ExtensionHost][0bf9c…] high roundtrip time: 1122ms (2 of 5 recent samples)
2023-02-28 18:30:57.973 [info] [remote-connection][ExtensionHost][0bf9c…] high roundtrip time: 15023ms (3 of 5 recent samples)
2023-02-28 18:30:57.979 [info] [remote-connection][Management   ][e7c99…] high roundtrip time: 15030ms (3 of 5 recent samples)
```

**Comment by benhillis** [comment]
The vscode remote guys should probably have a first look at this.

https://github.com/microsoft/vscode-remote-release
