### ISSUE TITLE
Docker Desktop and Docker in general crashing and hanging. Errors wont go away even after full wipe

### ISSUE THREAD

**Issue by memetrusidovski** [microsoft/WSL#9974]
### Windows Version

Microsoft Windows [Version 10.0.22621.1555]

### WSL Version

1.2.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Default Distribution: Ubuntu Default Version: 2

### Distro Version

Release:        22.04

### Repro Steps

installed updates. docker settings dont open either

### Expected Behavior

it working

### Actual Behavior

no matter what ive tried in the end i still get this error "wsl integration with distro ubuntu unexpectedly stopped with exit code 1" in a popup. i've tried rolling back to old versions, whipping everything, deleting all antivirus programs, trying debian, etc. Still nothing. if anyone has an idea id apprciate it. it was working perfectly fine until my pc auto updated the other night. i can somewhat get docker working in ubuntu through the terminal but it just crashes once i close it. 

### Diagnostic Logs

System.InvalidOperationException:
distro stopped unexpectedly
at Docker.Engines.LinuxkitDaemonStartup.d__5.MoveNext() in C:\workspaces\PR-19568\src\github.com\docker\pinata\win\src\Docker.Engines\LinuxkitDaemonStartup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.Engines.WSL2.LinuxWSL2Engine.d__26.MoveNext() in C:\workspaces\PR-19568\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.ApiServices.StateMachines.TaskExtensions.d__0.MoveNext() in C:\workspaces\PR-19568\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.ApiServices.StateMachines.StartTransition.d__5.MoveNext() in C:\workspaces\PR-19568\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Docker.ApiServices.StateMachines.StartTransition.d__5.MoveNext() in C:\workspaces\PR-19568\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.ApiServices.StateMachines.EngineStateMachine.d__14.MoveNext() in C:\workspaces\PR-19568\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.Engines.Engines.d__22.MoveNext() in C:\workspaces\PR-19568\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 106

at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.Engines.Engines.d__22.MoveNext() in C:\workspaces\PR-19568\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 106

**Comment by benhillis** [comment]
/logs

Issue may also be more appropriate in the docker repo.

**Comment by memetrusidovski** [comment]
I tried posting there as well. in the end i factory reset my pc. i tried everything i could find online and everything everyone recommended. I've literally had the pc for a month lol. oh well, hopefully the problem gets patched if it was windows, WSL, or docker that was the culprit. I guess it had something to do with how WSL and docker connect

**Comment by QAnders** [comment]
See https://github.com/microsoft/WSL/issues/9429

You are far from alone...

**Comment by Biswa96** [comment]
@memetrusidovski Just curious. Would you like to check if the issue happens without docker desktop? For example, run `sudo service docker start` in one WSL session and `docker` in another. Or systemd will automatically run dockerd if enabled.

**Comment by MiikaH** [comment]
Not sure if it is related but I just started seeing similar hanging issue after installing Ubuntu 22.04 distro (and deleting old 20.04 afterwards) yesterday.

It seems like if I'm doing something that requires lots of file operations such as building a project inside a VSCode dev container within `\\wsl.localhost\Ubuntu-22.04\` it may randomly hang. Previously a year ago that was happening if I was doing same inside a Windows NTFS file system, but switching over to the WSL mount fixed it. Now it happens within the WLS mount too.

When it happened just moments ago I decided to wait it out to see what would happen:

![VMmemWSL 2023 04 17 - 16 41 13 15](https://user-images.githubusercontent.com/1881360/232505074-5efdfc8d-f475-457d-a186-dd2788255ea1.png)

Looksl ike VMmemVSL was using about 20 CPU threads worth CPU and reading from the SSD at about 1500-2500MB/s for about 3-5 minutes. So probably over >300GB worth disk reads (The Ubuntu distro is only 30GB), then it stopped and started responding again.

I Googled if someone else had seen the same issue and ended on this thread here.

**Comment by maikebing** [comment]
[WslLogs-2023-04-22_13-08-23.zip](https://github.com/microsoft/WSL/files/11300321/WslLogs-2023-04-22_13-08-23.zip)
